import{act,cleanup,render,screen,waitFor}from'@testing-library/react'
import userEvent from'@testing-library/user-event'
import{afterEach,expect,it,vi}from'vitest'
import{BridgeClientError,type SessionBridge}from'../bridge/client'
import type{ProjectDTO,SessionDTO}from'../generated/bridge'
import{SessionPage}from'./SessionPage'
afterEach(cleanup)
const U='01ARZ3NDEKTSV4RRFFQ69G5FAV',P='01ARZ3NDEKTSV4RRFFQ69G5FAA',now='2025-01-01T00:00:00Z',project:ProjectDTO={id:P,name:'Parent',projectCode:'ITM00001',type:'implementation',status:'active',createdAt:now,updatedAt:now,version:1},item:SessionDTO={id:U,projectId:P,title:'<img src=x onerror=alert(1)>',pinned:false,status:'active',createdAt:now,updatedAt:now,version:1}
const api=(x:Partial<SessionBridge>={}):SessionBridge=>({list:vi.fn().mockResolvedValue({items:[]}),create:vi.fn().mockResolvedValue(item),update:vi.fn().mockResolvedValue(item),delete:vi.fn().mockResolvedValue({deleted:true,id:'01ARZ3NDEKTSV4RRFFQ69G5FAV'}),...x})
it('hides sidebar delete for 月伴对话',async()=>{
 const companion={...item,title:'月伴对话'}
 render(<SessionPage project={project} bridge={api({list:vi.fn().mockResolvedValue({items:[companion]})})} onBack={vi.fn()}/>)
 expect(await screen.findByText('月伴对话')).toBeInTheDocument()
 expect(screen.queryByRole('button',{name:'删除会话 月伴对话'})).toBeNull()
})

it('loads parent-bound sessions, normalizes create, and renders markup inert',async()=>{const bridge=api(),user=userEvent.setup();render(<SessionPage project={project} bridge={bridge} onBack={vi.fn()}/>);expect(await screen.findByText('还没有会话')).toBeInTheDocument();expect(bridge.list).toHaveBeenCalledWith({projectId:P});await user.type(screen.getByLabelText('会话标题'),'  Moon   Tide  ');await user.click(screen.getByRole('button',{name:'创建会话'}));await waitFor(()=>expect(bridge.create).toHaveBeenCalledOnce());expect(vi.mocked(bridge.create).mock.calls[0][0]).toEqual({projectId:P,title:'Moon Tide'});expect(await screen.findByText(item.title)).toBeInTheDocument();expect(document.querySelector('img')).toBeNull()})
it('blocks busy re-entry and retains retry attempt',async()=>{let reject!:(e:unknown)=>void;const create=vi.fn().mockReturnValueOnce(new Promise<SessionDTO>((_,r)=>reject=r)).mockResolvedValue(item),bridge=api({create}),user=userEvent.setup();render(<SessionPage project={project} bridge={bridge} onBack={vi.fn()}/>);await screen.findByText('还没有会话');await user.type(screen.getByLabelText('会话标题'),'Demo');await user.click(screen.getByRole('button',{name:'创建会话'}));expect(screen.getByRole('button',{name:'创建中…'})).toBeDisabled();reject(new BridgeClientError('uncertain','TIMEOUT',true,'trace'));expect(await screen.findByText(/uncertain/)).toBeInTheDocument();await user.click(screen.getByRole('button',{name:'创建会话'}));await waitFor(()=>expect(create).toHaveBeenCalledTimes(2));expect(create.mock.calls[1][1]?.attempt).toBe(create.mock.calls[0][1]?.attempt)})
it('keeps a created session when a delayed stale retry resolves',async()=>{let resolveList!:(v:{items:SessionDTO[]})=>void,resolveCreate!:(v:SessionDTO)=>void;const list=vi.fn().mockRejectedValueOnce(new BridgeClientError('list failed','LIST_FAILED',true,'trace')).mockReturnValueOnce(new Promise(r=>resolveList=r)),create=vi.fn().mockReturnValue(new Promise<SessionDTO>(r=>resolveCreate=r)),bridge=api({list,create}),user=userEvent.setup();render(<SessionPage project={project} bridge={bridge} onBack={vi.fn()}/>);expect(await screen.findByText('list failed')).toBeInTheDocument();await user.type(screen.getByLabelText('会话标题'),'Created');await user.click(screen.getByRole('button',{name:'重试'}));expect(screen.getByRole('button',{name:'重试'})).toBeDisabled();await user.click(screen.getByRole('button',{name:'创建会话'}));expect(screen.queryByText('list failed')).toBeNull();expect(screen.getByRole('button',{name:'创建中…'})).toBeDisabled();await act(async()=>resolveCreate(item));expect(await screen.findByText(item.title)).toBeInTheDocument();await act(async()=>resolveList({items:[]}));expect(screen.getByText(item.title)).toBeInTheDocument();expect(list).toHaveBeenCalledTimes(2)})
it('ignores stale parent response and returns to parent',async()=>{let resolve!:(v:{items:SessionDTO[]})=>void;const old=api({list:vi.fn().mockReturnValue(new Promise(r=>resolve=r))}),back=vi.fn(),user=userEvent.setup(),view=render(<SessionPage project={project} bridge={old} onBack={back}/>);view.rerender(<SessionPage project={{...project,id:U,name:'Other'}} bridge={api()} onBack={back}/>);expect(await screen.findByText('还没有会话')).toBeInTheDocument();resolve({items:[item]});await Promise.resolve();expect(screen.queryByText(item.title)).toBeNull();await user.click(screen.getByRole('button',{name:/返回项目/}));expect(back).toHaveBeenCalledOnce()})
it('does not let an old project create block or populate the next project',async()=>{let resolveCreate!:(v:SessionDTO)=>void;const create=vi.fn().mockReturnValue(new Promise<SessionDTO>(r=>resolveCreate=r)),list=vi.fn().mockResolvedValue({items:[]}),bridge=api({list,create}),user=userEvent.setup(),view=render(<SessionPage project={project} bridge={bridge} onBack={vi.fn()}/>);await screen.findByText('还没有会话');await user.type(screen.getByLabelText('会话标题'),'Old project');await user.click(screen.getByRole('button',{name:'创建会话'}));expect(screen.getByRole('button',{name:'创建中…'})).toBeDisabled();const next={...project,id:U,name:'Other'};view.rerender(<SessionPage project={next} bridge={bridge} onBack={vi.fn()}/>);expect(await screen.findByText('还没有会话')).toBeInTheDocument();expect(list).toHaveBeenLastCalledWith({projectId:U});expect(screen.getByRole('button',{name:'创建会话'})).toBeEnabled();await act(async()=>resolveCreate(item));expect(screen.queryByText(item.title)).toBeNull()})
