import React,{useEffect,useRef,useState}from'react'
import{BridgeClientError,createMutationAttempt,type MutationAttempt,type SessionBridge}from'../bridge/client'
import type{ProjectDTO,SessionCreatePayload,SessionDTO}from'../generated/bridge'
import{normalizeProjectName}from'../project/ProjectPage'
const problem=(e:unknown)=>e instanceof BridgeClientError?e:new BridgeClientError(e instanceof Error?e.message:'请求失败','CLIENT_ERROR',false,'renderer')
const ordered=(v:SessionDTO[])=>[...v].sort((a,b)=>a.createdAt.localeCompare(b.createdAt)||a.id.localeCompare(b.id))
type Retained={signature:string;attempt:MutationAttempt<SessionCreatePayload>}
export function SessionPage({project,bridge,onBack}:{project:ProjectDTO;bridge:SessionBridge;onBack:()=>void}):React.JSX.Element{
 const[items,setItems]=useState<SessionDTO[]>([]),[title,setTitle]=useState(''),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState<BridgeClientError>(),mounted=useRef(true),token=useRef(0),busyRef=useRef(false),retained=useRef<Retained|undefined>(undefined),projectRef=useRef(project.id);projectRef.current=project.id
 const load=async()=>{if(busyRef.current)return;const current=++token.current;setLoading(true);try{const r=await bridge.list({projectId:project.id});if(mounted.current&&current===token.current){setItems(ordered(r.items));setError(undefined)}}catch(e){if(mounted.current&&current===token.current)setError(problem(e))}finally{if(mounted.current&&current===token.current)setLoading(false)}}
 useEffect(()=>{mounted.current=true;token.current++;busyRef.current=false;retained.current=undefined;setItems([]);setTitle('');setBusy(false);setError(undefined);void load();return()=>{mounted.current=false;token.current++}},[bridge,project.id])
 const submit=async(e:React.FormEvent)=>{e.preventDefault();if(busyRef.current)return;const normalized=normalizeProjectName(title);if(!normalized||Array.from(normalized).length>200)return;const submittedProject=project.id,payload:SessionCreatePayload={projectId:submittedProject,title:normalized},signature=JSON.stringify(payload),attempt=retained.current?.signature===signature?retained.current.attempt:createMutationAttempt('session.create',payload),current=++token.current;retained.current={signature,attempt};busyRef.current=true;setLoading(false);setBusy(true);setError(undefined);setTitle(normalized);try{const created=await bridge.create(attempt.payload as SessionCreatePayload,{attempt});if(mounted.current&&current===token.current&&projectRef.current===submittedProject){retained.current=undefined;setItems(v=>ordered([...v.filter(x=>x.id!==created.id),created]));setTitle('');setError(undefined)}}catch(x){const issue=problem(x);if(mounted.current&&current===token.current&&projectRef.current===submittedProject){setError(issue);if(!issue.retryable)retained.current=undefined}}finally{if(mounted.current&&current===token.current&&projectRef.current===submittedProject){busyRef.current=false;setBusy(false)}}}
 return <div className="shell project-page"><button onClick={onBack}>← 返回项目</button><header className="brand"><h1>{project.name} · 会话</h1></header><div className="project-layout"><section className="project-create"><h2>新建会话</h2><form onSubmit={e=>void submit(e)}><fieldset disabled={busy}><label>会话标题<input value={title} onChange={e=>{setTitle(e.target.value);retained.current=undefined}}/></label><button className="primary" disabled={busy}>{busy?'创建中…':'创建会话'}</button></fieldset></form>{error&&<div role="alert">{error.message}{error.retryable&&<button disabled={busy||loading} onClick={()=>void load()}>重试</button>}</div>}</section><section className="project-list"><h2>会话列表</h2>{loading&&!items.length?<p role="status">正在载入会话…</p>:items.length?<div className="project-cards">{items.map(v=><article className="project-card" key={v.id}><h3>{v.title}</h3><p>活跃 · {new Date(v.createdAt).toLocaleString()}</p></article>)}</div>:<div className="empty"><b>还没有会话</b></div>}</section></div></div>
}
