import { expect, it, vi } from 'vitest'
import { createChatBridge, createMutationAttempt, createProviderBridge, type MutationAttempt, type WebViewTransport } from './client'
const U='01ARZ3NDEKTSV4RRFFQ69G5FAV'
const list={items:[]}
function harness(result:unknown=list){let listener:(e:MessageEvent)=>void=()=>{};const sent:any[]=[];const transport:WebViewTransport={addEventListener:(_t,l)=>{listener=l},removeEventListener:vi.fn(),postMessage:m=>{sent.push(m);queueMicrotask(()=>listener(new MessageEvent('message',{data:{v:'1.0',kind:'response',id:U,requestId:(m as any).id,ok:true,payload:result}})))} };return{sent,bridge:createProviderBridge(transport)}}
it('reuses idempotency and the deeply immutable snapshot while request and trace IDs stay fresh',async()=>{const {sent,bridge}=harness({deleted:true}),payload={id:U,expectedVersion:1,nested:{values:['a']}} as any,attempt=createMutationAttempt('provider.delete',payload);expect(Object.isFrozen(attempt.payload.nested.values)).toBe(true);payload.nested.values[0]='changed';await bridge.delete(attempt.payload as any,{attempt});await bridge.delete(structuredClone(attempt.payload) as any,{attempt});expect(sent[0].payload).toEqual(sent[1].payload);expect(sent[0].idempotencyKey).toBe(sent[1].idempotencyKey);expect(sent[0].id).not.toBe(sent[1].id);expect(sent[0].traceId).not.toBe(sent[1].traceId)})
it('rejects changed or fabricated attempts before transport',async()=>{const {sent,bridge}=harness({deleted:true}),payload={id:U,expectedVersion:1},attempt=createMutationAttempt('provider.delete',payload);expect(()=>bridge.delete({...payload,expectedVersion:2},{attempt})).toThrow(/不匹配/);const fabricated={...attempt,payload:{...payload}} as MutationAttempt<typeof payload>;expect(()=>bridge.delete(payload,{attempt:fabricated})).toThrow(/不匹配/);expect(sent).toHaveLength(0)})
it('different payload attempts get different idempotency keys',async()=>{const {sent,bridge}=harness({deleted:true}),a={id:U,expectedVersion:1},b={id:U,expectedVersion:2};await bridge.delete(a,{attempt:createMutationAttempt('provider.delete',a)});await bridge.delete(b,{attempt:createMutationAttempt('provider.delete',b)});expect(sent[0].idempotencyKey).not.toBe(sent[1].idempotencyKey)})
it('adds deadlines only and validates method results',async()=>{const {sent,bridge}=harness();await bridge.list();expect(sent[0].deadlineMs).toBe(8000);expect(sent[0]).not.toHaveProperty('idempotencyKey');const bad=harness({items:[{id:'bad'}]});await expect(bad.bridge.list()).rejects.toMatchObject({code:'INVALID_BRIDGE_RESULT'})})
it('submits a credential once without retaining it in the caller payload',async()=>{const result={credentialSubmissionId:U,providerId:U,expiresAt:new Date().toISOString(),expiresInSeconds:60},seen:string[]=[];let listener:(e:MessageEvent)=>void=()=>{};const transport:WebViewTransport={addEventListener:(_t,l)=>{listener=l},removeEventListener:vi.fn(),postMessage:m=>{seen.push((m as any).payload.credential);queueMicrotask(()=>listener(new MessageEvent('message',{data:{v:'1.0',kind:'response',id:U,requestId:(m as any).id,ok:true,payload:result}})))}};const payload:any={scope:{providerId:U},request:{id:U,expectedVersion:1},credential:'one-use'};await createProviderBridge(transport).submitCredential(payload);expect(seen).toEqual(['one-use']);expect(payload.credential).toBe('')})
it('clears the credential payload when transport throws',async()=>{const transport:WebViewTransport={addEventListener:vi.fn(),removeEventListener:vi.fn(),postMessage:()=>{throw new Error('transport')}};const payload:any={scope:{providerId:U},request:{id:U,expectedVersion:1},credential:'one-use'};await expect(createProviderBridge(transport).submitCredential(payload)).rejects.toMatchObject({code:'BRIDGE_UNAVAILABLE'});expect(payload.credential).toBe('')})
it('preserves valid structured errors and rejects malformed envelopes',async()=>{let listener:(e:MessageEvent)=>void=()=>{};const t:WebViewTransport={addEventListener:(_t,l)=>{listener=l},removeEventListener:vi.fn(),postMessage:m=>queueMicrotask(()=>listener(new MessageEvent('message',{data:{v:'1.0',kind:'response',id:U,requestId:(m as any).id,ok:false,error:{code:'STORAGE_BUSY',message:'busy',retryable:true,correlationId:'trace'}}})))};await expect(createProviderBridge(t).list()).rejects.toMatchObject({code:'STORAGE_BUSY',retryable:true});const bad:WebViewTransport={...t,postMessage:m=>queueMicrotask(()=>listener(new MessageEvent('message',{data:{v:'1.0',kind:'response',id:U,requestId:(m as any).id,ok:true,payload:list,extra:true}})))};await expect(createProviderBridge(bad).list()).rejects.toMatchObject({code:'INVALID_BRIDGE_RESPONSE'})})
it('times out and ignores a late response',async()=>{vi.useFakeTimers();let listener:(e:MessageEvent)=>void=()=>{},request:any;const transport:WebViewTransport={addEventListener:(_t,l)=>{listener=l},removeEventListener:vi.fn(),postMessage:m=>{request=m}};const promise=createProviderBridge(transport,1).list();const assertion=expect(promise).rejects.toMatchObject({code:'REQUEST_DEADLINE_EXCEEDED',retryable:true});await vi.advanceTimersByTimeAsync(252);await assertion;listener(new MessageEvent('message',{data:{v:'1.0',kind:'response',id:U,requestId:request.id,ok:true,payload:list}}));await vi.runAllTimersAsync();vi.useRealTimers()})

function chatHarness(){const listeners=new Set<(e:MessageEvent)=>void>(),sent:any[]=[];const emit=(data:unknown)=>{for(const l of [...listeners])l(new MessageEvent('message',{data}))};const transport:WebViewTransport={addEventListener:(_t,l)=>listeners.add(l as any),removeEventListener:(_t,l)=>listeners.delete(l as any),postMessage:m=>sent.push(m)};return{sent,emit,transport}}
const event=(sequence:number,type='delta',extra:object={delta:{text:'x'}})=>({v:'1.0',kind:'event',id:U,streamId:U,sequence,type,...extra})
it('replays a valid immediate event after chat.start continuation registers',async()=>{const h=chatHarness(),seen:any[]=[];const promise=createChatBridge(h.transport).start({providerId:U,modelId:'m',messages:[{role:'user',content:'x'}]},e=>seen.push(e));const request=h.sent[0];h.emit(event(1));h.emit({v:'1.0',kind:'response',id:U,requestId:request.id,ok:true,payload:{streamId:U}});await promise;expect(seen.map(e=>e.sequence)).toEqual([1])})
it('rejects malformed, duplicate, out-of-order, and post-terminal events',async()=>{for(const events of [[event(1,'delta',{delta:{text:'x'},extra:true})],[event(2)],[event(1),event(1)],[event(1,'completed',{}),event(2)]]){const h=chatHarness(),seen:any[]=[];const p=createChatBridge(h.transport).start({providerId:U,modelId:'m',messages:[{role:'user',content:'x'}]},e=>seen.push(e));h.emit({v:'1.0',kind:'response',id:U,requestId:h.sent[0].id,ok:true,payload:{streamId:U}});await p;events.forEach(h.emit);expect(seen.length).toBeLessThanOrEqual(2);expect(seen.filter(e=>['completed','cancelled','failed'].includes(e.type)).length).toBeLessThanOrEqual(1)}})
it('terminates an active stream locally on an event sequence violation',async()=>{const h=chatHarness(),seen:any[]=[];const p=createChatBridge(h.transport).start({providerId:U,modelId:'m',messages:[{role:'user',content:'x'}]},e=>seen.push(e));h.emit({v:'1.0',kind:'response',id:U,requestId:h.sent[0].id,ok:true,payload:{streamId:U}});await p;h.emit(event(1));h.emit(event(3));h.emit(event(2));expect(seen.map(e=>e.type)).toEqual(['delta','failed']);expect(seen[1]).toMatchObject({sequence:2,error:{code:'BRIDGE_EVENT_SEQUENCE_INVALID'}})})
it('terminates instead of hanging when invalid early events precede start response',async()=>{const h=chatHarness(),seen:any[]=[];const p=createChatBridge(h.transport).start({providerId:U,modelId:'m',messages:[{role:'user',content:'x'}]},e=>seen.push(e));h.emit(event(2));h.emit({v:'1.0',kind:'response',id:U,requestId:h.sent[0].id,ok:true,payload:{streamId:U}});await p;expect(seen).toHaveLength(1);expect(seen[0]).toMatchObject({type:'failed',sequence:1,error:{code:'BRIDGE_EARLY_EVENT_INVALID'}})})
it('terminates an active stream when a malformed event names that stream',async()=>{const h=chatHarness(),seen:any[]=[];const p=createChatBridge(h.transport).start({providerId:U,modelId:'m',messages:[{role:'user',content:'x'}]},e=>seen.push(e));h.emit({v:'1.0',kind:'response',id:U,requestId:h.sent[0].id,ok:true,payload:{streamId:U}});await p;h.emit(event(1,'delta',{delta:{text:'x'},extra:true}));expect(seen).toHaveLength(1);expect(seen[0]).toMatchObject({type:'failed',error:{code:'INVALID_BRIDGE_EVENT'}})})
it('keeps a cancelling stream active until Engine sends its terminal',async()=>{const h=chatHarness(),seen:any[]=[];const p=createChatBridge(h.transport).start({providerId:U,modelId:'m',messages:[{role:'user',content:'x'}]},e=>seen.push(e));h.emit({v:'1.0',kind:'response',id:U,requestId:h.sent[0].id,ok:true,payload:{streamId:U}});const stream=await p;const cancel=stream.cancel();const request=h.sent[1];h.emit({v:'1.0',kind:'response',id:U,requestId:request.id,ok:true,payload:{cancelled:true}});await expect(cancel).resolves.toBe(true);h.emit(event(1,'cancelled',{}));expect(seen.map(e=>e.type)).toEqual(['cancelled'])})
it('closes terminal ownership before invoking a throwing listener',async()=>{const h=chatHarness(),calls:any[]=[];const p=createChatBridge(h.transport).start({providerId:U,modelId:'m',messages:[{role:'user',content:'x'}]},e=>{calls.push(e);throw new Error('listener')});h.emit({v:'1.0',kind:'response',id:U,requestId:h.sent[0].id,ok:true,payload:{streamId:U}});await p;expect(()=>h.emit(event(1,'completed',{}))).toThrow('listener');expect(()=>h.emit(event(2,'cancelled',{}))).not.toThrow();expect(calls).toHaveLength(1)})
it('chat requests timeout and dispose rejects pending and removes its single listener',async()=>{vi.useFakeTimers();const h=chatHarness(),bridge=createChatBridge(h.transport,1);const timed=expect(bridge.start({providerId:U,modelId:'m',messages:[{role:'user',content:'x'}]},()=>{})).rejects.toMatchObject({code:'REQUEST_DEADLINE_EXCEEDED'});await vi.advanceTimersByTimeAsync(252);await timed;const pending=expect(bridge.start({providerId:U,modelId:'m',messages:[{role:'user',content:'x'}]},()=>{})).rejects.toMatchObject({code:'BRIDGE_UNAVAILABLE'});bridge.dispose();await pending;vi.useRealTimers()})
