import type * as DTO from '../generated/bridge'

export interface OfficeContracts {
 'office.artifact.chart': [DTO.OfficeArtifactChartPayload, DTO.OfficeArtifactChartResult]
 'office.artifact.patchChart': [DTO.OfficeArtifactPatchChartPayload, DTO.OfficeArtifactPatchChartResult]
 'office.artifact.refresh': [DTO.OfficeArtifactRefreshPayload, DTO.OfficeArtifactRefreshResult]
 'office.storage.usage': [DTO.OfficeStorageUsagePayload, DTO.OfficeStorageUsageResult]
 'office.storage.sweep': [DTO.OfficeStorageSweepPayload, DTO.OfficeStorageSweepResult]
 'office.artifact.replaceImage': [DTO.OfficeArtifactReplaceImagePayload, DTO.OfficeArtifactReplaceImageResult]
 'office.artifact.diff': [DTO.OfficeArtifactDiffPayload, DTO.OfficeArtifactDiffResult]
 'office.artifact.patchRange': [DTO.OfficeArtifactPatchRangePayload, DTO.OfficeArtifactPatchRangeResult]
 'office.metric.capture': [DTO.OfficeMetricCapturePayload, DTO.OfficeMetricCaptureResult]
 'office.metric.list': [DTO.OfficeMetricListPayload, DTO.OfficeMetricListResult]
 'office.metric.apply': [DTO.OfficeMetricApplyPayload, DTO.OfficeMetricApplyResult]
 'office.bundle.create': [DTO.OfficeBundleCreatePayload, DTO.OfficeBundleCreateResult]
 'office.bundle.list': [DTO.OfficeBundleListPayload, DTO.OfficeBundleListResult]
 'office.bundle.export': [DTO.OfficeBundleExportPayload, DTO.OfficeBundleExportResult]
 'office.task.list': [DTO.OfficeTaskListPayload, DTO.OfficeTaskListResult]
 'office.task.create': [DTO.OfficeTaskCreatePayload, DTO.OfficeTaskCreateResult]
 'office.task.get': [DTO.OfficeTaskGetPayload, DTO.OfficeTaskGetResult]
 'office.task.sync': [DTO.OfficeTaskSyncPayload, DTO.OfficeTaskSyncResult]
 'office.task.update': [DTO.OfficeTaskUpdatePayload, DTO.OfficeTaskUpdateResult]
 'office.task.cancel': [DTO.OfficeTaskCancelPayload, DTO.OfficeTaskCancelResult]
 'office.artifact.import': [DTO.OfficeArtifactImportPayload, DTO.OfficeArtifactImportResult]
 'office.artifact.preview': [DTO.OfficeArtifactPreviewPayload, DTO.OfficeArtifactPreviewResult]
 'office.artifact.patch': [DTO.OfficeArtifactPatchPayload, DTO.OfficeArtifactPatchResult]
 'office.artifact.validate': [DTO.OfficeArtifactValidatePayload, DTO.OfficeArtifactValidateResult]
 'office.artifact.accept': [DTO.OfficeArtifactAcceptPayload, DTO.OfficeArtifactAcceptResult]
 'office.artifact.restore': [DTO.OfficeArtifactRestorePayload, DTO.OfficeArtifactRestoreResult]
 'office.artifact.export': [DTO.OfficeArtifactExportPayload, DTO.OfficeArtifactExportResult]
 'office.artifact.open': [DTO.OfficeArtifactOpenPayload, DTO.OfficeArtifactOpenResult]
 'office.artifact.readChunk': [DTO.OfficeArtifactReadChunkPayload, DTO.OfficeArtifactReadChunkResult]
 'office.renderer.probe': [DTO.OfficeRendererProbePayload, DTO.OfficeRendererProbeResult]
}
