// Package org implements the M9 slice-1 organization foundation (T-9.1.1 /
// T-9.1.2): the immutable org_id isolation root accepted by ADR-011 and the
// enterprise identity model accepted by ADR-012.
//
// Concept error taxonomy (04 错误目录, wire-alias only - the wire AppError
// contract per method is regenerated by the bridge schema pipeline):
//
//	M9-001 ORG_NOT_FOUND          M9-004 TEAMSPACE_NOT_FOUND
//	M9-002 ORG_SUSPENDED          M9-005 PRINCIPAL_EXPIRED
//	M9-003 CROSS_ORG_ACCESS_DENIED  M9-006 ROLE_BINDING_DENIED
//
// M9-003 is the uniform answer for every cross-org target - in-org
// not-found, other-org existing and missing-org-context all return the exact
// same sentinel so no existence side channel leaks (threat m9-01 / T-01).
package org

import (
	"context"
	"errors"
	"time"
)

// ConceptError is an M9 concept-taxonomy error (code + name).
type ConceptError struct {
	Code string
	Name string
}

func (e *ConceptError) Error() string { return e.Code + " " + e.Name }

func (e *ConceptError) Is(target error) bool {
	var other *ConceptError
	if errors.As(target, &other) {
		return other.Code == e.Code
	}
	return false
}

var (
	ErrOrgNotFound       = &ConceptError{"M9-001", "ORG_NOT_FOUND"}
	ErrOrgSuspended      = &ConceptError{"M9-002", "ORG_SUSPENDED"}
	ErrCrossOrgAccess    = &ConceptError{"M9-003", "CROSS_ORG_ACCESS_DENIED"}
	ErrSpaceNotFound     = &ConceptError{"M9-004", "TEAMSPACE_NOT_FOUND"}
	ErrPrincipalExpired  = &ConceptError{"M9-005", "PRINCIPAL_EXPIRED"}
	ErrRoleBindingDenied = &ConceptError{"M9-006", "ROLE_BINDING_DENIED"}
)

// Code extracts the M9 concept code when err carries one.
func Code(err error) string {
	var ce *ConceptError
	if errors.As(err, &ce) {
		return ce.Code
	}
	return ""
}

// Organization states (ADR-011): draft -> active -> suspended -> closed;
// suspended keeps Hold/audit and closed is never a physical delete.
const (
	OrgDraft     = "draft"
	OrgActive    = "active"
	OrgSuspended = "suspended"
	OrgClosed    = "closed"
)

// AllowedOrgTransition enforces the ADR-011 organization state machine.
func AllowedOrgTransition(from, to string) bool {
	switch from {
	case OrgDraft:
		return to == OrgActive || to == OrgClosed
	case OrgActive:
		return to == OrgSuspended || to == OrgClosed
	case OrgSuspended:
		return to == OrgActive || to == OrgClosed
	default: // closed is terminal - data stays in read-only sealed form
		return false
	}
}

// Role names (closed set). legal-officer is the D-5 Legal Hold authority.
const (
	RoleOrgAdmin     = "org-admin"
	RoleSpaceAdmin   = "space-admin"
	RoleOperator     = "operator"
	RoleApprover     = "approver"
	RoleAuditor      = "auditor"
	RoleLegalOfficer = "legal-officer"
	RoleMember       = "member"
)

// Organization is the isolation root row (migrations/0069).
type Organization struct {
	OrgID                string
	Name                 string
	State                string
	RetentionDays        int
	ResidencyPolicyDigest string
	CreatedAt            string
	UpdatedAt            string
}

// TeamSpace is an organization-scoped collaboration space.
type TeamSpace struct {
	SpaceID   string
	OrgID     string
	Name      string
	State     string
	CreatedAt string
	UpdatedAt string
}

// Principal states (ADR-012): active / suspended / expired / revoked.
const (
	PrincipalActive    = "active"
	PrincipalSuspended = "suspended"
	PrincipalExpired   = "expired"
	PrincipalRevoked   = "revoked"
)

// Principal is a local-authority identity row; external IdP assertions map
// onto it and never bypass the local directory.
type Principal struct {
	PrincipalID    string
	OrgID          string
	ExternalID     string
	IdpIssuer      string
	DisplayName    string
	State          string
	BindingVersion int
	ExpiresAt      string // RFC3339; empty = no expiry
	RevokedAt      string
	CreatedAt      string
	UpdatedAt      string
}

// RoleBinding is a time-limited role grant (ADR-012): expires_at is checked
// against the live clock on every authorization decision - no grace cache.
type RoleBinding struct {
	BindingID  string
	OrgID      string
	PrincipalID string
	ScopeKey   string // "org" or a space ULID
	Role       string
	ExpiresAt  string
	State      string // active | revoked
	CreatedAt  string
	UpdatedAt  string
}

// IdentityEvent is an append-only evidence row; the latest binding_version
// per principal doubles as the revocation watermark.
type IdentityEvent struct {
	EventID        string
	OrgID          string
	PrincipalID    string
	Kind           string // created|bound|rebound|suspended|restored|expired|revoked
	BindingVersion int
	CreatedAt      string
}

// MemberView is the org-admin member listing row: principal plus its live
// bindings (already org-scoped by the store predicate).
type MemberView struct {
	Principal Principal
	Bindings  []RoleBinding
}

// Store is the persistence contract. Every method that resolves an entity
// takes the verified org id as its leading scope argument and MUST bind it
// into the SQL predicate (org_id = ?) - the repository-layer enforcement
// required by ADR-011; implementations that skip the predicate fail TestIsolation.
type Store interface {
	CreateOrg(ctx context.Context, o Organization) error
	OrgByID(ctx context.Context, orgID string) (Organization, error)
	UpdateOrgState(ctx context.Context, orgID, state, updatedAt string) error
	ListOrgs(ctx context.Context) ([]Organization, error)

	CreateSpace(ctx context.Context, s TeamSpace) error
	SpaceByID(ctx context.Context, orgID, spaceID string) (TeamSpace, error)
	ListSpaces(ctx context.Context, orgID string) ([]TeamSpace, error)

	CreatePrincipal(ctx context.Context, p Principal, ev IdentityEvent) error
	PrincipalByID(ctx context.Context, orgID, principalID string) (Principal, error)
	UpdatePrincipalState(ctx context.Context, orgID, principalID, state string, bumpedVersion int, ev IdentityEvent) error
	ListPrincipals(ctx context.Context, orgID string) ([]Principal, error)

	CreateBinding(ctx context.Context, b RoleBinding) error
	BindingByID(ctx context.Context, orgID, bindingID string) (RoleBinding, error)
	ListBindings(ctx context.Context, orgID, principalID string) ([]RoleBinding, error)
	RevokeBinding(ctx context.Context, orgID, bindingID, updatedAt string) error
}

// Now returns the canonical RFC3339 UTC timestamp for t (house convention).
func Now(t time.Time) string { return t.UTC().Format(time.RFC3339) }
