package toolruntime

import (
	"errors"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"strings"

	"github.com/lunitide/lunitide/internal/canonpath"
)

// htmlArtifactPath is the renderer-safe preview name. Host sanitizer
// rejects file:// URLs, backslashes and non-.html suffixes, so desktop
// writes still preview as desktop/basename.html.
func htmlArtifactPath(requested string, desktop bool) string {
	base := filepath.Base(filepath.Clean(strings.TrimSpace(requested)))
	base = strings.ReplaceAll(base, `\`, "")
	lower := strings.ToLower(base)
	if base == "" || base == "." || strings.Contains(base, "..") {
		base = "preview.html"
	} else if !strings.HasSuffix(lower, ".html") && !strings.HasSuffix(lower, ".htm") {
		base = "preview.html"
	}
	if desktop {
		return "desktop/" + base
	}
	return base
}

// ResolveSessionArtifact maps a renderer-safe artifact path to a confined
// on-disk target under the session folder or user Desktop (desktop/ prefix).
func (r *Runtime) ResolveSessionArtifact(sessionID, relPath string) (string, error) {
	relPath = strings.TrimSpace(relPath)
	if relPath == "" {
		return r.SessionFolder(sessionID)
	}
	clean := filepath.Clean(filepath.FromSlash(relPath))
	clean = strings.ReplaceAll(clean, `\`, "/")
	if strings.HasPrefix(clean, "desktop/") {
		base := strings.TrimPrefix(clean, "desktop/")
		if base == "" || base == "." {
			return userDesktopDir()
		}
		dir, err := userDesktopDir()
		if err != nil {
			return "", err
		}
		return r.containedRead(dir, base)
	}
	dir, err := r.SessionFolder(sessionID)
	if err != nil {
		return "", err
	}
	return r.containedRead(dir, clean)
}

// ReadWorkspaceFile reads up to max bytes of one contained session
// workspace file (binary-safe). Host-side preview surfaces (bridge
// workspace.officePreview) use it; the model-facing read path stays
// workspace.read.
func (r *Runtime) ReadWorkspaceFile(session, relPath string, max int64) ([]byte, error) {
	if max <= 0 || max > maxGeneratedBytes {
		max = maxGeneratedBytes
	}
	// Host-side previews do not know the execution mode that produced the
	// artifact, so try the session sandbox first and fall back to the
	// user-selected full-access root (read-only, same containment checks).
	p, err := r.path(Approval, session, relPath, false, false)
	if err != nil {
		return nil, err
	}
	if _, statErr := os.Stat(p); statErr != nil && r.fullAccessRoot != nil {
		if root, rootErr := r.fullAccessRoot(); rootErr == nil && root != "" {
			if alt, altErr := r.containedRead(root, relPath); altErr == nil {
				p = alt
			}
		}
	}
	f, err := os.Open(p)
	if err != nil {
		return nil, err
	}
	defer f.Close()
	return io.ReadAll(io.LimitReader(f, max))
}

// WorkspaceRoot answers the runtime root (host-side export surfaces).
func (r *Runtime) WorkspaceRoot() string { return r.root }

// containedRead resolves relPath inside an arbitrary root with the same
// traversal and symlink-escape discipline as path(); read-only.
func (r *Runtime) containedRead(root, relPath string) (string, error) {
	if relPath == "" || filepath.IsAbs(relPath) || filepath.VolumeName(relPath) != "" {
		return "", errors.New("relative path required")
	}
	clean := filepath.Clean(relPath)
	if clean == ".." || strings.HasPrefix(clean, ".."+string(os.PathSeparator)) {
		return "", errors.New("path traversal")
	}
	// r.root is canonicalized once in New, but this root arrives from a
	// caller and has not been. Comparing a resolved child against an
	// unresolved root reports an escape for every file under a short-name
	// or redirected directory, so canonicalize both and compare like with
	// like.
	root, err := canonpath.Canonical(root)
	if err != nil {
		return "", err
	}
	p := filepath.Join(root, clean)
	real, err := canonpath.Canonical(p)
	if err != nil {
		return "", err
	}
	relCheck, err := filepath.Rel(root, real)
	if err != nil || relCheck == ".." || strings.HasPrefix(relCheck, ".."+string(os.PathSeparator)) {
		return "", errors.New("symlink escape")
	}
	return real, nil
}

// maxGeneratedBytes bounds both generated and parsed Office payloads.
const maxGeneratedBytes = 8 << 20

// finishOfficeGen writes generated office bytes and, for desktop=true,
// rewrites the artifact path to desktop/basename so the renderer can
// display a card (absolute C:\ paths are rejected as invalid stream events).
func (r *Runtime) finishOfficeGen(mode Mode, session, outPath string, data []byte, count int, unconfined, desktop bool, fallback string) (Result, error) {
	written, err := r.writeGenerated(mode, session, outPath, data, count, unconfined)
	if err != nil {
		return Result{}, err
	}
	if desktop && written.Artifact != nil {
		written.Artifact.Path = desktopPreviewPath(outPath, true, fallback)
	}
	return written, nil
}

// writeGenerated persists generated bytes into the session workspace with
// the same atomic temp+rename discipline as workspace.write.
func (r *Runtime) writeGenerated(mode Mode, session, relPath string, data []byte, count int, unconfined bool) (Result, error) {
	if len(data) > maxGeneratedBytes {
		return Result{}, errors.New("generated file exceeds limit")
	}
	p, e := r.path(mode, session, relPath, true, unconfined)
	if e != nil {
		return Result{}, e
	}
	tmp, e := os.CreateTemp(filepath.Dir(p), ".gen-*")
	if e != nil {
		return Result{}, e
	}
	tn := tmp.Name()
	defer os.Remove(tn)
	if e = tmp.Chmod(0600); e == nil {
		_, e = tmp.Write(data)
	}
	if e == nil {
		e = tmp.Sync()
	}
	ce := tmp.Close()
	if e == nil {
		e = ce
	}
	if e == nil {
		_ = os.Remove(p)
		e = os.Rename(tn, p)
	}
	if e != nil {
		return Result{}, e
	}
	out := result(fmt.Sprintf("generated %s (%d bytes)", relPath, len(data)))
	if count >= 0 {
		out.Output = fmt.Sprintf("generated %s (%d bytes, %d sections)", relPath, len(data), count)
	}
	// P2-2: surface the generated file as an artifact card. Office kinds
	// carry no inline content (binary payloads); preview goes through the
	// host-side workspace.artifact.preview method.
	switch strings.ToLower(filepath.Ext(relPath)) {
	case ".xlsx", ".docx", ".pptx", ".pdf":
		out.Artifact = &Artifact{Kind: strings.TrimPrefix(strings.ToLower(filepath.Ext(relPath)), "."), Path: filepath.ToSlash(relPath)}
	}
	return out, nil
}
