package toolruntime

import (
	"bytes"
	"image"
	"image/png"
	"os"
	"path/filepath"
	"testing"
)

func TestGeneratedImageDeliveryAndConfinement(t *testing.T) {
	r, err := New(t.TempDir())
	if err != nil {
		t.Fatal(err)
	}
	defer r.Close()
	var data bytes.Buffer
	if err = png.Encode(&data, image.NewRGBA(image.Rect(0, 0, 8, 8))); err != nil {
		t.Fatal(err)
	}
	out, err := r.SaveGeneratedImage(officeSession, "generated/picture.png", data.Bytes())
	if err != nil || out.Artifact == nil || out.Artifact.Kind != "image" || out.Artifact.Path != "generated/picture.png" {
		t.Fatalf("%+v %v", out, err)
	}
	root, err := r.SessionFolder(officeSession)
	if err != nil {
		t.Fatal(err)
	}
	read, err := os.ReadFile(filepath.Join(root, out.Artifact.Path))
	if err != nil || !bytes.Equal(read, data.Bytes()) {
		t.Fatal("generated bytes were lost")
	}
	for _, path := range []string{"../escape.png", "C:/escape.png", "picture.jpg"} {
		if _, err = r.SaveGeneratedImage(officeSession, path, data.Bytes()); err == nil {
			t.Fatalf("unsafe path accepted: %s", path)
		}
	}
	if _, err = r.SaveGeneratedImage(officeSession, "bad.png", []byte("not an image")); err == nil {
		t.Fatal("invalid image accepted")
	}
}
