CREATE TABLE tool_operations (
    id TEXT PRIMARY KEY CHECK (length(id)=26 AND substr(id, 1, 1) GLOB '[0-7]' AND id NOT GLOB '*[^0123456789ABCDEFGHJKMNPQRSTVWXYZ]*'),
    owner_scope TEXT NOT NULL CHECK (length(owner_scope) BETWEEN 1 AND 128),
    session_id TEXT NOT NULL DEFAULT '' CHECK (session_id='' OR (length(session_id)=26 AND substr(session_id, 1, 1) GLOB '[0-7]' AND session_id NOT GLOB '*[^0123456789ABCDEFGHJKMNPQRSTVWXYZ]*')),
    turn_id TEXT NOT NULL DEFAULT '' CHECK (turn_id='' OR (length(turn_id)=26 AND substr(turn_id, 1, 1) GLOB '[0-7]' AND turn_id NOT GLOB '*[^0123456789ABCDEFGHJKMNPQRSTVWXYZ]*')),
    automation_run_id TEXT NOT NULL DEFAULT '' CHECK (length(automation_run_id) <= 64),
    tool_name TEXT NOT NULL CHECK (length(tool_name) BETWEEN 1 AND 128),
    tool_version TEXT NOT NULL DEFAULT '' CHECK (length(tool_version) <= 32),
    target_ref TEXT NOT NULL DEFAULT '' CHECK (length(target_ref) <= 512),
    input_digest TEXT NOT NULL CHECK (length(input_digest)=64 AND input_digest NOT GLOB '*[^0-9a-f]*'),
    effect_class TEXT NOT NULL CHECK (effect_class IN ('read_only','local_reversible','remote_trackable','remote_unknown','desktop_interactive')),
    state TEXT NOT NULL CHECK (state IN ('pending','running','succeeded','partial','failed','unknown','cancelled')),
    expected_version INTEGER NOT NULL DEFAULT 1 CHECK (expected_version >= 1),
    external_id TEXT NOT NULL DEFAULT '' CHECK (length(external_id) <= 256),
    checkpoint_ref TEXT NOT NULL DEFAULT '' CHECK (length(checkpoint_ref) <= 256),
    evidence_ref TEXT NOT NULL DEFAULT '' CHECK (length(evidence_ref) <= 256),
    artifact_refs_json TEXT NOT NULL DEFAULT '[]' CHECK (json_valid(artifact_refs_json) AND length(artifact_refs_json) <= 4096),
    attempt INTEGER NOT NULL DEFAULT 1 CHECK (attempt >= 1),
    budget_used INTEGER NOT NULL DEFAULT 0 CHECK (budget_used >= 0),
    next_check_at TEXT NOT NULL DEFAULT '',
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    cancellation_requested_at TEXT NOT NULL DEFAULT '',
    error_kind TEXT NOT NULL DEFAULT '' CHECK (length(error_kind) <= 64),
    UNIQUE(owner_scope, id)
);
CREATE INDEX ix_tool_operations_session ON tool_operations(session_id, turn_id, created_at);
CREATE INDEX ix_tool_operations_external ON tool_operations(external_id) WHERE external_id <> '';
CREATE TABLE model_call_attempts (
    id TEXT PRIMARY KEY CHECK (length(id)=26 AND substr(id, 1, 1) GLOB '[0-7]' AND id NOT GLOB '*[^0123456789ABCDEFGHJKMNPQRSTVWXYZ]*'),
    owner_scope TEXT NOT NULL CHECK (length(owner_scope) BETWEEN 1 AND 128),
    task_id TEXT NOT NULL DEFAULT '' CHECK (length(task_id) <= 64),
    turn_id TEXT NOT NULL DEFAULT '' CHECK (length(turn_id) <= 64),
    call_id TEXT NOT NULL CHECK (length(call_id) BETWEEN 1 AND 64),
    parent_call_id TEXT NOT NULL DEFAULT '' CHECK (length(parent_call_id) <= 64),
    attempt_id TEXT NOT NULL CHECK (length(attempt_id) BETWEEN 1 AND 64),
    purpose TEXT NOT NULL CHECK (length(purpose) BETWEEN 1 AND 64),
    provider TEXT NOT NULL DEFAULT '' CHECK (length(provider) <= 64),
    deployment_ref TEXT NOT NULL DEFAULT '' CHECK (length(deployment_ref) <= 256),
    model TEXT NOT NULL DEFAULT '' CHECK (length(model) <= 256),
    protocol_revision TEXT NOT NULL DEFAULT '' CHECK (length(protocol_revision) <= 64),
    credential_generation TEXT NOT NULL DEFAULT '' CHECK (length(credential_generation) <= 64),
    policy_version TEXT NOT NULL DEFAULT '' CHECK (length(policy_version) <= 64),
    status TEXT NOT NULL CHECK (status IN ('intent','sent','succeeded','failed','cancelled','unknown')),
    started_at TEXT NOT NULL,
    ended_at TEXT NOT NULL DEFAULT '',
    input_tokens INTEGER NOT NULL DEFAULT 0 CHECK (input_tokens >= 0),
    output_tokens INTEGER NOT NULL DEFAULT 0 CHECK (output_tokens >= 0),
    cached_input_tokens INTEGER NOT NULL DEFAULT 0 CHECK (cached_input_tokens >= 0),
    cache_write_tokens INTEGER NOT NULL DEFAULT 0 CHECK (cache_write_tokens >= 0),
    usage_integrity TEXT NOT NULL CHECK (usage_integrity IN ('reported','partial','estimated','unknown')),
    provider_request_id TEXT NOT NULL DEFAULT '' CHECK (length(provider_request_id) <= 256),
    price_revision TEXT NOT NULL DEFAULT '' CHECK (length(price_revision) <= 64),
    currency TEXT NOT NULL DEFAULT '' CHECK (length(currency) <= 8),
    cost_status TEXT NOT NULL DEFAULT 'unknown' CHECK (cost_status IN ('known','partial','unknown')),
    UNIQUE(owner_scope, call_id, attempt_id)
);
CREATE INDEX ix_model_call_attempts_task ON model_call_attempts(owner_scope, task_id, turn_id, started_at);
