import{cleanup,fireEvent,render,screen,waitFor}from'@testing-library/react'
import{afterEach,expect,it,vi}from'vitest'
import type{AgentRuntimeBridge}from'../bridge/client'
import type{AgentRunDTO}from'../generated/bridge'
import{AgentRuntimePanel}from'./AgentRuntimePanel'
const U='01ARZ3NDEKTSV4RRFFQ69G5FAV',now='2026-01-01T00:00:00Z',usage={modelTurns:0,toolCalls:0,tokens:0,costMicros:0,wallClockSeconds:0,outputBytes:0,retries:0,noProgress:0},budget={maxModelTurns:8,maxToolCalls:32,maxTokens:100000,maxCostMicros:500000,maxWallClockSeconds:3600,maxOutputBytes:1048576,maxRetries:3,maxNoProgress:5,hardCeiling:true},run={id:U,sessionId:U,status:'running',budget,used:usage,createdAt:now,updatedAt:now,version:1}as AgentRunDTO
afterEach(()=>{cleanup();localStorage.clear()})
const api=()=>({capabilities:vi.fn().mockResolvedValue({manifest:{manifestVersion:'1',digest:'d',items:[{name:'changeset.apply',version:'1',kind:'changeset',risk:'high',enabled:true,requiresReview:true}]}}),start:vi.fn().mockResolvedValue(run),get:vi.fn().mockResolvedValue(run),cancel:vi.fn().mockResolvedValue({...run,status:'cancelled',version:2}),resume:vi.fn(),reconcile:vi.fn(),registerWorkspace:vi.fn().mockResolvedValue({id:U}),grantWorkspace:vi.fn().mockResolvedValue({id:U}),leaseWorkspace:vi.fn().mockResolvedValue({id:U,grantId:U,fencingToken:1,expiresAt:now,status:'active',createdAt:now,updatedAt:now}),decide:vi.fn(),previewChanges:vi.fn(),applyChanges:vi.fn(),revertChanges:vi.fn(),startCommand:vi.fn(),getCommand:vi.fn(),cancelCommand:vi.fn(),fetchWeb:vi.fn(),searchWeb:vi.fn(),putPlan:vi.fn(),evidence:vi.fn()})
it('starts and restores one durable agent run through the bridge',async()=>{const bridge=api();render(<AgentRuntimePanel sessionId={U} bridge={bridge as unknown as AgentRuntimeBridge}/>);fireEvent.click(await screen.findByRole('button',{name:'启动 Run'}));await waitFor(()=>expect(bridge.start).toHaveBeenCalledWith({sessionId:U,budget}));expect(await screen.findByText(/running · v1/)).toBeInTheDocument();expect(screen.getByText(/changeset.apply/)).toBeInTheDocument();expect(localStorage.getItem(`lunitide:m4-run:${U}`)).toBe(U);cleanup();render(<AgentRuntimePanel sessionId={U} bridge={bridge as unknown as AgentRuntimeBridge}/>);await waitFor(()=>expect(bridge.get).toHaveBeenCalledWith({runId:U}))})
it('authorizes workspace via register grant lease and can cancel',async()=>{localStorage.setItem(`lunitide:m4-run:${U}`,U);const bridge=api();render(<AgentRuntimePanel sessionId={U} bridge={bridge as unknown as AgentRuntimeBridge}/>);await screen.findByText(/running · v1/);fireEvent.click(screen.getByText('Workspace 授权'));fireEvent.change(screen.getByLabelText('工作区根目录'),{target:{value:'E:\\project'}});fireEvent.click(screen.getByText('授权并取得租约'));await waitFor(()=>expect(bridge.leaseWorkspace).toHaveBeenCalled());expect(bridge.registerWorkspace).toHaveBeenCalledWith({rootPath:'E:\\project'});fireEvent.click(screen.getByRole('button',{name:'取消'}));await waitFor(()=>expect(bridge.cancel).toHaveBeenCalledWith({runId:U,expectedVersion:1}))})
