import React,{useEffect,useState}from'react'
import{artifactReviewBridge,type ArtifactReviewBridge}from'../bridge/client'
import type{StreamArtifact}from'../bridge/client'
export type ArtifactCard=StreamArtifact&{callId:string;toolName:string}
const KIND_LABEL:Record<string,string>={html:'HTML',xlsx:'Excel',docx:'Word',pptx:'PPT',pdf:'PDF'}
const KIND_ICON:Record<string,string>={html:'◧',xlsx:'▤',docx:'▤',pptx:'◫',pdf:'▦'}
type Preview=|{kind:'xlsx';sheets:Array<{name:string;rows:number;cols:number;truncated:boolean;preview:string[][];header:string[]}>}|{kind:'html'|'docx'|'pptx';text:string}|{kind:'error';message:string}|{kind:'loading'}
const parseXlsx=(content:string)=>{try{const parsed=JSON.parse(content)as{sheets?:Array<{name?:string;rows?:number;cols?:number;truncated?:boolean;preview?:string[][];header?:string[]}>};if(!Array.isArray(parsed.sheets))return undefined;return parsed.sheets.map(sheet=>({name:sheet.name??'',rows:Number(sheet.rows??0),cols:Number(sheet.cols??0),truncated:!!sheet.truncated,preview:Array.isArray(sheet.preview)?sheet.preview:[],header:Array.isArray(sheet.header)?sheet.header:[]}))}catch{return undefined}}
export function ArtifactPanel({sessionId,artifacts,bridge=artifactReviewBridge,onRevise}:{sessionId:string;artifacts:ArtifactCard[];bridge?:ArtifactReviewBridge;onRevise?:(path:string,note:string)=>void}):React.JSX.Element{
  const[accepted,setAccepted]=useState<Set<string>>(()=>new Set()),[reviews,setReviews]=useState<Record<string,number>>(()=>({})),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[preview,setPreview]=useState<{path:string;data:Preview}|undefined>(),[draft,setDraft]=useState<Record<string,string>>(()=>({})),[exportTarget,setExportTarget]=useState<'desktop'|'downloads'|'documents'|'custom'>('desktop'),[customDir,setCustomDir]=useState('')
  useEffect(()=>{let active=true;bridge.list({sessionId}).then(result=>{if(!active)return;const acceptedPaths=new Set<string>(),counts:Record<string,number>={};for(const item of result.items){counts[item.path]=(counts[item.path]??0)+1}for(const path of result.acceptedPaths)acceptedPaths.add(path);setAccepted(acceptedPaths);setReviews(counts)}).catch(()=>{});return()=>{active=false}},[bridge,sessionId,artifacts.length])
  const reload=async()=>{try{const result=await bridge.list({sessionId});const acceptedPaths=new Set<string>(),counts:Record<string,number>={};for(const item of result.items){counts[item.path]=(counts[item.path]??0)+1}for(const path of result.acceptedPaths)acceptedPaths.add(path);setAccepted(acceptedPaths);setReviews(counts)}catch{}}
  const act=async(card:ArtifactCard,action:'comment'|'revise'|'accept')=>{const note=(draft[card.path]??'').trim();if(action!=='accept'&&!note){setNotice(action==='comment'?'请先填写评论内容':'请先填写修改要求');return}if(busy)return;setBusy(true);setNotice('');try{await bridge.append({sessionId,callId:card.callId,toolName:card.toolName,kind:card.kind,path:card.path,action,note});await reload();setDraft(values=>({...values,[card.path]:''}));if(action==='revise')onRevise?.(card.path,note);if(action==='accept')setNotice(`已验收 ${card.path}`);if(action==='comment')setNotice('评论已记录')}catch(e){setNotice(e instanceof Error?e.message:'操作失败')}finally{setBusy(false)}}
  const openPreview=async(card:ArtifactCard)=>{if(preview?.path===card.path){setPreview(undefined);return}setPreview({path:card.path,data:{kind:'loading'}});try{const result=await bridge.preview({sessionId,path:card.path});if(card.kind==='xlsx'){const sheets=parseXlsx(result.content);if(sheets)setPreview({path:card.path,data:{kind:'xlsx',sheets}});else setPreview({path:card.path,data:{kind:'error',message:'表格解析失败'}})}else setPreview({path:card.path,data:{kind:card.kind as 'html'|'docx'|'pptx',text:result.content}})}catch(e){setPreview({path:card.path,data:{kind:'error',message:e instanceof Error?e.message:'预览失败'}})}}
  const exportOne=async(card:ArtifactCard)=>{const target=exportTarget==='custom'?customDir.trim():exportTarget;if(exportTarget==='custom'&&!target){setNotice('请先填写自定义导出目录的绝对路径');return}if(busy)return;setBusy(true);setNotice('');try{const result=await bridge.exportArtifact({sessionId,path:card.path,target,overwrite:false});setNotice(`已导出到 ${result.exportedPath}`)}catch(e){setNotice(e instanceof Error?e.message:'导出失败')}finally{setBusy(false)}}
  if(!artifacts.length)return <section className="artifact-panel" aria-label="会话产物"><h3>产物</h3><p>本轮会话还没有生成的产物；AI 生成文件后会显示在这里。</p></section>
  return <section className="artifact-panel" aria-label="会话产物"><h3>产物（{artifacts.length}）</h3><div className="artifact-export-bar"><label>导出到<select aria-label="导出目录" value={exportTarget} onChange={e=>setExportTarget(e.target.value as typeof exportTarget)}><option value="desktop">桌面</option><option value="downloads">下载</option><option value="documents">文档</option><option value="custom">自定义目录…</option></select></label>{exportTarget==='custom'&&<input aria-label="自定义导出目录" placeholder="D:\\客户交付（绝对路径）" value={customDir} onChange={e=>setCustomDir(e.target.value)}/>}</div><ul className="artifact-list">{artifacts.map(card=>{const isAccepted=accepted.has(card.path),rounds=reviews[card.path]??0;return <li key={card.callId} className={`artifact-item ${isAccepted?'is-accepted':''}`}><div className="artifact-item-head"><span className="artifact-kind" aria-hidden="true">{KIND_ICON[card.kind]??'▣'}</span><b title={card.path}>{card.path}</b><span className="artifact-kind-label">{KIND_LABEL[card.kind]??card.kind}</span>{isAccepted&&<span className="artifact-accepted-badge" role="status">已验收</span>}{!isAccepted&&rounds>0&&<span className="artifact-review-count">{rounds} 条评审</span>}</div><div className="artifact-item-note"><input aria-label={`产物备注 ${card.path}`} placeholder={isAccepted?'已验收，可继续评论':'评论或填写修改要求…'} value={draft[card.path]??''} onChange={e=>setDraft(values=>({...values,[card.path]:e.target.value}))}/></div><div className="artifact-item-actions"><button type="button" onClick={()=>void openPreview(card)} aria-expanded={preview?.path===card.path}>{preview?.path===card.path?'收起预览':'预览'}</button><button type="button" disabled={busy} onClick={()=>void act(card,'comment')}>评论</button>{!isAccepted&&<button type="button" disabled={busy} onClick={()=>void act(card,'revise')}>修改</button>}<button type="button" className="artifact-accept" disabled={busy} onClick={()=>void act(card,'accept')}>{isAccepted?'再次验收':'验收'}</button><button type="button" className="artifact-export" disabled={busy} onClick={()=>void exportOne(card)}>导出</button></div>{preview?.path===card.path&&<div className="artifact-preview">{preview.data.kind==='loading'?<p role="status">正在载入预览…</p>:preview.data.kind==='error'?<p role="alert">{preview.data.message}</p>:preview.data.kind==='xlsx'?<div className="artifact-xlsx">{preview.data.sheets.map(sheet=><div key={sheet.name} className="artifact-xlsx-sheet"><b>{sheet.name||'工作表'} · {sheet.rows}×{sheet.cols}{sheet.truncated?'（已截断）':''}</b><div className="artifact-xlsx-table"><table><tbody>{sheet.preview.slice(0,40).map((row,ri)=><tr key={ri}>{row.map((cell,ci)=><td key={ci}>{cell}</td>)}</tr>)}</tbody></table></div></div>)}</div>:<pre className="artifact-text">{preview.data.text}</pre>}</div>}</li>})}</ul>{notice&&<p className="artifact-notice" role="status">{notice}</p>}</section>
}
