import {cleanup,fireEvent,render,screen,waitFor} from '@testing-library/react'
import {afterEach,expect,it,vi} from 'vitest'
import type{PlanBridge}from'../bridge/client'
import type{PlanDTO,PlanNodeDTO,PlanRunDTO}from'../generated/bridge'
import{CoordinationPlanPanel}from'./CoordinationPlanPanel'
const P='01ARZ3NDEKTSV4RRFFQ69G5FAA',N='01ARZ3NDEKTSV4RRFFQ69G5FAB',R='01ARZ3NDEKTSV4RRFFQ69G5FAC',C='01ARZ3NDEKTSV4RRFFQ69G5FAD',now='2026-01-01T00:00:00Z'
const plan={id:P,projectId:P,name:'计划',description:'',version:1,status:'draft',createdAt:now,updatedAt:now}as PlanDTO,node={id:N,planId:P,name:'节点',description:'',status:'pending',riskLevel:'low',workerRole:'',sequence:1,createdAt:now,updatedAt:now}as PlanNodeDTO
const root={id:R,planId:P,nodeId:N,role:'planner',todo:{id:R,title:'根项',description:''},status:'queued',depth:0,createdAt:now,updatedAt:now,version:1}as PlanRunDTO,child={...root,id:C,parentRunId:R,todo:{...root.todo,id:C,title:'子项'},depth:1}as PlanRunDTO
afterEach(cleanup)
const api=()=>({list:vi.fn().mockResolvedValue({items:[plan]}),listNodes:vi.fn().mockResolvedValue({items:[node]}),runTree:vi.fn().mockResolvedValue({items:[root,child]}),createTodo:vi.fn().mockResolvedValue({run:root,executionStarted:false}),spawnRun:vi.fn().mockResolvedValue({run:child,executionStarted:false}),startRun:vi.fn().mockResolvedValue({run:root,executionStarted:false}),joinRun:vi.fn().mockResolvedValue({run:root,executionStarted:false}),cancelRun:vi.fn().mockResolvedValue({run:root,executionStarted:false})})
it('shows the summary first, keeps management collapsed, and invokes coordination actions',async()=>{const b=api();render(<CoordinationPlanPanel projectId={P} bridge={b as unknown as PlanBridge}/>);expect(await screen.findByText('0/2 已完成')).toBeInTheDocument();expect(screen.getByRole('note')).not.toBeVisible();expect(screen.getByText('子项').closest('li')).toHaveStyle({paddingLeft:'16px'});fireEvent.click(screen.getByText('高级管理'));expect(screen.getByRole('note')).toHaveTextContent('不会执行模型、工具、网关、聊天或节点转换');fireEvent.change(screen.getByLabelText('Todo 标题'),{target:{value:'new'}});fireEvent.click(screen.getByText('创建根 Todo'));await waitFor(()=>expect(b.createTodo).toHaveBeenCalledWith({planId:P,nodeId:N,role:'planner',title:'new',description:''}));fireEvent.click(screen.getByText('根项'));fireEvent.click(screen.getByText('派生子项'));fireEvent.click(screen.getByText('开始协调'));fireEvent.click(screen.getByText('Join all'));fireEvent.click(screen.getByText('Join any'));fireEvent.click(screen.getByText('递归取消'));await waitFor(()=>{expect(b.spawnRun).toHaveBeenCalledWith({parentRunId:R,nodeId:N,role:'planner',title:'new',description:''});expect(b.startRun).toHaveBeenCalledWith({runId:R});expect(b.joinRun).toHaveBeenCalledWith({runId:R,mode:'all'});expect(b.joinRun).toHaveBeenCalledWith({runId:R,mode:'any'});expect(b.cancelRun).toHaveBeenCalledWith({runId:R})})})
