import React,{useEffect,useState}from'react'
import{planBridge,type PlanBridge}from'../bridge/client'
import type{PlanDTO,PlanNodeDTO,PlanRunDTO}from'../generated/bridge'
export function CoordinationPlanPanel({projectId,bridge=planBridge}:{projectId:string;bridge?:PlanBridge}){
 const[plans,setPlans]=useState<PlanDTO[]>([]),[nodes,setNodes]=useState<PlanNodeDTO[]>([]),[runs,setRuns]=useState<PlanRunDTO[]>([]),[planId,setPlanId]=useState(''),[nodeId,setNodeId]=useState(''),[selected,setSelected]=useState(''),[title,setTitle]=useState(''),[role,setRole]=useState('planner'),[error,setError]=useState('')
 useEffect(()=>{bridge.list({projectId}).then(r=>{setPlans(r.items);setPlanId(r.items[0]?.id??'')}).catch(e=>setError(String(e)))},[bridge,projectId])
 const refresh=async(id=planId)=>{if(!id)return;const[n,t]=await Promise.all([bridge.listNodes({planId:id}),bridge.runTree({planId:id})]);setNodes(n.items);setRuns(t.items);setNodeId(v=>n.items.some(x=>x.id===v)?v:(n.items[0]?.id??''))}
 useEffect(()=>{void refresh(planId)},[planId])
 const act=async(fn:()=>Promise<unknown>)=>{setError('');try{await fn();await refresh()}catch(e){setError(e instanceof Error?e.message:String(e))}}
 const create=()=>act(()=>selected?bridge.spawnRun({parentRunId:selected,nodeId,role,title,description:''}):bridge.createTodo({planId,nodeId,role,title,description:''}))
 const icon=(status:PlanRunDTO['status'])=>status==='succeeded'?'✓':status==='failed'||status==='cancelled'?'×':'○'
 return <section className="coordination-plan"><header><div><strong>任务摘要</strong><small>{runs.length?`${runs.filter(r=>r.status==='succeeded').length}/${runs.length} 已完成`:'暂无任务'}</small></div><select aria-label="协调计划" value={planId} onChange={e=>{setPlanId(e.target.value);setSelected('')}}>{plans.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></header>{error&&<p role="alert">{error}</p>}{runs.length?<ol className="plan-summary-list">{runs.map(r=><li key={r.id} className={`status-${r.status}`} style={{paddingLeft:`${r.depth*16}px`}}><button aria-pressed={selected===r.id} onClick={()=>setSelected(r.id)}><span aria-hidden="true">{icon(r.status)}</span><span><b>{r.todo.title}</b>{r.todo.description&&<em>{r.todo.description}</em>}<small>{r.role} · {r.status}</small></span></button></li>)}</ol>:<p className="plan-empty">当前计划还没有清单项。</p>}<details className="plan-admin"><summary>高级管理</summary><p role="note">此面板只记录协调状态，不会执行模型、工具、网关、聊天或节点转换。</p><div className="plan-admin-fields"><label>节点<select aria-label="协调节点" value={nodeId} onChange={e=>setNodeId(e.target.value)}>{nodes.map(n=><option key={n.id} value={n.id}>{n.name}</option>)}</select></label><label>角色<input aria-label="协调角色" maxLength={128} value={role} onChange={e=>setRole(e.target.value)}/></label><label>Todo<input aria-label="Todo 标题" maxLength={200} value={title} onChange={e=>setTitle(e.target.value)}/></label></div><div className="plan-admin-actions"><button disabled={!planId||!nodeId||!role.trim()||!title.trim()} onClick={()=>void create()}>{selected?'派生子项':'创建根 Todo'}</button><button disabled={!selected} onClick={()=>void act(()=>bridge.startRun({runId:selected}))}>开始协调</button><button disabled={!selected} onClick={()=>void act(()=>bridge.joinRun({runId:selected,mode:'all'}))}>Join all</button><button disabled={!selected} onClick={()=>void act(()=>bridge.joinRun({runId:selected,mode:'any'}))}>Join any</button><button disabled={!selected} onClick={()=>void act(()=>bridge.cancelRun({runId:selected}))}>递归取消</button></div></details></section>
}
