/** Preview documents without scripts, network access, nested frames or forms. */
export const isolatedHTML = (content: string) =>
  `<meta http-equiv="Content-Security-Policy" content="default-src 'none'; img-src data: blob:; style-src 'unsafe-inline'; font-src data:; media-src data: blob:; connect-src 'none'; frame-src 'none'; object-src 'none'; base-uri 'none'; form-action 'none'">${content}`

/** A generated page with no preview ticket still runs here. Scripts and buttons
 *  work. The network, nested frames, and this application's origin stay closed. */
const storageShim = `<script>(function(){var mem={};function remember(k,v){mem[String(k)]=String(v)}function recall(k){return Object.prototype.hasOwnProperty.call(mem,k)?mem[k]:null}function forget(k){delete mem[k]}function wipe(){mem={}}try{var proto=window.Storage&&Storage.prototype;if(proto&&!proto.__lunitidePatched){var set=proto.setItem,get=proto.getItem,rem=proto.removeItem,clr=proto.clear;proto.setItem=function(k,v){remember(k,v);try{return set.call(this,k,String(v))}catch(e){}};proto.getItem=function(k){try{var v=get.call(this,k);if(v!=null)return v}catch(e){}return recall(k)};proto.removeItem=function(k){forget(k);try{return rem.call(this,k)}catch(e){}};proto.clear=function(){wipe();try{return clr.call(this)}catch(e){}};proto.__lunitidePatched=1}}catch(e){}var api={getItem:function(k){return recall(k)},setItem:function(k,v){remember(k,v)},removeItem:forget,clear:wipe,key:function(i){return Object.keys(mem)[i]||null},get length(){return Object.keys(mem).length}};function broken(){try{var s=window.localStorage;s.setItem('__lunitide_probe__','1');s.removeItem('__lunitide_probe__');return false}catch(e){return true}}if(!broken())return;try{Object.defineProperty(window,'localStorage',{configurable:true,get:function(){return api}})}catch(e){}try{Object.defineProperty(window,'sessionStorage',{configurable:true,get:function(){return api}})}catch(e){}})()</script>`

export const runnableHTML = (content: string) =>
  `<meta http-equiv="Content-Security-Policy" content="default-src 'none'; script-src 'unsafe-inline' 'unsafe-eval'; style-src 'unsafe-inline'; img-src data: blob:; font-src data:; media-src data: blob:; connect-src 'none'; frame-src 'none'; object-src 'none'; base-uri 'none'; form-action 'none'">${storageShim}${content}`
