import React,{useEffect,useState}from'react'
import type{LocalWorkspaceBridge}from'../bridge/client'
type Node={name:string;path:string;directory:boolean}
export function LocalExplorer({bridge,onPreview,targetPath}:{bridge:LocalWorkspaceBridge;onPreview:(file:{path:string;content:string;size:number})=>void;targetPath?:string}):React.JSX.Element{
 const[root,setRoot]=useState<{name:string;path:string;bound:boolean}>({name:'',path:'',bound:false}),[children,setChildren]=useState<Record<string,Node[]>>({}),[open,setOpen]=useState<Set<string>>(new Set()),[error,setError]=useState('')
 const refresh=async()=>{const r=await bridge.root();setRoot(r);if(r.bound){const list=await bridge.list(),next:Record<string,Node[]>={'':list.items},expanded=new Set<string>();let path='';for(const part of (targetPath??'').replace(/\\/g,'/').split('/').filter(Boolean).slice(0,-1)){path=path?`${path}/${part}`:part;const node=(next[path.slice(0,Math.max(0,path.lastIndexOf('/')))]??next['']).find(x=>x.path===path);if(!node?.directory)break;expanded.add(path);next[path]=(await bridge.list(path)).items}setChildren(next);setOpen(expanded)}}
 useEffect(()=>{void refresh().catch(e=>setError(e instanceof Error?e.message:'工作区载入失败'))},[bridge])
 const choose=async()=>{try{await bridge.select();setChildren({});setOpen(new Set());await refresh()}catch(e){setError(e instanceof Error?e.message:'未选择工作区')}}
 const activate=async(node:Node)=>{try{setError('');if(node.directory){const next=new Set(open);if(next.has(node.path))next.delete(node.path);else{next.add(node.path);if(!children[node.path]){const r=await bridge.list(node.path);setChildren(v=>({...v,[node.path]:r.items}))}}setOpen(next)}else onPreview(await bridge.read(node.path))}catch(e){setError(e instanceof Error?e.message:'无法打开文件')}}
 const rows=(path='',depth=0):React.ReactNode=>(children[path]??[]).map(node=><React.Fragment key={node.path}><button type="button" role="treeitem" aria-expanded={node.directory?open.has(node.path):undefined} className="local-tree-row" style={{paddingLeft:12+depth*16}} onClick={()=>void activate(node)}><span aria-hidden="true">{node.directory?(open.has(node.path)?'▾':'▸'):'·'}</span>{node.name}</button>{node.directory&&open.has(node.path)&&rows(node.path,depth+1)}</React.Fragment>)
 return <section className="local-explorer" aria-label="本地工作区目录"><header><b>{root.bound?root.name:'未选择本地工作区'}</b><button type="button" onClick={()=>void choose()}>{root.bound?'更换文件夹':'选择文件夹'}</button></header>{root.bound&&<small title={root.path}>{root.path}</small>}<div role="tree">{root.bound?rows():<p>选择一个明确的本地文件夹后显示目录。</p>}</div>{error&&<p role="alert">{error}</p>}</section>
}
