import{cleanup,render,screen,waitFor}from'@testing-library/react'
import userEvent from'@testing-library/user-event'
import{afterEach,describe,expect,it,vi}from'vitest'
import type{AttachmentBridge}from'../bridge/client'
import type{BrowserBridge}from'../bridge/client'
import{Workspace,workspaceTabForTool,autoRevealWorkspaceTab,autoRevealWorkspaceForHtmlTool}from'./Workspace'
import{resetSessionWorkspaceBindings}from'./workspaceSession'
const P='01ARZ3NDEKTSV4RRFFQ69G5FAV',S='01ARZ3NDEKTSV4RRFFQ69G5FAA',OTHER='01ARZ3NDEKTSV4RRFFQ69G5FAB',A='01ARZ3NDEKTSV4RRFFQ69G5FAC',NOW='2025-01-01T00:00:00Z'
const item=(id=A,sessionId=S,name='notes.txt')=>({attachmentId:id,projectId:P,sessionId,originalName:name,mime:'text/plain',size:12,sha256:'hash',parseStatus:'succeeded' as const,parseErrorCode:'',parsedTextBytes:12,createdAt:NOW})
const bridge=(text='hello https://safe.example/path and javascript:alert(1) http://plain.test')=>({list:vi.fn().mockResolvedValue({items:[item(),item(OTHER,OTHER,'hidden.txt')]}),get:vi.fn().mockResolvedValue({...item(),parsedText:text}),ingest:vi.fn(),delete:vi.fn(),begin:vi.fn(),chunk:vi.fn(),commit:vi.fn(),abort:vi.fn()} as unknown as AttachmentBridge)
afterEach(()=>{cleanup();resetSessionWorkspaceBindings()})
describe('Workspace',()=>{
 it('routes web search to the browser, office files to files, subagents to subagents, and does not auto-reveal the terminal',()=>{expect(workspaceTabForTool('browser.open')).toBe('browser');expect(workspaceTabForTool('web.search')).toBe('browser');expect(workspaceTabForTool('web.fetch')).toBe('browser');expect(workspaceTabForTool('html.gen')).toBe('browser');expect(workspaceTabForTool('subagent.spawn')).toBe('subagents');expect(workspaceTabForTool('subagent.join')).toBe('subagents');expect(workspaceTabForTool('command.run')).toBe('terminal');expect(autoRevealWorkspaceTab('command.run')).toBeUndefined();expect(autoRevealWorkspaceTab('web.search')).toBeUndefined();expect(autoRevealWorkspaceTab('web.search',true)).toBe('browser');expect(autoRevealWorkspaceTab('web.fetch')).toBeUndefined();expect(autoRevealWorkspaceTab('browser.open')).toBe('browser');expect(autoRevealWorkspaceTab('subagent.spawn')).toBe('subagents');expect(autoRevealWorkspaceForHtmlTool('web.search')).toBeUndefined();expect(autoRevealWorkspaceForHtmlTool('web.search',true)).toBe('browser');expect(autoRevealWorkspaceTab('pptx.gen')).toBe('files');expect(workspaceTabForTool('workspace.write')).toBeUndefined();expect(workspaceTabForTool('answer.with.https-link')).toBeUndefined()})
 it('adds user-facing workspace tabs without exposing the unfinished Agent runtime console',()=>{render(<Workspace attachments={bridge()} projectId={P} sessionId={S} onClose={vi.fn()}/>);expect(screen.getAllByRole('tab').map(tab=>tab.textContent)).toEqual(expect.arrayContaining(['预览','文件','浏览器','子智能体','终端','计划','自动化']));expect(screen.queryByRole('tab',{name:'Agent'})).toBeNull();expect(screen.queryByRole('button',{name:'启动 Run'})).toBeNull()})
 it('mounts the automation panel on the automation tab instead of the plan panel',async()=>{const user=userEvent.setup();render(<Workspace attachments={bridge()} projectId={P} sessionId={S} onClose={vi.fn()}/>);await user.click(screen.getByRole('tab',{name:'自动化'}));expect(screen.getByRole('tab',{name:'自动化'})).toHaveAttribute('aria-selected','true');expect(screen.getByLabelText('自动化任务')).toBeInTheDocument();expect(screen.queryByText('工作计划清单')).toBeNull()})
 it('opens on the requested terminal tab, shows command activity and keeps start retryable when the bridge is unavailable',async()=>{render(<Workspace attachments={bridge()} projectId={P} sessionId={S} targetTab="terminal" toolActivities={[{callId:'call-1',name:'command.run',status:'tool_started',summary:'go test ./...'}]} onClose={vi.fn()}/>);expect(screen.getByRole('tab',{name:'终端'})).toHaveAttribute('aria-selected','true');expect(screen.getByText('自动审批')).toBeInTheDocument();expect(screen.getByLabelText('命令调用情况')).toHaveTextContent('command.run');expect(screen.getByLabelText('命令调用情况')).toHaveTextContent('go test ./...');expect(screen.getByRole('button',{name:'启动交互终端'})).toBeEnabled()})
 it('closes, filters to the current session, selects an attachment, and renders parsed text',async()=>{const onClose=vi.fn(),attachments=bridge(),user=userEvent.setup();render(<Workspace attachments={attachments} projectId={P} sessionId={S} onClose={onClose}/>);expect(await screen.findByText('notes.txt')).toBeInTheDocument();expect(screen.queryByText('hidden.txt')).toBeNull();await waitFor(()=>expect(attachments.get).toHaveBeenCalledWith({attachmentId:A}));expect(screen.getByText(/hello/)).toBeInTheDocument();await user.click(screen.getByRole('button',{name:'关闭工作区'}));expect(onClose).toHaveBeenCalledOnce()})
 it('has independent bounded minus and plus zoom controls',async()=>{const user=userEvent.setup();render(<Workspace attachments={bridge()} projectId={P} sessionId={S} onClose={vi.fn()}/>);await screen.findByText('notes.txt');const minus=screen.getByRole('button',{name:'缩小预览'}),plus=screen.getByRole('button',{name:'放大预览'});for(let i=0;i<10;i++)await user.click(minus);expect(screen.getByLabelText('预览缩放')).toHaveTextContent('50%');expect(minus).toBeDisabled();expect(plus).toBeEnabled();for(let i=0;i<10;i++)await user.click(plus);expect(screen.getByLabelText('预览缩放')).toHaveTextContent('200%');expect(plus).toBeDisabled();expect(minus).toBeEnabled()})
 it('linkifies only HTTPS text and leaves unsafe schemes inert',async()=>{render(<Workspace attachments={bridge()} projectId={P} sessionId={S} onClose={vi.fn()}/>);const link=await screen.findByRole('link',{name:'https://safe.example/path'});expect(link).toHaveAttribute('href','https://safe.example/path');expect(link).toHaveAttribute('rel',expect.stringContaining('noopener'));expect(screen.queryByRole('link',{name:/javascript|http:\/\/plain/})).toBeNull();expect(screen.getByText(/javascript:alert/)).toBeInTheDocument()})
 it('opens and closes only through the isolated browser bridge and reports opening',async()=>{const browser={open:vi.fn().mockResolvedValue({status:'opening',url:'https://example.com/'}),close:vi.fn().mockResolvedValue({status:'closed'})}as BrowserBridge,user=userEvent.setup();render(<Workspace attachments={bridge()} browser={browser} projectId={P} sessionId={S} onClose={vi.fn()}/>);await user.click(screen.getByRole('tab',{name:'浏览器'}));expect(screen.getByRole('tab',{name:'安全浏览器'})).toHaveAttribute('aria-selected','true');const input=screen.getByLabelText('浏览器地址');await user.clear(input);await user.type(input,'http://unsafe.example');expect(screen.getByRole('button',{name:'打开独立浏览器'})).toBeDisabled();await user.clear(input);await user.type(input,'https://example.com/');await user.click(screen.getByRole('button',{name:'打开独立浏览器'}));await waitFor(()=>expect(browser.open).toHaveBeenCalledWith({url:'https://example.com/'}));expect(screen.getByLabelText('浏览器状态')).toHaveTextContent('已接受，正在打开');expect(document.querySelector('iframe')).toBeNull();await user.click(screen.getByRole('button',{name:'关闭浏览器'}));await waitFor(()=>expect(browser.close).toHaveBeenCalledOnce())})
 it('opens skill creation on the files tab with the installed skill catalog and no saved disk folder',async()=>{const localWorkspace={root:vi.fn().mockResolvedValue({name:'知域宫殿',path:'D:\\知域宫殿',bound:true}),select:vi.fn(),clear:vi.fn().mockResolvedValue({cleared:true}),list:vi.fn().mockResolvedValue({items:[{name:'notes',path:'notes',directory:true}]}),read:vi.fn()};render(<Workspace attachments={bridge()} projectId={P} sessionId={S} localWorkspace={localWorkspace} targetTab="files" filesFocus="skills" isolateRoot onClose={vi.fn()}/>);expect(screen.getByRole('tab',{name:'文件'})).toHaveAttribute('aria-selected','true');expect(await screen.findByRole('region',{name:'技能包目录'})).toBeInTheDocument();expect(await screen.findByText('未选择本地工作区')).toBeInTheDocument();expect(screen.queryByText('知域宫殿')).not.toBeInTheDocument();await waitFor(()=>expect(localWorkspace.clear).toHaveBeenCalledOnce())})
 it('refreshes attachments when the upload revision changes',async()=>{const attachments=bridge(),view=render(<Workspace attachments={attachments} projectId={P} sessionId={S} refreshRevision={0} onClose={vi.fn()}/>);await waitFor(()=>expect(attachments.list).toHaveBeenCalledOnce());view.rerender(<Workspace attachments={attachments} projectId={P} sessionId={S} refreshRevision={1} onClose={vi.fn()}/>);await waitFor(()=>expect(attachments.list).toHaveBeenCalledTimes(2))})
 it('shows search progress in the browser tab before HTML results arrive',()=>{
  render(<Workspace attachments={bridge()} projectId={P} sessionId={S} targetTab="browser" toolActivities={[{callId:'search-1',name:'web.search',status:'tool_started',summary:'搜索：周杰伦'}]} onClose={vi.fn()}/>)
  expect(screen.getByText('正在检索网页…')).toBeInTheDocument()
 })
 it('renders web.search HTML results in the isolated browser preview',()=>{
  const url='https://cn.bing.com/search?q=%E5%91%A8%E6%9D%B0%E4%BC%A6'
  render(<Workspace attachments={bridge()} projectId={P} sessionId={S} targetTab="browser" toolActivities={[{callId:'search-1',name:'web.search',status:'tool_completed',summary:`query: 周杰伦\nresults_url: ${url}`,artifact:{kind:'html',path:'search.html',content:'<!doctype html><h1>搜索结果 · 周杰伦</h1><ol class="serp"><li class="serp-hit"><a href="https://news.example/jay">1. 周杰伦新闻</a><small>https://news.example/jay</small><p>动态</p></li></ol>'}}]} onClose={vi.fn()}/>)
  expect(screen.getByLabelText('浏览器地址')).toHaveValue(url)
  expect(screen.getByRole('button',{name:/周杰伦新闻/})).toBeInTheDocument()
  expect(screen.queryByTitle(/HTML 预览/)).toBeNull()
  expect(screen.queryByText('尚无 HTML 预览')).toBeNull()
 })
 it('shows a fetched-page extract instead of the empty placeholder',()=>{
  render(<Workspace attachments={bridge()} projectId={P} sessionId={S} targetTab="browser" toolActivities={[{callId:'fetch-1',name:'web.fetch',status:'tool_completed',summary:'url: https://tags.sina.com.cn/star_gutianle',artifact:{kind:'html',path:'fetch.html',content:'<h1>古天乐</h1><small>https://tags.sina.com.cn/star_gutianle</small><pre>最新动态</pre>'}}]} onClose={vi.fn()}/>)
  expect(screen.getByLabelText('浏览器地址')).toHaveValue('https://tags.sina.com.cn/star_gutianle')
  expect(screen.getByTitle('HTML 预览 fetch.html')).toBeInTheDocument()
  expect(screen.queryByText('尚无 HTML 预览')).toBeNull()
 })
 it('does not leave a blank pane when only the URL survived sanitization',()=>{
  render(<Workspace attachments={bridge()} projectId={P} sessionId={S} targetTab="browser" toolActivities={[{callId:'fetch-1',name:'web.fetch',status:'tool_completed',summary:'url: https://tags.sina.com.cn/star_gutianle'}]} onClose={vi.fn()}/>)
  expect(screen.getByLabelText('浏览器地址')).toHaveValue('https://tags.sina.com.cn/star_gutianle')
  expect(screen.getByText('该网页无法嵌进预览')).toBeInTheDocument()
  expect(screen.queryByText('尚无 HTML 预览')).toBeNull()
 })
 it('updates the address bar when a search result is opened',async()=>{
  const browser={open:vi.fn().mockResolvedValue({status:'opening',url:'https://news.example/jay'}),close:vi.fn().mockResolvedValue({status:'closed'})}as BrowserBridge
  const user=userEvent.setup()
  render(<Workspace attachments={bridge()} browser={browser} projectId={P} sessionId={S} targetTab="browser" toolActivities={[{callId:'search-1',name:'web.search',status:'tool_completed',summary:'query: jay\nresults_url: https://cn.bing.com/search?q=jay',artifact:{kind:'html',path:'search.html',content:'<h1>搜索结果 · jay</h1><ol class="serp"><li class="serp-hit"><a href="https://news.example/jay">1. 周杰伦新闻</a><small>https://news.example/jay</small><p>动态</p></li></ol>'}}]} onClose={vi.fn()}/>)
  await user.click(screen.getByRole('button',{name:/周杰伦新闻/}))
  await waitFor(()=>expect(browser.open).toHaveBeenCalledWith({url:'https://news.example/jay'}))
  expect(screen.getByLabelText('浏览器地址')).toHaveValue('https://news.example/jay')
 })
})
