package producthub

func detailedCards() []Card {
	voiceMethods := []Method{
		{Type: "voice", Entry: "唤醒月伴后直接说该动作", Continuous: "支持连续指令，不必重复唤醒"},
		{Type: "typing", Entry: "在对话框输入该动作"},
	}
	return []Card{
		detail("feature.dialog.music.open-player", "打开音乐播放软件", "Open music player", "dialog", "companion", "intent-control",
			"用语音或打字打开本机已安装的汽水音乐、网易云等播放器。",
			"月伴或对话框理解「打开网易云 / 打开汽水音乐」后，走电脑控制启动进程，用窗口句柄或 SMTC 会话确认真的起来了。没装、超时、权限拒绝会换注册表 App Paths 重试，再失败则播报原因并推荐已安装的替代播放器。连续语音不必重新唤醒。",
			Attributes{Operations: []string{"电脑操作"}, Tools: []string{"computer.control", "process.launch", "window.find"}, Capabilities: []string{"capability.stt.asr", "capability.llm.intent", "capability.tts.voice"}},
			voiceMethods,
			closedChain([]Step{
				{1, "用户输入", "语音/文字", "月伴说或打字；语音经 VAD 断句。"},
				{2, "语音识别", "ASR", "本地 sherpa；在线不可用切本地。"},
				{3, "意图理解", "LLM", "解析为打开播放器并抽出应用名；低置信反问。"},
				{4, "方案生成", "工具绑定", "FullAccess 免批，否则弹授权。"},
				{5, "执行控制", "启动进程", "开始菜单/快捷方式启进程，8s 内等窗口或 SMTC。"},
			}, 5, "窗口句柄或 SMTC 会话到了，TTS 已打开", "未安装 / 超时 / 权限拒绝", "注册表 App Paths 再搜", "播报原因并推荐已装播放器"),
			Scaffold{Pages: []string{"home", "media"}, Bridge: []string{"computer.control"}, Runtime: []string{"smtc", "winexec"}},
		),
		detail("feature.dialog.music.play", "放歌", "Play track", "dialog", "companion", "media-transport",
			"对当前播放器或媒体中心会话发出播放，并用 SMTC / 自有运行时核验。",
			"用户说「播放 / 放这首 / 继续放」或点媒体中心播放。引擎建 media operation action=play。外部播放器最多记 command_dispatched；只有匹配目标的 SMTC 或本产品音视频事件才能 verified_playing。命名搜歌走外部 origin，不进自有队列。",
			Attributes{Operations: []string{"媒体控制"}, Tools: []string{"media.play"}, Capabilities: []string{"capability.media.smtc", "capability.media.owned_runtime"}},
			append(voiceMethods, Method{Type: "menu", Entry: "媒体中心播放按钮"}),
			closedChain([]Step{
				{1, "选定会话", "媒体会话", "使用当前媒体中心会话或前台播放器。"},
				{2, "发操作", "play", "写入 play，带幂等键。"},
				{3, "派发", "runtime", "自有播放器或系统媒体键，禁止双通道连发。"},
				{4, "核验", "snapshot", "SMTC 或 owned runtime 回读 playing。"},
			}, 4, "verification=verified_playing，界面切播放中", "无会话、审批拒绝或核验失败", "按 recovery 重试一次", "仅 command_dispatched：标已发送未核验，不声称已播放"),
			Scaffold{Pages: []string{"media"}, Bridge: []string{"media.play"}, Runtime: []string{"smtc", "owned_runtime"}},
		),
		detail("feature.dialog.music.pause", "暂停播放", "Pause", "dialog", "companion", "media-transport",
			"暂停当前曲目，并核验 paused。",
			"语音「暂停」、打字或媒体中心暂停。action=pause。媒体键路径与 play_pause 共用 VK。核验不到 paused 时不得对用户说已经停住。",
			Attributes{Operations: []string{"媒体控制"}, Tools: []string{"media.pause"}, Capabilities: []string{"capability.media.smtc"}},
			voiceMethods,
			defaultChain("media-transport", "暂停播放"),
			Scaffold{Pages: []string{"media"}, Bridge: []string{"media.pause"}, Runtime: []string{"smtc"}},
		),
		detail("feature.dialog.music.next", "下一曲", "Next track", "dialog", "companion", "media-transport",
			"切到下一首，禁止一次派发两套路径连跳两首。",
			"外部播放器用 VK_MEDIA_NEXT_TRACK；自有队列用 queue next + auto_advance。SendMediaKey 注释约束禁止双通道。成功看新曲名或队列指针变化且核验通过。",
			Attributes{Operations: []string{"媒体控制"}, Tools: []string{"media.next"}, Capabilities: []string{"capability.media.smtc"}},
			voiceMethods,
			closedChain([]Step{
				{1, "选定会话", "媒体会话", "当前会话或前台播放器。"},
				{2, "发 next", "operation", "只走一条路径。"},
				{3, "派发", "runtime", "媒体键或自有队列，禁止双发。"},
				{4, "核验", "曲名/指针", "新曲名或队列指针变化。"},
			}, 4, "新曲核验通过", "队列空或播放器不响应", "只再发一次 next", "提示没有下一首或打开媒体中心"),
			Scaffold{Pages: []string{"media"}, Bridge: []string{"media.next"}},
		),
		detail("feature.dialog.music.search", "搜索并播放歌曲", "Search and play", "dialog", "companion", "intent-control",
			"按歌名搜索并播放（外部播放器或本机资产）。",
			"「放周杰伦的晴天」解析为 media.play + query。外部 origin 不把文件导入 owned queue、不抓版权资源。本机资产则走 media.asset.open + play。",
			Attributes{Operations: []string{"媒体控制", "检索"}, Tools: []string{"media.play", "media.asset.open"}},
			voiceMethods,
			closedChain([]Step{
				{1, "用户输入", "语音/文字", "说出歌名或歌手。"},
				{2, "意图", "LLM", "抽出 query 实体。"},
				{3, "解析目标", "外部或本机资产", "外部不入库；本机走 assetId。"},
				{4, "播放", "play", "派发并核验。"},
			}, 4, "核验到正在播放匹配曲目", "无匹配或无许可", "换关键词再搜", "列出近似名或打开媒体中心"),
			Scaffold{Pages: []string{"media"}, Bridge: []string{"media.play", "media.asset.open"}},
		),
		detail("feature.dialog.file.open", "打开文件", "Open a file", "dialog", "companion", "file-open",
			"用对话或文件对话框打开本机、工作区或同事传来的文件。",
			"三条入口合成同一核验：对话「打开桌面上的周报.docx」；工作区点文件；同事聊天点附件。Renderer 不得拿绝对路径当 payload；走 assetId / destPath 由引擎解析。Windows 上选文件走系统或托管对话框。",
			Attributes{Operations: []string{"文件"}, Tools: []string{"desktop.files.readChunk", "people.file.open", "agentHub.file.open"}},
			[]Method{
				{Type: "voice", Entry: "说「打开某某文件」"},
				{Type: "typing", Entry: "对话框输入打开文件"},
				{Type: "menu", Entry: "工作区单击或同事附件"},
			},
			closedChain([]Step{
				{1, "入口", "对话/工作区/同事", "从对话、工作区或附件点开。"},
				{2, "解析目标", "assetId", "用资产或用户点选解析，渲染进程不拼盘符路径。"},
				{3, "权限", "范围", "工作区或用户选择；越权拒绝。"},
				{4, "打开", "预览/关联应用", "产品内预览或系统关联应用。"},
				{5, "核验", "可见", "预览出现或外部窗口出现。"},
			}, 5, "文件已打开", "找不到、无权限或取消对话框", "再弹出选择框", "只揭示所在文件夹"),
			Scaffold{Pages: []string{"home", "people"}, Bridge: []string{"desktop.files.readChunk", "people.file.open", "agentHub.file.open"}},
		),
		detail("feature.dialog.app.launch", "打开电脑应用", "Launch app", "dialog", "companion", "intent-control",
			"打开计算器、浏览器、网易云等已装应用。",
			"与开播放器同族，目标不限播放器。开始菜单 / App Paths / 快捷方式。失败报未安装；重试走 App Paths；降级请用户从开始菜单开。",
			Attributes{Operations: []string{"电脑操作"}, Tools: []string{"computer.control"}},
			voiceMethods,
			defaultChain("intent-control", "打开电脑应用"),
			Scaffold{Pages: []string{"home"}, Bridge: []string{"computer.control"}, Settings: []string{"computer"}},
		),
		detail("feature.office.media.asset-open", "打开媒体资产", "Open media asset", "office", "media", "media-transport",
			"在媒体中心打开已授权的音视频资产。",
			"media.asset.open 要 assetId + mediaSessionId，回 playbackUrl（media.lunitide.local）和过期时间。禁止 payload 带本机 path。",
			Attributes{Operations: []string{"媒体控制"}, Tools: []string{"media.asset.open"}},
			[]Method{{Type: "menu", Entry: "媒体中心点开资产"}},
			closedChain([]Step{
				{1, "选资产", "assetId", "用户点已授权资产。"},
				{2, "校验会话", "mediaSessionId", "会话必须属于当前范围。"},
				{3, "发 open", "Bridge", "领取限时 playbackUrl。"},
				{4, "加载", "owned runtime", "自有播放器 loadedmetadata。"},
			}, 4, "资产可播", "资产 missing/revoked", "请用户重选", "提示重新选择，不拼盘符路径"),
			Scaffold{Pages: []string{"media"}, Bridge: []string{"media.asset.open"}},
		),
		detail("feature.office.people.open-file", "打开同事发来的文件", "Open received file", "office", "people", "file-open",
			"打开同事聊天里已接收的附件。",
			"入口固定同事聊天。成功：本地 staging 打开。失败：文件未下完。重试：再下再开。降级：只预览元数据。",
			Attributes{Operations: []string{"文件"}, Tools: []string{"people.file.open"}},
			[]Method{{Type: "menu", Entry: "同事聊天点附件"}},
			defaultChain("file-open", "打开同事发来的文件"),
			Scaffold{Pages: []string{"people"}, Bridge: []string{"people.file.open"}},
		),
		detail("feature.office.meetings.start", "开始会议听写", "Start meeting", "office", "meetings", "meeting-pipeline",
			"开始会议拾音并进入转写管线。",
			"会议页点开始或语音「开始会议记录」。音频进 meetings 管线，ASR 可本机 sherpa / 系统 / 火山（设置决定）。",
			Attributes{Operations: []string{"会议"}, Tools: []string{"meetings.start"}, Capabilities: []string{"capability.stt.asr"}},
			[]Method{{Type: "voice", Entry: "说开始会议记录"}, {Type: "menu", Entry: "会议页开始"}},
			closedChain([]Step{
				{1, "进入会议页", "meetings", "侧栏或语音打开。"},
				{2, "检查麦克风", "权限", "设备与权限可用。"},
				{3, "开始拾音", "start", "写入会议会话。"},
				{4, "实时字幕", "ASR", "本机或已配置引擎出字。"},
			}, 4, "字幕可见", "无麦或权限拒绝", "只录文件稍后转写", "给出无法拾音原因"),
			Scaffold{Pages: []string{"meetings"}, Bridge: []string{"meetings.start"}, Settings: []string{"meetings", "voice"}},
		),
		detail("feature.office.meetings.summary", "生成会议纪要", "Summarize meeting", "office", "meetings", "meeting-pipeline",
			"把转写做成纪要。",
			"转写完成后生成摘要；来源记在 meeting_summary_source。无转写则失败；可换路由重试；降级只给原文。",
			Attributes{Operations: []string{"会议"}, Tools: []string{"meetings.summary.source.get"}},
			[]Method{{Type: "menu", Entry: "会议页生成纪要"}},
			defaultChain("meeting-pipeline", "生成会议纪要"),
			Scaffold{Pages: []string{"meetings"}, Bridge: []string{"meetings.summary.source.get"}},
		),
		detail("feature.office.mro.search-manual", "检索机务手册", "Search MRO manual", "office", "mro", "asset-invoke",
			"在机务工作台按关键词查手册。",
			"已注册手册上检索，带 scope receipt。未注册手册则失败并提示去注册。",
			Attributes{Operations: []string{"检索"}, Tools: []string{"mro.manual.register"}},
			[]Method{{Type: "menu", Entry: "机务工作台搜索"}},
			defaultChain("asset-invoke", "检索机务手册"),
			Scaffold{Pages: []string{"mro"}, Bridge: []string{"mro.manual.register"}},
		),
		detail("feature.assets.memory.recall", "召回记忆", "Recall memory", "assets", "memory", "asset-invoke",
			"按对话上下文取出相关记忆。",
			"走 memory fabric / retrieval，不把用户密钥当记忆展示。库空则不注入，对话照走。",
			Attributes{Operations: []string{"检索"}, Tools: []string{"memory.search"}},
			[]Method{{Type: "menu", Entry: "对话自动召回或设置里检索"}},
			defaultChain("asset-invoke", "召回记忆"),
			Scaffold{Pages: []string{"settings"}, Bridge: []string{"memory.search"}, Settings: []string{"personal"}},
		),
		detail("feature.assets.ocr.screenshot", "OCR 识别截图", "OCR screenshot", "assets", "ocr", "asset-invoke",
			"把截图打成字。",
			"本机 OCR 兜底（Windows OCR / RapidOCR / 已验证的 PP-OCR 包）。未验证 runtime 不得当可用。",
			Attributes{Operations: []string{"OCR"}, Tools: []string{"ocr.routing.get"}},
			[]Method{{Type: "voice", Entry: "说识别这张截图"}, {Type: "menu", Entry: "智能能力设置"}},
			defaultChain("asset-invoke", "OCR 识别截图"),
			Scaffold{Pages: []string{"settings"}, Bridge: []string{"ocr.routing.get"}, Settings: []string{"personal"}},
		),
		detail("feature.execution.command.run", "执行白名单命令", "Run command", "execution", "command", "asset-invoke",
			"跑一条产品清单里签过名的命令，不走裸 shell 字符串。",
			"CommandSpec + argv 模板 + Job Object。未在清单或被撤销的拒绝。没有「随便拼一条 cmd」的降级。",
			Attributes{Operations: []string{"命令"}, Tools: []string{"command.start"}},
			[]Method{{Type: "menu", Entry: "安全与治理或对话批准后执行"}},
			closedChain([]Step{
				{1, "选 spec", "清单", "只接受已签名 CommandSpec。"},
				{2, "填参", "argv 模板", "参数进模板，不拼裸命令行。"},
				{3, "校验", "cwd/env", "工作目录与环境受控。"},
				{4, "启动作业", "Job Object", "执行并拿回执。"},
			}, 4, "回执成功", "签名失败、超时或不在清单", "按错误码重试同一 spec", "拒绝裸 shell，展示原因"),
			Scaffold{Pages: []string{"settings"}, Bridge: []string{"command.start"}, Settings: []string{"security"}},
		),
		detail("feature.execution.workspace.open-file", "在工作区打开文件", "Open workspace file", "execution", "workspace", "file-open",
			"在工作区编辑器打开文件。",
			"入口固定工作区。读 desktop.files.readChunk 一类方法，内容进编辑器。渲染进程不拼盘符。",
			Attributes{Operations: []string{"文件"}, Tools: []string{"desktop.files.readChunk"}},
			[]Method{{Type: "menu", Entry: "工作区文件树单击"}},
			defaultChain("file-open", "在工作区打开文件"),
			Scaffold{Pages: []string{"home"}, Bridge: []string{"desktop.files.readChunk"}},
		),
		detail("feature.execution.browser.navigate", "浏览器打开网址", "Browser navigate", "execution", "browser", "asset-invoke",
			"让产品浏览器打开一个 URL。",
			"br.navigate，依赖 Playwright 或已探测到的 Chrome。浏览器未就绪则提示去设置探测。",
			Attributes{Operations: []string{"浏览器"}, Tools: []string{"br.navigate"}},
			[]Method{{Type: "typing", Entry: "对话里给出网址"}, {Type: "menu", Entry: "浏览器设置"}},
			defaultChain("asset-invoke", "浏览器打开网址"),
			Scaffold{Pages: []string{"settings"}, Bridge: []string{"br.navigate"}, Settings: []string{"browser"}},
		),
		detail("feature.foundation.diagnostics.health", "查看系统健康", "System health", "foundation", "diagnostics", "diagnose-only",
			"查看引擎健康并作为本模块诊断输入。",
			"system.health 只读。本模块生成说明书与诊断报告时对照该回执，不在本里程碑自动改源码。",
			Attributes{Operations: []string{"诊断"}, Tools: []string{"system.health"}},
			[]Method{{Type: "menu", Entry: "设置 · 诊断与更新；或本模块生成按钮"}},
			defaultChain("diagnose-only", "查看系统健康"),
			Scaffold{Pages: []string{"settings"}, Bridge: []string{"system.health"}, Settings: []string{"diagnostics"}},
		),
	}
}

func detail(key, name, nameEN, domain, module, class, summary, desc string, attrs Attributes, methods []Method, chain Chain, scaffold Scaffold) Card {
	return Card{
		StableKey: key, Name: name, NameEN: nameEN, Domain: domain, Module: module,
		Summary: summary, Description: desc, Attributes: attrs, Methods: methods,
		Chain: chain, ChainClass: class, Scaffold: scaffold,
		Source: "seed", Provenance: "seed", Version: "seed.v1",
		Tags: []string{"status:核心"},
	}
}
