import { describe, expect, test } from 'vitest'
import { VOLC_ASR_RESOURCE_ID, VOLC_DEFAULT_VOICE_ID, VOLC_OFFICIAL_SPEAKERS, VOLC_SPEECH_ORIGIN, VOLC_TTS_RESOURCE_ID, canonicalizeVolcAsrModelId, canonicalizeVolcModelId, canonicalizeVolcSpeechUrl, canonicalizeVolcTtsResourceId, isVolcSpeakerId, isVolcTtsResourceId, nextUnusedVolcSpeaker } from './volcVoices'

describe('official seed-tts speakers', () => {
  test('ships the documented Agent Plan list, not 50 local lives', () => {
    expect(VOLC_OFFICIAL_SPEAKERS).toHaveLength(29)
    expect(new Set(VOLC_OFFICIAL_SPEAKERS.map(s => s.id)).size).toBe(29)
    expect(VOLC_OFFICIAL_SPEAKERS[0]?.id).toBe(VOLC_DEFAULT_VOICE_ID)
    expect(VOLC_OFFICIAL_SPEAKERS.every(s => s.id.endsWith('_uranus_bigtts'))).toBe(true)
    expect(VOLC_OFFICIAL_SPEAKERS.some(s => s.id.startsWith('refpack:'))).toBe(false)
    expect(VOLC_TTS_RESOURCE_ID).toBe('seed-tts-2.0')
    expect(isVolcSpeakerId(VOLC_TTS_RESOURCE_ID)).toBe(false)
    expect(isVolcTtsResourceId(VOLC_TTS_RESOURCE_ID)).toBe(true)
    expect(isVolcTtsResourceId('seed-tts-1.0')).toBe(true)
    expect(isVolcTtsResourceId('seedtts-2.0')).toBe(true)
    expect(isVolcTtsResourceId('doubao-seed-tts-2.0')).toBe(true)
    expect(isVolcTtsResourceId(VOLC_DEFAULT_VOICE_ID)).toBe(false)
    expect(canonicalizeVolcTtsResourceId('seedtts-2.0')).toBe(VOLC_TTS_RESOURCE_ID)
    expect(canonicalizeVolcTtsResourceId('doubao-seed-tts-2.0')).toBe(VOLC_TTS_RESOURCE_ID)
    expect(canonicalizeVolcAsrModelId('doubao-seed-asr-2.0')).toBe(VOLC_ASR_RESOURCE_ID)
    expect(canonicalizeVolcAsrModelId('seed-asr-2.0')).toBe(VOLC_ASR_RESOURCE_ID)
    expect(canonicalizeVolcAsrModelId('volc.seedasr.sauc.concurrent')).toBe('volc.seedasr.sauc.concurrent')
    expect(canonicalizeVolcModelId('tts', 'zh_female_xiaohe_uranus_bigtts')).toBe(VOLC_DEFAULT_VOICE_ID)
    expect(canonicalizeVolcSpeechUrl('wss://openspeech.bytedance.com/api/v3/plan/sauc/bigmodel_async')).toBe(VOLC_SPEECH_ORIGIN)
    expect(canonicalizeVolcSpeechUrl('https://openspeech.bytedance.com/api/v3/plan/tts/unidirectional')).toBe(VOLC_SPEECH_ORIGIN)
    expect(canonicalizeVolcSpeechUrl('wss://openspeech.bytedance.com/api/v3/plan/tts/bidirection')).toBe(VOLC_SPEECH_ORIGIN)
    expect(canonicalizeVolcSpeechUrl('https://ark.cn-beijing.volces.com/api/plan/v3')).toBe(VOLC_SPEECH_ORIGIN)
    expect(() => canonicalizeVolcSpeechUrl('https://evil.example/v1')).toThrow(/openspeech/)
    expect(isVolcSpeakerId(VOLC_DEFAULT_VOICE_ID)).toBe(true)
    expect(isVolcSpeakerId('saturn_invented')).toBe(false)
    expect(isVolcSpeakerId('温柔桃子')).toBe(false)
    expect(nextUnusedVolcSpeaker([VOLC_DEFAULT_VOICE_ID])?.name).toBe('Vivi')
  })
})
