import React,{useEffect,useRef,useState}from'react'
import{Terminal}from'@xterm/xterm'
import{FitAddon}from'@xterm/addon-fit'
import'@xterm/xterm/css/xterm.css'
import{getTerminalBridge,type TerminalBridge,type TerminalSession}from'../bridge/client'

type ToolActivity={callId:string;name:string;status:string;summary?:string}
export function TerminalPanel({projectId,sessionId,bridge,toolActivities=[],executionMode='auto-edit'}:{projectId:string;sessionId:string;bridge?:TerminalBridge;toolActivities?:ToolActivity[];executionMode?:'approval'|'auto-edit'|'plan'|'full-access'}){
 const host=useRef<HTMLDivElement>(null),active=useRef<TerminalSession|undefined>(undefined),term=useRef<Terminal|undefined>(undefined),[status,setStatus]=useState<'idle'|'starting'|'running'|'exited'|'error'>('idle'),[error,setError]=useState('')
 useEffect(()=>()=>{active.current?.dispose();term.current?.dispose();active.current=undefined;term.current=undefined},[projectId,sessionId])
 const start=async()=>{if(active.current||!host.current)return;setStatus('starting');setError('');const terminal=new Terminal({cursorBlink:true,convertEol:true,theme:{background:'#101318'}}),fit=new FitAddon();term.current=terminal;terminal.loadAddon(fit);terminal.open(host.current);fit.fit();const api=bridge??getTerminalBridge();try{const session=await api.start({projectId,sessionId,cols:terminal.cols,rows:terminal.rows},event=>{if(event.type==='output')terminal.write(event.data);else{terminal.writeln(`\r\n[进程已退出：${event.exitCode}]`);active.current=undefined;setStatus('exited')}});active.current=session;terminal.onData(data=>void session.input(data));const resize=()=>{fit.fit();void session.resize(terminal.cols,terminal.rows)};const observer=new ResizeObserver(resize);observer.observe(host.current);setStatus('running')}catch(e){terminal.dispose();term.current=undefined;setStatus('error');setError(e instanceof Error?e.message:'终端启动失败')}}
 const close=async()=>{const session=active.current;active.current=undefined;if(session)await session.close().catch(()=>{});term.current?.dispose();term.current=undefined;if(host.current)host.current.textContent='';setStatus('idle')}
 return <section className="terminal-panel" aria-label="终端面板"><div className="terminal-tabstrip" role="tablist" aria-label="终端会话"><div className="terminal-tab" role="tab" aria-selected="true"><span aria-hidden="true">›_</span><b>PowerShell</b></div><button type="button" aria-label="新建终端" disabled>＋</button><span className="terminal-sandbox-badge">{executionMode==='full-access'?'完全访问':executionMode==='approval'?'审批模式':executionMode==='plan'?'计划模式':'受控工作区'}</span></div><div className="terminal-toolbar"><div className="terminal-actions"><button type="button" disabled={status==='starting'||status==='running'} onClick={()=>void start()}>启动交互终端</button><button type="button" disabled={status!=='running'} onClick={()=>void close()}>关闭终端</button></div><span role="status" data-status={status}><i aria-hidden="true"/>{status==='running'?'运行中':status==='starting'?'启动中…':status==='exited'?'已退出':'未启动'}</span></div>{toolActivities.length>0&&<ol className="terminal-activities" aria-label="命令调用情况">{toolActivities.map(activity=><li key={activity.callId}><b>{activity.name}</b><span>{activity.status}</span>{activity.summary&&<code>{activity.summary}</code>}</li>)}</ol>}{error&&<p role="alert">{error}</p>}<div className="terminal-viewport"><div className="terminal-watermark" aria-hidden="true">LUNITIDE TERMINAL</div><div className="terminal-host" ref={host}/>{status==='idle'&&<div className="terminal-empty"><span aria-hidden="true">›_</span><b>终端尚未启动</b><p>点击「启动交互终端」在当前项目工作区中运行 PowerShell；对话中的命令调用与输出会实时记录在上方列表。</p></div>}</div></section>
}
