import { cleanup, render, screen, waitFor } from '@testing-library/react'
import userEvent from '@testing-library/user-event'
import { afterEach, expect, it, vi } from 'vitest'
import { BridgeClientError, type ProviderBridge } from '../bridge/client'
import type { ProviderDTO } from '../generated/bridge'
import { ProviderApp } from './ProviderApp'
afterEach(cleanup)
const provider:ProviderDTO={id:'01ARZ3NDEKTSV4RRFFQ69G5FAV',name:'Demo',protocol:'openai_compatible',baseUrl:'https://example.com',models:[{modelId:'m',displayName:'M',isDefault:true}],status:'enabled',credentialState:'configured',createdAt:new Date().toISOString(),updatedAt:new Date().toISOString(),version:1}
const credential={credentialSubmissionId:'01ARZ3NDEKTSV4RRFFQ69G5FAA',providerId:provider.id,expiresAt:new Date().toISOString(),expiresInSeconds:60}
function api(overrides:Partial<ProviderBridge>={}):ProviderBridge{return{list:vi.fn().mockResolvedValue({items:[]}),get:vi.fn(),create:vi.fn().mockResolvedValue(provider),update:vi.fn(),delete:vi.fn(),submitCredential:vi.fn().mockResolvedValue(credential),syncModels:vi.fn(),test:vi.fn(),...overrides}}
async function fillCreate(user:ReturnType<typeof userEvent.setup>,urlValue='https://example.com/v1'){await user.click(screen.getByRole('button',{name:/新建供应商/}));await user.type(screen.getByLabelText('供应商名称'),'Demo');const url=screen.getByLabelText('基础 URL');await user.clear(url);await user.type(url,urlValue);await user.type(screen.getByLabelText('模型 1 ID'),'m');await user.type(screen.getByLabelText('模型 1 显示名称'),'M')}
it('submits exact public request before bound create',async()=>{const bridge=api(),user=userEvent.setup();render(<ProviderApp bridge={bridge}/>);expect(await screen.findByText('还没有供应商')).toBeInTheDocument();await fillCreate(user);await user.type(screen.getByLabelText(/API 凭据/),'test-only');await user.click(screen.getByRole('button',{name:'安全保存'}));await waitFor(()=>expect(bridge.create).toHaveBeenCalledOnce());const submitted=vi.mocked(bridge.submitCredential).mock.calls[0][0],created=vi.mocked(bridge.create).mock.calls[0][0];expect(submitted.request).not.toHaveProperty('credentialSubmissionId');expect(created.credentialSubmissionId).toBe(credential.credentialSubmissionId)})
it.each(['http://example.com','https://例子.com','https://exa_mple.com'] as const)('prevents invalid HTTPS/ASCII host %s in the UI',async bad=>{const bridge=api(),user=userEvent.setup();render(<ProviderApp bridge={bridge}/>);await screen.findByText('还没有供应商');await fillCreate(user,bad);await user.click(screen.getByRole('button',{name:'安全保存'}));expect(await screen.findByRole('status')).toHaveTextContent(/HTTPS|ASCII|主机名/);expect(bridge.create).not.toHaveBeenCalled();expect(bridge.submitCredential).not.toHaveBeenCalled()})
it('retains exact retryable public mutation attempt and blocks busy re-entry',async()=>{let rejectFirst!:(e:unknown)=>void;const first=new Promise<ProviderDTO>((_,reject)=>{rejectFirst=reject});const create=vi.fn().mockReturnValueOnce(first).mockResolvedValue(provider),bridge=api({create}),user=userEvent.setup();render(<ProviderApp bridge={bridge}/>);await screen.findByText('还没有供应商');await fillCreate(user);await user.click(screen.getByRole('button',{name:'安全保存'}));await user.click(screen.getByRole('button',{name:'处理中…'}));expect(create).toHaveBeenCalledOnce();rejectFirst(new BridgeClientError('uncertain','TIMEOUT',true,'trace'));await waitFor(()=>expect(screen.getAllByText('uncertain')).not.toHaveLength(0));await user.click(screen.getByRole('button',{name:'安全保存'}));await waitFor(()=>expect(create).toHaveBeenCalledTimes(2));expect(create.mock.calls[1][0]).toEqual(create.mock.calls[0][0]);expect(create.mock.calls[1][1]?.attempt).toBe(create.mock.calls[0][1]?.attempt)})
it('does not auto-resend cleared credential plaintext after an uncertain credential outcome',async()=>{const submitCredential=vi.fn().mockRejectedValue(new BridgeClientError('uncertain credential','TIMEOUT',true,'trace')),bridge=api({submitCredential}),user=userEvent.setup();render(<ProviderApp bridge={bridge}/>);await screen.findByText('还没有供应商');await fillCreate(user);const secret=screen.getByLabelText(/API 凭据/);await user.type(secret,'one-use-secret');await user.click(screen.getByRole('button',{name:'安全保存'}));expect((await screen.findAllByText('uncertain credential')).length).toBeGreaterThan(0);expect(secret).toHaveValue('');await user.click(screen.getByRole('button',{name:'安全保存'}));expect(await screen.findByText(/不会自动继续保存/)).toBeInTheDocument();expect(submitCredential).toHaveBeenCalledOnce();expect(bridge.create).not.toHaveBeenCalled()})
it('shows refresh errors even while stale providers remain visible',async()=>{const list=vi.fn().mockResolvedValueOnce({items:[provider]}).mockRejectedValueOnce(new BridgeClientError('refresh failed','OFFLINE',true,'trace')),bridge=api({list}),user=userEvent.setup();render(<ProviderApp bridge={bridge}/>);expect(await screen.findByText('Demo')).toBeInTheDocument();await user.click(screen.getByRole('button',{name:'刷新供应商'}));expect(await screen.findByText('refresh failed')).toBeInTheDocument();expect(screen.getByText('Demo')).toBeInTheDocument()})
it('handles CAS update conflict by fetching latest and never auto-retrying',async()=>{const latest={...provider,name:'Server Demo',version:2},update=vi.fn().mockRejectedValue(new BridgeClientError('conflict','PROVIDER_VERSION_CONFLICT',false,'trace')),get=vi.fn().mockResolvedValueOnce(provider).mockResolvedValueOnce(latest),bridge=api({list:vi.fn().mockResolvedValue({items:[provider]}),get,update}),user=userEvent.setup();render(<ProviderApp bridge={bridge}/>);await user.click(await screen.findByRole('button',{name:/Demo/}));await screen.findByRole('heading',{name:'Demo'});await user.click(screen.getByRole('button',{name:'编辑'}));const name=screen.getByLabelText('供应商名称');await user.clear(name);await user.type(name,'My edit');await user.click(screen.getByRole('button',{name:'安全保存'}));expect(await screen.findByText('保存发生并发冲突')).toBeInTheDocument();expect(screen.getByText(/服务器现在是 v2/)).toBeInTheDocument();expect(update).toHaveBeenCalledOnce();expect(vi.mocked(update).mock.calls[0][0].expectedVersion).toBe(1);await user.click(screen.getByRole('button',{name:'载入服务器版本'}));expect(screen.getByLabelText('供应商名称')).toHaveValue('Server Demo');expect(update).toHaveBeenCalledOnce()})
