import React, { useEffect, useRef, useState } from 'react'
import { BridgeClientError, createMutationAttempt, type MutationAttempt, type MutationMethod, type ProviderBridge } from '../bridge/client'
import type { ModelDTO, ProviderCreatePayload, ProviderDTO, ProviderProtocol, ProviderStatus, ProviderTestResult, ProviderUpdatePayload } from '../generated/bridge'
import { normalizeOrigin, originFingerprint } from './fingerprint'
type Draft={name:string;protocol:ProviderProtocol;baseUrl:string;status:ProviderStatus;models:ModelDTO[]}
type Conflict={operation:'update'|'delete'|'sync';latest:ProviderDTO}
type PendingMutation={method:MutationMethod;publicPayload:string;attempt:MutationAttempt<any>}
const blank=():Draft=>({name:'',protocol:'openai_compatible',baseUrl:'https://',status:'enabled',models:[{modelId:'',displayName:'',isDefault:true}]})
const draftOf=(p:ProviderDTO):Draft=>({name:p.name,protocol:p.protocol,baseUrl:p.baseUrl,status:p.status,models:p.models.map(m=>({...m}))})
const states={configured:'凭据已配置',missing:'缺少凭据',unavailable:'凭据不可用',requires_reentry:'需要重新输入凭据'}
const issue=(e:unknown)=>e instanceof BridgeClientError?e:new BridgeClientError(e instanceof Error?e.message:'请求失败','CLIENT_ERROR',false,'renderer')
export function ProviderApp({bridge}:{bridge:ProviderBridge}):React.JSX.Element{
 const [items,setItems]=useState<ProviderDTO[]>([]),[selected,setSelected]=useState<ProviderDTO>(),[draft,setDraft]=useState(blank),[mode,setMode]=useState<'view'|'create'|'edit'>('view'),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState<BridgeClientError>(),[notice,setNotice]=useState(''),[diagnostic,setDiagnostic]=useState<ProviderTestResult>(),[warnings,setWarnings]=useState<string[]>([]),[conflict,setConflict]=useState<Conflict>();const secret=useRef<HTMLInputElement>(null),heading=useRef<HTMLHeadingElement>(null),generation=useRef(0),loadGeneration=useRef(0),mounted=useRef(true),busyRef=useRef(false),pending=useRef<PendingMutation|undefined>(undefined),credentialBlocked=useRef('')
 const clear=()=>{setError(undefined);setNotice('');setWarnings([]);setConflict(undefined)}
 const load=async()=>{const token=++loadGeneration.current;setLoading(true);try{const result=await bridge.list();if(mounted.current&&token===loadGeneration.current){setItems(result.items);setError(undefined)}}catch(e){if(mounted.current&&token===loadGeneration.current)setError(issue(e))}finally{if(mounted.current&&token===loadGeneration.current)setLoading(false)}}
 useEffect(()=>{mounted.current=true;return()=>{mounted.current=false;generation.current++;loadGeneration.current++}},[]);useEffect(()=>{void load()},[]);useEffect(()=>heading.current?.focus(),[mode,selected?.id])
 const enter=()=>{if(busyRef.current)return;busyRef.current=true;setBusy(true);return++generation.current}
 const leave=(token:number)=>{if(mounted.current&&token===generation.current){busyRef.current=false;setBusy(false)}}
 const choose=async(id:string)=>{const token=enter();if(!token)return;clear();setDiagnostic(undefined);try{const p=await bridge.get({id});if(mounted.current&&token===generation.current){pending.current=undefined;setSelected(p);setDraft(draftOf(p));setMode('view')}}catch(e){if(mounted.current&&token===generation.current)setError(issue(e))}finally{leave(token)}}
 const normalized=():Draft=>({...draft,name:draft.name.trim(),baseUrl:draft.baseUrl.trim(),models:draft.models.map(m=>({...m,displayName:m.displayName.trim()}))})
 const invalid=(d:Draft)=>{if(!d.name)return'请输入供应商名称';try{normalizeOrigin(d.baseUrl)}catch(e){return e instanceof Error?e.message:'地址无效'}if(d.models.length<1||d.models.length>50)return'模型数量必须为 1–50';if(d.models.filter(m=>m.isDefault).length!==1)return'必须且只能设置一个默认模型';if(d.models.some(m=>!(/^[\x21-\x7E]{1,200}$/.test(m.modelId))))return'模型 ID 必须为 1–200 字节可打印 ASCII，且不能含空格';if(new Set(d.models.map(m=>m.modelId)).size!==d.models.length)return'模型 ID 不能重复';if(d.models.some(m=>!m.displayName||new TextEncoder().encode(m.displayName).length>200))return'显示名称不能为空且最多 200 字节'}
 const refreshConflict=async(operation:Conflict['operation'],id:string,token:number)=>{try{const latest=await bridge.get({id});if(mounted.current&&token===generation.current)setConflict({operation,latest})}catch(e){if(mounted.current&&token===generation.current)setError(issue(e))}}
 const retain=<T extends object>(method:MutationMethod,publicPayload:object,payload:T):MutationAttempt<T>=>{const signature=JSON.stringify(publicPayload),old=pending.current;if(old?.method===method&&old.publicPayload===signature)return old.attempt as MutationAttempt<T>;const attempt=createMutationAttempt(method,payload);pending.current={method,publicPayload:signature,attempt};return attempt}
 const submit=async(e:React.FormEvent)=>{e.preventDefault();const clean=normalized(),problem=invalid(clean);if(problem){setNotice(problem);return}const base=mode==='create'?{name:clean.name,protocol:clean.protocol,baseUrl:clean.baseUrl,models:clean.models,status:clean.status} satisfies ProviderCreatePayload:{id:selected!.id,name:clean.name,protocol:clean.protocol,baseUrl:clean.baseUrl,models:clean.models,status:clean.status,expectedVersion:selected!.version} satisfies ProviderUpdatePayload;const method=mode==='create'?'provider.create':'provider.update',credential=secret.current?.value??'',signature=JSON.stringify(base);if(!credential&&credentialBlocked.current===signature){setNotice('凭据提交结果不确定且输入已清除。请刷新权威状态或重新输入凭据；不会自动继续保存。');return}const token=enter();if(!token)return;setDraft(clean);clear();let credentialUsed=false,credentialCompleted=false;try{let attempt:MutationAttempt<any>|undefined;const cached=pending.current;if(!credential&&cached?.method===method&&cached.publicPayload===signature)attempt=cached.attempt;else{pending.current=undefined;let credentialSubmissionId:string|undefined;if(credential){credentialUsed=true;credentialBlocked.current=signature;const cp=mode==='create'?{scope:{draftFingerprint:(await originFingerprint(clean.protocol,clean.baseUrl)).fingerprint},protocol:clean.protocol,origin:normalizeOrigin(clean.baseUrl),request:base,credential}:{scope:{providerId:selected!.id},request:base,credential};if(secret.current)secret.current.value='';credentialSubmissionId=(await bridge.submitCredential(cp)).credentialSubmissionId;credentialCompleted=true;credentialBlocked.current=''}if(secret.current)secret.current.value='';const payload={...base,...(credentialSubmissionId?{credentialSubmissionId}:{})};attempt=retain(method,base,payload)}const saved=method==='provider.create'?await bridge.create(attempt.payload as ProviderCreatePayload,{attempt}):await bridge.update(attempt.payload as ProviderUpdatePayload,{attempt});if(mounted.current&&token===generation.current){pending.current=undefined;credentialBlocked.current='';setSelected(saved);setDraft(draftOf(saved));setMode('view');setNotice('已安全保存');void load()}}catch(e){if(secret.current)secret.current.value='';const x=issue(e);if(mounted.current&&token===generation.current){setError(x);if(!x.retryable)pending.current=undefined;if(credentialUsed&&!credentialCompleted)setNotice('凭据提交结果不确定。已清除输入；不会自动重发，请刷新权威状态或重新输入。');if(x.code==='PROVIDER_VERSION_CONFLICT'&&selected){pending.current=undefined;await refreshConflict('update',selected.id,token)}}}finally{leave(token)}}
 const remove=async()=>{if(!selected||busyRef.current||!confirm(`删除“${selected.name}”？此操作不可撤销。`))return;const token=enter();if(!token)return;clear();const p={id:selected.id,expectedVersion:selected.version},attempt=retain('provider.delete',p,p);try{await bridge.delete(attempt.payload,{attempt});if(mounted.current&&token===generation.current){pending.current=undefined;setSelected(undefined);setNotice('供应商已删除');void load()}}catch(e){const x=issue(e);if(mounted.current&&token===generation.current){setError(x);if(!x.retryable)pending.current=undefined;if(x.code==='PROVIDER_VERSION_CONFLICT')await refreshConflict('delete',selected.id,token)}}finally{leave(token)}}
 const sync=async()=>{if(!selected)return;const token=enter();if(!token)return;clear();const p={providerId:selected.id,expectedVersion:selected.version},attempt=retain('provider.model.sync',p,p);try{const r=await bridge.syncModels(attempt.payload,{attempt}),old=draft.models.find(m=>m.isDefault)?.modelId,has=r.models.some(m=>m.isDefault);if(mounted.current&&token===generation.current){pending.current=undefined;const models=r.models.map((m,i)=>({...m,displayName:m.displayName.trim(),isDefault:has?m.isDefault:m.modelId===old||(!r.models.some(x=>x.modelId===old)&&i===0)}));setDraft(d=>({...d,models}));setSelected({...selected,models,version:r.version});setWarnings(r.warnings);setNotice('模型已同步，请检查默认模型后保存')}}catch(e){const x=issue(e);if(mounted.current&&token===generation.current){setError(x);if(!x.retryable)pending.current=undefined;if(x.code==='PROVIDER_VERSION_CONFLICT')await refreshConflict('sync',selected.id,token)}}finally{leave(token)}}
 const test=async()=>{if(!selected)return;const token=enter();if(!token)return;setDiagnostic(undefined);setError(undefined);try{const result=await bridge.test({providerId:selected.id,modelId:selected.models.find(m=>m.isDefault)?.modelId});if(mounted.current&&token===generation.current)setDiagnostic(result)}catch(e){if(mounted.current&&token===generation.current)setError(issue(e))}finally{leave(token)}}
 const updateModel=(i:number,p:Partial<ModelDTO>)=>setDraft(d=>({...d,models:d.models.map((m,n)=>n===i?{...m,...p}:p.isDefault?{...m,isDefault:false}:m)}))
 const beginCreate=()=>{if(busyRef.current)return;generation.current++;pending.current=undefined;credentialBlocked.current='';clear();setDiagnostic(undefined);setDraft(blank());setSelected(undefined);setMode('create')}
 return <div className="shell"><header className="brand"><div><p className="eyebrow">LOCAL-FIRST AI WORKSPACE</p><h1>Lunitide <span>月汐</span></h1><p>安全连接你的模型世界，凭据始终由 Windows Host 托管。</p></div><button className="primary" disabled={busy} onClick={beginCreate}>＋ 新建供应商</button></header><div className="layout"><aside aria-label="供应商列表"><div className="aside-title"><h2>供应商</h2><button aria-label="刷新供应商" disabled={busy||loading} onClick={()=>void load()}>↻</button></div>{loading?<p role="status">正在载入…</p>:error&&!items.length?<ErrorBox error={error} retry={load}/>:!items.length?<div className="empty"><b>还没有供应商</b><span>创建第一个连接开始使用。</span></div>:<><div className="cards">{items.map(p=><button className={`provider-card ${selected?.id===p.id?'active':''}`} aria-pressed={selected?.id===p.id} disabled={busy} key={p.id} onClick={()=>void choose(p.id)}><span className="protocol-mark">{p.protocol==='anthropic'?'A':'O'}</span><span><b>{p.name}</b><small>{p.models.length} 个模型 · v{p.version}</small></span><i className={`state ${p.credentialState}`}>{states[p.credentialState]}</i></button>)}</div>{error&&<ErrorBox error={error} retry={load}/>}</>}</aside><main>{mode==='view'&&!selected?<section className="welcome"><div className="orb">◐</div><h2 tabIndex={-1} ref={heading}>选择一个供应商</h2><p>查看配置、同步模型并执行安全连接诊断。</p></section>:mode==='view'&&selected?<section><div className="detail-head"><div><p className="eyebrow">{selected.protocol}</p><h2 tabIndex={-1} ref={heading}>{selected.name}</h2><span className={`pill ${selected.credentialState}`}>{states[selected.credentialState]}</span></div><div className="actions"><button disabled={busy} onClick={()=>{pending.current=undefined;clear();setDraft(draftOf(selected));setMode('edit')}}>编辑</button><button disabled={busy} onClick={()=>void test()}>测试连接</button><button className="danger" disabled={busy} onClick={()=>void remove()}>删除</button></div></div><dl><div><dt>基础地址</dt><dd>{selected.baseUrl}</dd></div><div><dt>状态</dt><dd>{selected.status==='enabled'?'已启用':'已停用'}</dd></div><div><dt>更新时间</dt><dd>{new Date(selected.updatedAt).toLocaleString()}</dd></div></dl><h3>模型</h3><div className="model-list">{selected.models.map(m=><div key={m.modelId}><span><b>{m.displayName}</b><small>{m.modelId}</small></span>{m.isDefault&&<i>默认</i>}</div>)}</div>{diagnostic&&<div className={`diagnostic ${diagnostic.status}`} role="status"><b>{diagnostic.status==='passed'?'连接测试通过':'连接测试失败'}</b><span>阶段 {diagnostic.stage} · {diagnostic.latencyMs} ms{diagnostic.errorCode&&` · ${diagnostic.errorCode}`}</span>{diagnostic.sanitizedMessage&&<p className="diagnostic-msg">{diagnostic.sanitizedMessage}</p>}</div>}{error&&<ErrorBox error={error}/>} {conflict&&ConflictBox()}</section>:Editor()}</main></div></div>
 function ConflictBox(){if(!conflict)return null;const verbs={update:'保存',delete:'删除',sync:'同步'};return <div className="conflict" role="alert"><b>{verbs[conflict.operation]}发生并发冲突</b><p>服务器现在是 v{conflict.latest.version}。不会自动重试，请刷新审阅后重新确认操作。</p><button type="button" onClick={()=>{setSelected(conflict.latest);setDraft(draftOf(conflict.latest));setConflict(undefined);setError(undefined);setMode(conflict.operation==='delete'?'view':'edit')}}>载入服务器版本</button></div>}
 function Editor(){return <section><div className="detail-head"><div><p className="eyebrow">{mode==='create'?'NEW CONNECTION':'EDIT CONNECTION'}</p><h2 tabIndex={-1} ref={heading}>{mode==='create'?'新建供应商':`编辑 ${selected?.name}`}</h2></div><button disabled={busy} onClick={()=>{clear();setMode('view')}}>取消</button></div><form onSubmit={e=>void submit(e)}><fieldset disabled={busy} className="editor-fields"><div className="form-grid"><label>供应商名称<input value={draft.name} maxLength={500} onChange={e=>setDraft(d=>({...d,name:e.target.value}))}/></label><label>协议<select value={draft.protocol} onChange={e=>setDraft(d=>({...d,protocol:e.target.value as ProviderProtocol}))}><option value="openai_compatible">OpenAI Compatible</option><option value="anthropic">Anthropic</option></select></label><label className="wide">基础 URL<input type="url" value={draft.baseUrl} onChange={e=>setDraft(d=>({...d,baseUrl:e.target.value}))}/></label><label>状态<select value={draft.status} onChange={e=>setDraft(d=>({...d,status:e.target.value as ProviderStatus}))}><option value="enabled">启用</option><option value="disabled">停用</option></select></label><label>API 凭据（仅覆盖）<input ref={secret} type="password" autoComplete="new-password" aria-describedby="secret-help"/><small id="secret-help">留空即不更改；结果不确定时会清空且绝不自动重发。</small></label></div><div className="model-title"><div><h3>模型</h3><p>1–50 个；选择且仅选择一个默认模型。</p></div><div>{mode==='edit'&&<button type="button" onClick={()=>void sync()}>从供应商同步</button>} <button type="button" disabled={draft.models.length>=50} onClick={()=>setDraft(d=>({...d,models:[...d.models,{modelId:'',displayName:'',isDefault:false}]}))}>＋ 添加模型</button></div></div><div className="model-editor">{draft.models.map((m,i)=><fieldset key={i}><legend>模型 {i+1}</legend><label>模型 ID<input aria-label={`模型 ${i+1} ID`} value={m.modelId} maxLength={200} onChange={e=>updateModel(i,{modelId:e.target.value})}/></label><label>显示名称<input aria-label={`模型 ${i+1} 显示名称`} value={m.displayName} maxLength={200} onBlur={e=>updateModel(i,{displayName:e.target.value.trim()})} onChange={e=>updateModel(i,{displayName:e.target.value})}/></label><label className="default"><input type="radio" name="defaultModel" checked={m.isDefault} onChange={()=>updateModel(i,{isDefault:true})}/> 默认</label><button type="button" aria-label={`删除模型 ${i+1}`} disabled={draft.models.length===1} onClick={()=>setDraft(d=>{const models=d.models.filter((_,n)=>n!==i);if(m.isDefault)models[0]={...models[0],isDefault:true};return{...d,models}})}>×</button></fieldset>)}</div></fieldset>{warnings.length>0&&<div className="warning" role="status">{warnings.map(w=><p key={w}>{w}</p>)}</div>}{conflict&&<ConflictBox/>}{error&&<ErrorBox error={error}/>} {notice&&<p role="status" className="notice">{notice}</p>}<div className="submit-row"><button className="primary" disabled={busy}>{busy?'处理中…':'安全保存'}</button></div></form></section>}
}
function ErrorBox({error,retry}:{error:BridgeClientError;retry?:()=>void}){return <div className="error" role="alert"><b>{error.message}</b><span>代码 {error.code} · 关联 {error.correlationId}{error.retryable?' · 可重试':''}</span>{retry&&<button onClick={retry}>重试</button>}</div>}
