import React,{useCallback,useEffect,useMemo,useRef,useState}from'react'
import{skillBridge,type SkillBridge}from'../bridge/client'
import type{SkillCatalogListResult,SkillCategory,SkillCategorySource,SkillDTO,SkillPermission,SkillStatus}from'../generated/bridge'
import{Dialog}from'../ui/Dialog'
import{SkillImportWizard}from'./SkillImportWizard'
import{searchRemoteSkillsLive,type RemoteSkillHit}from'./remoteSkillIndex'
import{usePanelResize}from'../ui/usePanelResize'

type CatalogEntry=SkillCatalogListResult['items'][number]
const STATUS:Record<SkillStatus,string>={draft:'草稿',published:'已发布',deprecated:'已弃用',disabled:'已禁用'}
const PERMISSION:Record<SkillPermission,string>={read_only:'只读',read_write:'读写',network:'网络',file_system:'文件系统',shell:'Shell',admin:'管理员'}
const CATEGORY:Record<SkillCategory,string>={efficiency:'效率',writing:'写作',development:'开发',data:'数据',design:'设计',research:'研究',lifestyle:'生活',education:'教育',business:'商业',automation:'自动化',security:'安全',other:'其他'}
const CATEGORY_SOURCE:Record<SkillCategorySource,string>={manual:'手动指定',manifest:'清单声明',keyword:'规则匹配'}
const FILTERS:Array<{id:SkillStatus|'';label:string}>=[{id:'',label:'全部'},{id:'draft',label:'草稿'},{id:'published',label:'已发布'},{id:'deprecated',label:'已弃用'},{id:'disabled',label:'已禁用'}]
const CATEGORY_FILTERS:Array<{id:SkillCategory|'';label:string}>=[{id:'',label:'全部'},...Object.entries(CATEGORY).map(([id,label])=>({id:id as SkillCategory,label}))]
const sourceLabel=(skill:SkillDTO)=>skill.category==='other'&&skill.categorySource==='keyword'?'默认':CATEGORY_SOURCE[skill.categorySource]
const trigger=(skill:SkillDTO)=>{try{const value=JSON.parse(skill.manifestJson)as{triggers?:string[]};return value.triggers?.join('、')||skill.entryPoint}catch{return skill.entryPoint}}
const signatureLabel=(skill:SkillDTO)=>skill.signature?'已提供签名':'未提供签名'

export function SkillPage({bridge=skillBridge,onCreateInChat,onViewInWorkspace,highlightId}:{bridge?:SkillBridge;onCreateInChat?:()=>void;onViewInWorkspace?:(path:string)=>void;highlightId?:string}):React.JSX.Element{
 const[items,setItems]=useState<SkillDTO[]>([]),[selectedId,setSelectedId]=useState(''),[filter,setFilter]=useState<SkillStatus|''>(''),[categoryFilter,setCategoryFilter]=useState<SkillCategory|''>(''),[query,setQuery]=useState(''),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState(''),[editing,setEditing]=useState(false),[displayName,setDisplayName]=useState(''),[description,setDescription]=useState(''),[entryPoint,setEntryPoint]=useState(''),[manifest,setManifest]=useState('')
 const[view,setView]=useState<'library'|'market'>('market'),[catalog,setCatalog]=useState<CatalogEntry[]>([]),[marketBusy,setMarketBusy]=useState(''),[marketQuery,setMarketQuery]=useState(''),[marketCategory,setMarketCategory]=useState(''),[marketError,setMarketError]=useState(''),[marketLoading,setMarketLoading]=useState(false),[addDialogOpen,setAddDialogOpen]=useState(false),[importOpen,setImportOpen]=useState(false),[importUrl,setImportUrl]=useState(''),[uploadNotice,setUploadNotice]=useState('')
 const fileInputRef=useRef<HTMLInputElement>(null)
 const[detailWidth,startDetailResize]=usePanelResize({storageKey:'lunitide:skill-detail-width',initial:380,min:280,max:()=>Math.min(560,Math.max(320,window.innerWidth-360)),reverse:true})
 const load=useCallback(async()=>{setLoading(true);setError('');try{const result=await bridge.list({});setItems(result.items);setSelectedId(current=>result.items.some(item=>item.id===current)?current:(result.items[0]?.id??''))}catch(e){setError(e instanceof Error?e.message:'技能载入失败')}finally{setLoading(false)}},[bridge])
 const loadCatalog=useCallback(async()=>{if(!bridge.catalogList){setMarketError('当前版本未提供技能模板目录。');return}setMarketLoading(true);setMarketError('');try{const result=await bridge.catalogList({});setCatalog(result.items??[])}catch(e){setCatalog([]);setMarketError(e instanceof Error?e.message:'技能市场加载失败')}finally{setMarketLoading(false)}},[bridge])
 useEffect(()=>{void load()},[load])
 useEffect(()=>{void loadCatalog()},[loadCatalog])
 useEffect(()=>{if(!highlightId)return;setView('library');setSelectedId(current=>items.some(item=>item.id===highlightId)?highlightId:current)},[highlightId,items])
 const install=async(entry:CatalogEntry)=>{if(!bridge.install||marketBusy)return;setMarketBusy(entry.id);setError('');try{await bridge.install({templateId:entry.id});await Promise.all([loadCatalog(),load()])}catch(e){setError(e instanceof Error?e.message:'安装失败')}finally{setMarketBusy('')}}
 const counts=useMemo(()=>Object.fromEntries(FILTERS.map(tab=>[tab.id,tab.id?items.filter(item=>item.status===tab.id).length:items.length])),[items])as Record<SkillStatus|'',number>
 const categoryCounts=useMemo(()=>Object.fromEntries(CATEGORY_FILTERS.map(tab=>[tab.id,tab.id?items.filter(item=>item.category===tab.id).length:items.length])),[items])as Record<SkillCategory|'',number>
 const visible=useMemo(()=>items.filter(item=>(!filter||item.status===filter)&&(!categoryFilter||item.category===categoryFilter)&&(!query.trim()||`${item.name} ${item.displayName} ${item.description}`.toLowerCase().includes(query.trim().toLowerCase()))),[categoryFilter,filter,items,query])
 const marketCategories=useMemo(()=>{const map=new Map<string,number>();for(const entry of catalog)map.set(entry.category,(map.get(entry.category)??0)+1);return[...map.entries()].sort((a,b)=>a[0].localeCompare(b[0],'zh'))},[catalog])
 const visibleCatalog=useMemo(()=>{const q=marketQuery.trim().toLowerCase();return catalog.filter(entry=>(!marketCategory||entry.category===marketCategory)&&(!q||`${entry.displayName} ${entry.description} ${entry.category} ${entry.source}`.toLowerCase().includes(q)))},[catalog,marketCategory,marketQuery])
 const featured=useMemo(()=>catalog.filter(entry=>entry.featured).slice(0,8),[catalog])
 const[remoteHits,setRemoteHits]=useState<RemoteSkillHit[]>([])
 const[remoteNotice,setRemoteNotice]=useState('')
 useEffect(()=>{let alive=true;void searchRemoteSkillsLive(marketQuery).then(result=>{if(!alive)return;setRemoteHits(result.hits);setRemoteNotice(result.notice??'')});return()=>{alive=false}},[marketQuery])
 const browsingAll=!marketCategory&&!marketQuery.trim()
 const listedCatalog=useMemo(()=>browsingAll?visibleCatalog.filter(entry=>!entry.featured):visibleCatalog,[browsingAll,visibleCatalog])
 const selected=items.find(item=>item.id===selectedId)??visible[0]
 const beginEdit=()=>{if(!selected)return;setDisplayName(selected.displayName);setDescription(selected.description);setEntryPoint(selected.entryPoint);setManifest(selected.manifestJson);setEditing(true)}
 const update=async()=>{if(!selected)return;setBusy(true);setError('');try{await bridge.update({id:selected.id,displayName:displayName.trim(),description,entryPoint:entryPoint.trim(),manifestJson:manifest,expectedVersion:1});setEditing(false);await load()}catch(e){setError(e instanceof Error?e.message:'技能更新失败')}finally{setBusy(false)}}
 const assignCategory=async(category:SkillCategory)=>{if(!selected||busy)return;setBusy(true);setError('');try{await bridge.categorySet?.({skillId:selected.id,category});await load()}catch(e){setError(e instanceof Error?e.message:'分类更新失败')}finally{setBusy(false)}}
 const lifecycle=async(op:'publish'|'deprecate'|'disable')=>{if(!selected)return;setBusy(true);setError('');try{await bridge[op]({id:selected.id});await load()}catch(e){setError(e instanceof Error?e.message:'技能状态更新失败')}finally{setBusy(false)}}
 const remove=async()=>{if(!selected||!window.confirm(`删除技能「${selected.displayName}」？`))return;setBusy(true);setError('');try{await bridge.delete({id:selected.id,expectedVersion:1});await load()}catch(e){setError(e instanceof Error?e.message:'技能删除失败')}finally{setBusy(false)}}
 const handleUpload=async()=>{const file=fileInputRef.current?.files?.[0];if(!file)return;setUploadNotice(`正在上传 ${file.name}…`);try{const text=await file.text();const manifest=JSON.parse(text);await bridge.create({name:manifest.name||file.name.replace(/\.skill$/,''),displayName:manifest.displayName||manifest.name||file.name,description:manifest.description||'',version:manifest.version||'1.0.0',permissions:manifest.permissions||[],entryPoint:manifest.entryPoint||'',manifestJson:text});setUploadNotice('');await load()}catch(e){setUploadNotice('');setError(e instanceof Error?e.message:'技能上传失败，请检查文件格式')}finally{if(fileInputRef.current)fileInputRef.current.value=''}}
 return <main className="skill-center">
  <header className="skill-center-header"><div><h1>技能中心</h1><p>{items.length} 个已安装 · 市场 {catalog.length} 个可点选安装</p><small>技能市场按分类浏览，点「＋」即可安装并在对话中使用。技能库管理你已经安装的技能。</small></div><button className="primary skill-chat-create" aria-label="添加技能" onClick={()=>setAddDialogOpen(true)}>+ 添加技能</button></header>
  <Dialog open={addDialogOpen} title="添加技能" description="选择添加技能的方式" onClose={()=>setAddDialogOpen(false)}><div className="skill-add-options"><button type="button" className="skill-add-option" onClick={()=>{setAddDialogOpen(false);fileInputRef.current?.click()}}><span className="skill-add-option-icon">📦</span><span className="skill-add-option-title">上传技能包</span><small>从本地导入 .skill 技能包文件，支持标准技能清单格式</small></button><button type="button" className="skill-add-option" onClick={()=>{setAddDialogOpen(false);onCreateInChat?.()}}><span className="skill-add-option-icon">💬</span><span className="skill-add-option-title">通过对话创建</span><small>在对话中描述需求，AI 引导你完成技能清单的六段画像，确认后生成技能</small></button><button type="button" className="skill-add-option" onClick={()=>{setAddDialogOpen(false);setImportOpen(true)}}><span className="skill-add-option-icon">🐙</span><span className="skill-add-option-title">从 GitHub 导入</span><small>输入仓库 URL 与 commit，经发现、检查、扫描与审批后导入</small></button></div><input ref={fileInputRef} hidden type="file" accept=".skill,application/json" onChange={()=>void handleUpload()}/></Dialog>
  <SkillImportWizard open={importOpen} onClose={()=>{setImportOpen(false);setImportUrl('')}} onApproved={()=>void load()} initialUrl={importUrl}/>
  <Dialog open={editing} wide title={selected?`编辑 ${selected.displayName}`:'编辑技能'} onClose={()=>{if(!busy)setEditing(false)}}>
   <form className="editor-dialog" onSubmit={e=>{e.preventDefault();void update()}}>
    <div className="form-grid">
     <label>显示名称<input value={displayName} onChange={e=>setDisplayName(e.target.value)}/></label>
     <label>入口路径<input value={entryPoint} onChange={e=>setEntryPoint(e.target.value)}/></label>
     <label className="wide">描述<textarea rows={3} value={description} onChange={e=>setDescription(e.target.value)}/></label>
     <label className="wide">技能清单 JSON<textarea className="skill-manifest-editor" rows={8} value={manifest} onChange={e=>setManifest(e.target.value)}/></label>
    </div>
    {error&&<p className="skill-center-error" role="alert">{error}</p>}
    <div className="dialog-actions"><button type="button" disabled={busy} onClick={()=>setEditing(false)}>取消</button><button className="primary" disabled={busy||!displayName.trim()||!entryPoint.trim()}>{busy?'保存中…':'保存修改'}</button></div>
   </form>
  </Dialog>
  {uploadNotice&&<p className="skill-center-notice" role="status">{uploadNotice}</p>}
  <section className="skill-center-toolbar"><div className="skill-status-tabs" role="tablist" aria-label="技能视图"><button type="button" role="tab" aria-selected={view==='library'} onClick={()=>setView('library')}>技能库</button><button type="button" role="tab" aria-selected={view==='market'} onClick={()=>setView('market')}>技能市场</button></div>{view==='library'&&<><div className="skill-status-tabs" role="tablist" aria-label="技能状态">{FILTERS.map(tab=><button type="button" role="tab" aria-selected={filter===tab.id} key={tab.id||'all'} onClick={()=>setFilter(tab.id)}>{tab.label}<small>{counts[tab.id]}</small></button>)}</div><label className="skill-search">搜索技能<input value={query} onChange={e=>setQuery(e.target.value)} placeholder="名称或描述"/></label><button aria-label="刷新技能" onClick={()=>void load()} disabled={loading}>↻</button></>}{view==='market'&&<><label className="skill-search">搜索市场<input value={marketQuery} onChange={e=>setMarketQuery(e.target.value)} placeholder="名称、分类或来源"/></label><button aria-label="刷新市场" onClick={()=>void loadCatalog()}>↻</button></>}</section>
  {error&&!editing&&<p className="skill-center-error" role="alert">{error}</p>}
  {view==='market'?<div className="skill-market-page" aria-label="技能市场">{marketLoading?<p role="status">正在载入技能市场…</p>:marketError?<div className="empty"><b>市场加载失败</b><span>{marketError}</span></div>:!catalog.length?<div className="empty"><b>目录为空</b><span>引擎没有返回可安装的技能模板。</span></div>:<>
    <nav className="skill-market-cats" aria-label="市场分类"><button type="button" aria-pressed={!marketCategory} onClick={()=>setMarketCategory('')}>全部<small>{catalog.length}</small></button>{marketCategories.map(([id,count])=><button type="button" key={id} aria-pressed={marketCategory===id} onClick={()=>setMarketCategory(id)}>{id}<small>{count}</small></button>)}</nav>
    {browsingAll&&featured.length>0&&<section className="skill-market-shelf" aria-label="推荐技能"><header><b>推荐技能</b><small>点选即可安装使用</small></header><div className="skill-market">{featured.map(entry=><MarketCard key={`feat-${entry.id}`} entry={entry} busy={marketBusy} onInstall={install}/>)}</div></section>}
    <section className="skill-market-shelf" aria-label="全部可安装技能"><header><b>{marketCategory||'全部技能'}</b><small>{listedCatalog.length} 个</small></header>{listedCatalog.length?<div className="skill-market">{listedCatalog.map(entry=><MarketCard key={entry.id} entry={entry} busy={marketBusy} onInstall={install}/>)}</div>:<div className="empty"><b>没有匹配的技能</b><span>{browsingAll&&featured.length?'其余技能都在推荐里。':'换个分类或关键字再试。'}</span></div>}</section>
    {(remoteHits.length>0||remoteNotice)&&<section className="skill-market-shelf" aria-label="远程检索"><header><b>远程检索</b><small>{remoteNotice||'只索引点名仓，命中后走 GitHub 导入审批，不会静默下载'}</small></header><div className="skill-market">{remoteHits.map(hit=><article className="skill-market-card" key={`${hit.sourceId}:${hit.slug}`}><header><span className="skill-market-glyph" aria-hidden="true">远</span><div><b>{hit.title}</b><small>{hit.sourceName}</small></div><button type="button" className="skill-market-add" aria-label={`导入 ${hit.title}`} onClick={()=>{setImportUrl(hit.repo);setImportOpen(true)}}>导入审批</button></header><p>{hit.summary}</p></article>)}</div></section>}
   </>}</div>
  :<div className="skill-center-layout" style={{'--detail-width':`${detailWidth}px`} as React.CSSProperties}>
   <section className="skill-table" aria-label="技能列表"><div className="skill-table-inner"><div className="skill-table-head"><span>技能</span><span>版本</span><span>状态</span><span>触发方式</span></div>{loading?<p role="status">正在载入技能…</p>:visible.length?visible.map(skill=><button type="button" className={`skill-row ${selected?.id===skill.id?'active':''} ${skill.id===highlightId?'is-highlight':''}`} key={skill.id} onClick={()=>{setSelectedId(skill.id);setEditing(false)}}><span><b>{skill.displayName}</b><small>{skill.description||skill.name}</small></span><code>v{skill.version}</code><i className={`skill-status status-${skill.status}`}>{STATUS[skill.status]}</i><code title={trigger(skill)}>{trigger(skill)}</code></button>):<div className="empty"><b>暂无技能</b><span>{query?'没有匹配的技能。':'当前状态下还没有技能，可通过聊天创建。'}</span></div>}</div></section>
   <div className="panel-resizer split-resizer" role="separator" aria-label="调整详情栏宽度" aria-orientation="vertical" onPointerDown={startDetailResize}/>
   <aside className="skill-detail" aria-label="技能详情">{selected?<><div className="skill-detail-title"><div><h2>{selected.displayName}</h2><code>{selected.name} · v{selected.version}</code></div><span className={`skill-status status-${selected.status}`}>{STATUS[selected.status]}</span></div><p>{selected.description||'暂无说明'}</p><h3>权限清单</h3><div className="skill-permissions">{selected.permissions.map(permission=><span key={permission}>{PERMISSION[permission]}</span>)}</div><h3>技能目录</h3><div className="skill-path"><button type="button" onClick={()=>onViewInWorkspace?.(selected.entryPoint)} aria-label={`在工作区查看 ${selected.entryPoint}`}>在工作区查看</button><code>{selected.entryPoint}</code></div><h3>触发器</h3><p><code>{trigger(selected)}</code></p><div className={`skill-signature ${selected.signature?'valid':'unsigned'}`}><b>{signatureLabel(selected)}</b><small>{selected.publisherId?`发布者 ${selected.publisherId}`:'本地技能；发布前请审阅权限和清单'}</small></div><div className="skill-detail-actions"><button onClick={beginEdit} disabled={busy}>编辑技能</button>{selected.status==='draft'&&<button onClick={()=>void lifecycle('publish')} disabled={busy}>发布</button>}{selected.status==='published'&&<button onClick={()=>void lifecycle('deprecate')} disabled={busy}>弃用</button>}{selected.status!=='disabled'&&<button onClick={()=>void lifecycle('disable')} disabled={busy}>禁用</button>}{(selected.status==='draft'||selected.status==='disabled')&&<button className="danger" onClick={()=>void remove()} disabled={busy}>删除</button>}</div></>:<div className="empty"><b>选择技能查看详情</b></div>}</aside>
  </div>}
 </main>
}

function MarketCard({entry,busy,onInstall}:{entry:CatalogEntry;busy:string;onInstall:(entry:CatalogEntry)=>void}):React.JSX.Element{
 return <article className={`skill-market-card ${entry.installed?'is-installed':''}`}><header><span className="skill-market-glyph" aria-hidden="true">{entry.displayName.slice(0,1)}</span><div><b>{entry.displayName}</b><small>{entry.source} · {entry.category}</small></div>{entry.installed?<span className="skill-market-installed">已安装</span>:<button type="button" className="skill-market-add" aria-label={`安装 ${entry.displayName}`} disabled={Boolean(busy)} onClick={()=>void onInstall(entry)}>{busy===entry.id?'…':'＋'}</button>}</header><p>{entry.description}</p><footer><small>v{entry.version}</small><div className="skill-permissions">{entry.permissions.map(permission=><span key={permission}>{PERMISSION[permission]}</span>)}</div></footer></article>
}
