import{cleanup,fireEvent,render,screen}from'@testing-library/react'
import userEvent from'@testing-library/user-event'
import{afterEach,expect,it,vi}from'vitest'

const {mockSkillCreator,mockEnsureSkillCreator,mockExpertManager,mockEnsureExpertManager}=vi.hoisted(()=>{const mockSkillCreator={id:'01ARZ3NDEKTSV4RRFFQ69G5FBB',name:'skill-creator',displayName:'skill-creator',description:'Create new skills',version:'1.0.0',status:'published' as const,permissions:['read_write','file_system','shell'] as const,entryPoint:'builtin://skill-creator',manifestJson:'{}',category:'development' as const,categorySource:'manifest' as const,createdAt:'2026-01-01T00:00:00Z',updatedAt:'2026-01-01T00:00:00Z'};const mockExpertManager={id:'01ARZ3NDEKTSV4RRFFQ69G5FBC',name:'expert-manager',displayName:'expert-manager',description:'Create experts',version:'1.0.0',status:'published' as const,permissions:['read_write'] as const,entryPoint:'builtin://expert-manager',manifestJson:'{}',category:'development' as const,categorySource:'manifest' as const,createdAt:'2026-01-01T00:00:00Z',updatedAt:'2026-01-01T00:00:00Z'};return{mockSkillCreator,mockEnsureSkillCreator:vi.fn().mockResolvedValue(mockSkillCreator),mockExpertManager,mockEnsureExpertManager:vi.fn().mockResolvedValue(mockExpertManager)}})
vi.mock('./skill/ensureSkillCreator',()=>({SKILL_CREATE_PROMPT:'请帮我创建一个可以实现「……」的skill',SKILL_CREATOR_NAME:'skill-creator',SKILL_CREATOR_TEMPLATE_ID:'skill-creator',ensureSkillCreator:mockEnsureSkillCreator}))
vi.mock('./skill/ensureExpertManager',()=>({EXPERT_CREATE_PROMPT:'帮我创建一个 XXX 专家，擅长 XXXXX。我的经验是：[请补充你的行业背景、相关经验]',EXPERT_MANAGER_NAME:'expert-manager',EXPERT_MANAGER_TEMPLATE_ID:'expert-manager',ensureExpertManager:mockEnsureExpertManager}))
vi.mock('./bridge/client',async importOriginal=>{const actual=await importOriginal<typeof import('./bridge/client')>();return{...actual,templateBridge:{list:vi.fn().mockResolvedValue({items:[]}),create:vi.fn(),enable:vi.fn(),void:vi.fn(),delete:vi.fn()},deliverableBridge:{list:vi.fn().mockResolvedValue({items:[]}),upsert:vi.fn(),confirmGate:vi.fn()},stageBridge:{...actual.stageBridge,list:vi.fn().mockResolvedValue({items:[]}),create:vi.fn(),update:vi.fn()}}})

import type{ChatBridge,MessageBridge,ProjectBridge,ProviderBridge,SessionBridge}from'./bridge/client'
import type{ProjectDTO}from'./generated/bridge'
import{App,PERSONAL_CHAT_PROJECT}from'./App'
import{SKILL_CREATE_PROMPT}from'./skill/ensureSkillCreator'
import{EXPERT_CREATE_PROMPT}from'./skill/ensureExpertManager'
afterEach(cleanup)
const now='2026-01-01T00:00:00Z'
const personal:ProjectDTO={id:'01ARZ3NDEKTSV4RRFFQ69G5FAV',name:PERSONAL_CHAT_PROJECT,projectCode:'ITM00000',type:'implementation',status:'active',createdAt:now,updatedAt:now,version:1}
const project:ProjectDTO={id:'01ARZ3NDEKTSV4RRFFQ69G5FAA',name:'Moon',projectCode:'ITM00001',type:'implementation',status:'active',createdAt:now,updatedAt:now,version:1}
const messages:MessageBridge={list:vi.fn().mockResolvedValue({items:[],hasMore:false,nextCursor:null,snapshotSequence:0}),append:vi.fn()}
const chat:ChatBridge={start:vi.fn(),approve:vi.fn(),dispose:vi.fn()}
const providers:ProviderBridge={list:vi.fn().mockResolvedValue({items:[]}),get:vi.fn(),create:vi.fn(),update:vi.fn(),delete:vi.fn(),revealCredential:vi.fn(),submitCredential:vi.fn(),syncModels:vi.fn(),test:vi.fn()}as ProviderBridge
const projectBridge=(items:ProjectDTO[]=[project]):ProjectBridge=>({list:vi.fn().mockResolvedValue({items}),create:vi.fn(),update:vi.fn(),publish:vi.fn(),close:vi.fn(),reopen:vi.fn(),advanceStatus:vi.fn(),delete:vi.fn()})
const sessionBridge=(items:any[]=[]):SessionBridge=>({list:vi.fn().mockResolvedValue({items}),create:vi.fn(),update:vi.fn(),delete:vi.fn()})

it('opens on ordinary chat and keeps providers inside settings',async()=>{const user=userEvent.setup();render(<App projects={projectBridge([])} sessions={sessionBridge()} providers={providers} messages={messages} chat={chat}/>);expect(await screen.findByRole('heading',{name:'今天想聊什么？'})).toBeInTheDocument();expect(screen.getByRole('button',{name:/新对话/})).toBeInTheDocument();expect(screen.queryByRole('button',{name:'模型与供应商'})).not.toBeInTheDocument();await user.click(screen.getByRole('button',{name:'设置'}));expect(await screen.findByRole('button',{name:'← 返回主页'})).toBeInTheDocument();await user.click(screen.getByRole('button',{name:'模型与供应商'}));await user.click(screen.getByRole('button',{name:'打开供应商管理'}));expect(await screen.findByText('还没有供应商')).toBeInTheDocument();expect(screen.getByRole('button',{name:'← 返回设置'})).toBeInTheDocument()})

it('opens project management before entering a project workbench and returns to it',async()=>{const projects=projectBridge([personal,project]),sessions=sessionBridge(),user=userEvent.setup();render(<App projects={projects} sessions={sessions} messages={messages} chat={chat} providers={providers}/>);const entries=await screen.findAllByRole('button',{name:'项目管理'});await user.click(entries[0]);expect(await screen.findByRole('heading',{name:'项目管理'})).toBeInTheDocument();expect(screen.queryByText(PERSONAL_CHAT_PROJECT)).not.toBeInTheDocument();const enterButtons=screen.getAllByRole('button',{name:'进入工作台'});await user.click(enterButtons[0]);expect(await screen.findByRole('heading',{name:'Moon · 会话'})).toBeInTheDocument();expect(sessions.list).toHaveBeenCalledWith({projectId:project.id});const backButtons=screen.getAllByRole('button',{name:'← 返回项目管理'});await user.click(backButtons[0]);expect(await screen.findByRole('heading',{name:'项目管理'})).toBeInTheDocument()})

it('opens Skill Center from the sidebar under project management with chat-based creation',async()=>{const user=userEvent.setup();render(<App projects={projectBridge([])} sessions={sessionBridge()} messages={messages} chat={chat} providers={providers}/>);await user.click(await screen.findByRole('button',{name:'技能中心'}));expect((await screen.findAllByRole('heading',{name:'技能中心'})).length).toBeGreaterThan(0);await user.click(screen.getByRole('button',{name:'添加技能'}));expect(await screen.findByRole('dialog',{name:'添加技能'})).toBeInTheDocument();expect(screen.getByRole('button',{name:/上传技能包/})).toBeInTheDocument();expect(screen.getByRole('button',{name:/通过对话创建/})).toBeInTheDocument()})

it('keeps expert center and asset management as sidebar entries with real panels',async()=>{const user=userEvent.setup();render(<App projects={projectBridge([])} sessions={sessionBridge()} messages={messages} chat={chat} providers={providers}/>);await user.click(await screen.findByRole('button',{name:'资产管理'}));expect(await screen.findByLabelText('搜索资产')).toBeInTheDocument();expect(screen.queryByText('规划中')).not.toBeInTheDocument();await user.click(screen.getByRole('button',{name:'专家中心'}));expect(await screen.findByText('专家中心',{selector:'.view-title'})).toBeInTheDocument();expect(screen.getByLabelText('搜索专家')).toBeInTheDocument();expect(screen.queryByText('规划中')).not.toBeInTheDocument()})

it('starts skill creation in ordinary chat with the full prompt and files workspace',async()=>{const session={id:'01ARZ3NDEKTSV4RRFFQ69G5FAW',projectId:personal.id,title:'创建技能',status:'active' as const,createdAt:now,updatedAt:now,version:1},projects=projectBridge([personal]),sessions={...sessionBridge(),create:vi.fn().mockResolvedValue(session)},user=userEvent.setup();render(<App projects={projects} sessions={sessions} messages={messages} chat={chat} providers={providers}/>);await user.click(await screen.findByRole('button',{name:'技能中心'}));await user.click(screen.getByRole('button',{name:'添加技能'}));await user.click(await screen.findByRole('button',{name:/通过对话创建/}));expect(await screen.findByLabelText('创建技能 消息')).toHaveClass('personal-message-panel');expect(screen.getByRole('textbox',{name:'向月汐提问，或描述你想完成的任务…'})).toHaveValue(SKILL_CREATE_PROMPT);expect(screen.getByRole('list',{name:'已引用技能'})).toHaveTextContent('skill-creator');expect(screen.getByRole('tab',{name:'文件'})).toHaveAttribute('aria-selected','true');expect(await screen.findByRole('region',{name:'技能包目录'})).toBeInTheDocument();expect(screen.queryByText('知域宫殿')).not.toBeInTheDocument();expect(sessions.create).toHaveBeenCalledWith({projectId:personal.id,title:'创建技能'},expect.objectContaining({attempt:expect.any(Object)}));expect(screen.queryByRole('button',{name:'创建技能'})).not.toBeInTheDocument()})

it('deletes an empty skill-creation draft when leaving without sending a message',async()=>{const session={id:'01ARZ3NDEKTSV4RRFFQ69G5FAW',projectId:personal.id,title:'创建技能',status:'active' as const,createdAt:now,updatedAt:now,version:1},remove=vi.fn().mockResolvedValue({deleted:true,id:session.id}),sessions={...sessionBridge(),create:vi.fn().mockResolvedValue(session),delete:remove},user=userEvent.setup();render(<App projects={projectBridge([personal])} sessions={sessions} messages={messages} chat={chat} providers={providers}/>);await user.click(await screen.findByRole('button',{name:'技能中心'}));await user.click(screen.getByRole('button',{name:'添加技能'}));await user.click(await screen.findByRole('button',{name:/通过对话创建/}));await user.click(await screen.findByRole('button',{name:'← 返回主页'}));expect(await screen.findByRole('heading',{name:'今天想聊什么？'})).toBeInTheDocument();await vi.waitFor(()=>expect(remove).toHaveBeenCalledWith({id:session.id},expect.objectContaining({attempt:expect.any(Object)})));expect(screen.queryByRole('button',{name:'创建技能'})).not.toBeInTheDocument();expect(screen.getByText('还没有对话')).toBeInTheDocument()})

it('starts expert creation in ordinary chat with expert-manager and template prompt',async()=>{const session={id:'01ARZ3NDEKTSV4RRFFQ69G5FAW',projectId:personal.id,title:'创建专家',status:'active' as const,createdAt:now,updatedAt:now,version:1},projects=projectBridge([personal]),sessions={...sessionBridge(),create:vi.fn().mockResolvedValue(session)},user=userEvent.setup();render(<App projects={projects} sessions={sessions} messages={messages} chat={chat} providers={providers}/>);await user.click(await screen.findByRole('button',{name:'专家中心'}));await user.click(await screen.findByRole('button',{name:'＋ 创建专家'}));expect(await screen.findByLabelText('创建专家 消息')).toHaveClass('personal-message-panel');expect(screen.getByRole('textbox',{name:'向月汐提问，或描述你想完成的任务…'})).toHaveValue(EXPERT_CREATE_PROMPT);expect(screen.getByRole('list',{name:'已引用技能'})).toHaveTextContent('expert-manager');expect(screen.getByRole('tab',{name:'文件'})).toHaveAttribute('aria-selected','true');expect(sessions.create).toHaveBeenCalledWith({projectId:personal.id,title:'创建专家'},expect.objectContaining({attempt:expect.any(Object)}))})

it('creates an isolated ordinary-chat session and automatically starts the selected model',async()=>{const session={id:'01ARZ3NDEKTSV4RRFFQ69G5FAW',projectId:personal.id,title:'Hello',status:'active' as const,createdAt:now,updatedAt:now,version:1},provider={id:'01ARZ3NDEKTSV4RRFFQ69G5FAX',name:'Ready',protocol:'openai_compatible' as const,baseUrl:'https://example.test',models:[{modelId:'m-one',displayName:'Model One',isDefault:true}],status:'enabled' as const,credentialState:'configured' as const,createdAt:now,updatedAt:now,version:1},projects=projectBridge([personal]),sessions={...sessionBridge(),create:vi.fn().mockResolvedValue(session)},append=vi.fn().mockResolvedValue({}),start=vi.fn().mockResolvedValue({streamId:'01ARZ3NDEKTSV4RRFFQ69G5FAY',cancel:vi.fn(),dispose:vi.fn()}),user=userEvent.setup();render(<App projects={projects} sessions={sessions} providers={{...providers,list:vi.fn().mockResolvedValue({items:[provider]})}} messages={{...messages,append}} chat={{start,dispose:vi.fn()}}/>);await user.type(await screen.findByLabelText('输入消息'),'Hello');await user.click(screen.getByRole('button',{name:'开始对话'}));expect(await screen.findByRole('button',{name:'← 返回主页'})).toBeInTheDocument();expect(screen.queryByRole('heading',{name:/· 会话/})).not.toBeInTheDocument();await vi.waitFor(()=>expect(append).toHaveBeenCalledOnce());expect(sessions.create).toHaveBeenCalledWith({projectId:personal.id,title:'Hello'},expect.objectContaining({attempt:expect.any(Object)}));expect(start).toHaveBeenCalledWith({providerId:provider.id,modelId:'m-one',sessionId:session.id,executionMode:'full-access',companion:false},expect.any(Function))})

it('sends the launch message with Enter, keeps the sidebar, and uses Shift+Enter for a newline',async()=>{const session={id:'01ARZ3NDEKTSV4RRFFQ69G5FAW',projectId:personal.id,title:'Hello',status:'active' as const,createdAt:now,updatedAt:now,version:1},provider={id:'01ARZ3NDEKTSV4RRFFQ69G5FAX',name:'Ready',protocol:'openai_compatible' as const,baseUrl:'https://example.test',models:[{modelId:'m-one',displayName:'Model One',isDefault:true}],status:'enabled' as const,credentialState:'configured' as const,createdAt:now,updatedAt:now,version:1},sessions={...sessionBridge(),create:vi.fn().mockResolvedValue(session)},user=userEvent.setup();render(<App projects={projectBridge([personal])} sessions={sessions} providers={{...providers,list:vi.fn().mockResolvedValue({items:[provider]})}} messages={messages} chat={chat}/>);const input=await screen.findByLabelText('输入消息');await user.type(input,'line one{Shift>}{Enter}{/Shift}line two');expect(input).toHaveValue('line one\nline two');await user.keyboard('{Enter}');expect(await screen.findByRole('button',{name:/新对话/})).toBeInTheDocument();expect(await screen.findByLabelText(`${session.title} 消息`)).toHaveClass('personal-message-panel');expect(sessions.create).toHaveBeenCalledOnce()})

it('rejects an oversized launch message before creating a session',async()=>{const provider={id:'01ARZ3NDEKTSV4RRFFQ69G5FAX',name:'Ready',protocol:'openai_compatible' as const,baseUrl:'https://example.test',models:[{modelId:'m-one',displayName:'Model One',isDefault:true}],status:'enabled' as const,credentialState:'configured' as const,createdAt:now,updatedAt:now,version:1},sessions=sessionBridge(),user=userEvent.setup();render(<App projects={projectBridge([personal])} sessions={sessions} providers={{...providers,list:vi.fn().mockResolvedValue({items:[provider]})}} messages={messages} chat={chat}/>);const input=await screen.findByLabelText('输入消息');fireEvent.change(input,{target:{value:'x'.repeat(2049)}});await user.click(screen.getByRole('button',{name:'开始对话'}));expect(await screen.findByText(/1–2048/)).toBeInTheDocument();expect(sessions.create).not.toHaveBeenCalled()})

it('Ctrl+N resets the ordinary-chat draft',async()=>{const user=userEvent.setup();render(<App projects={projectBridge([])} sessions={sessionBridge()} providers={providers} messages={messages} chat={chat}/>);const input=await screen.findByLabelText('输入消息');await user.type(input,'discard me');await user.keyboard('{Control>}n{/Control}');expect(await screen.findByLabelText('输入消息')).toHaveValue('')})

it('shows only ordinary-chat history in the conversation group',async()=>{const personalSession={id:'01ARZ3NDEKTSV4RRFFQ69G5FAZ',projectId:personal.id,title:'Normal chat',status:'active' as const,createdAt:'2027-01-01T00:00:00Z',updatedAt:'2027-01-01T00:00:00Z',version:1},list=vi.fn().mockResolvedValue({items:[personalSession]}),sessions:SessionBridge={list,create:vi.fn(),update:vi.fn(),delete:vi.fn()};render(<App projects={projectBridge([personal,project])} sessions={sessions} providers={providers} messages={messages} chat={chat}/>);expect(await screen.findByText('Normal chat')).toBeInTheDocument();expect(screen.queryByText('Moon')).not.toBeInTheDocument();expect(list).toHaveBeenCalledTimes(1);expect(list).toHaveBeenCalledWith({projectId:personal.id})})

it('restores ordinary-chat history by its stable id when the stored project name is damaged',async()=>{const damaged={...personal,name:'\u2063��ϫ����ͨ�Ի�'},historical={id:'01ARZ3NDEKTSV4RRFFQ69G5FAZ',projectId:damaged.id,title:'Recovered history',status:'active' as const,createdAt:now,updatedAt:now,version:1},list=vi.fn().mockResolvedValue({items:[historical]});localStorage.setItem('lunitide:personal-chat-project-id',damaged.id);render(<App projects={projectBridge([damaged,project])} sessions={{...sessionBridge(),list}} providers={providers} messages={messages} chat={chat}/>);expect(await screen.findByText('Recovered history')).toBeInTheDocument();expect(list).toHaveBeenCalledWith({projectId:damaged.id})})

it('recognizes a legacy hidden ordinary-chat project even when its saved id is unavailable',async()=>{const damaged={...personal,name:'\u2063legacy-damaged-name'},historical={id:'01ARZ3NDEKTSV4RRFFQ69G5FAZ',projectId:damaged.id,title:'Legacy history',status:'active' as const,createdAt:now,updatedAt:now,version:1},list=vi.fn().mockResolvedValue({items:[historical]});localStorage.removeItem('lunitide:personal-chat-project-id');render(<App projects={projectBridge([damaged,project])} sessions={{...sessionBridge(),list}} providers={providers} messages={messages} chat={chat}/>);expect(await screen.findByText('Legacy history')).toBeInTheDocument();expect(list).toHaveBeenCalledWith({projectId:damaged.id})})

it('refreshes ordinary-chat history after returning home',async()=>{const created={id:'01ARZ3NDEKTSV4RRFFQ69G5FAZ',projectId:personal.id,title:'New history item',status:'active' as const,createdAt:'2027-01-01T00:00:00Z',updatedAt:'2027-01-01T00:00:00Z',version:1},list=vi.fn().mockResolvedValueOnce({items:[]}).mockResolvedValue({items:[created]}),sessions:SessionBridge={list,create:vi.fn().mockResolvedValue(created),update:vi.fn(),delete:vi.fn()},provider={id:'01ARZ3NDEKTSV4RRFFQ69G5FAX',name:'Ready',protocol:'openai_compatible' as const,baseUrl:'https://example.test',models:[{modelId:'m-one',displayName:'Model One',isDefault:true}],status:'enabled' as const,credentialState:'configured' as const,createdAt:now,updatedAt:now,version:1},user=userEvent.setup();render(<App projects={projectBridge([personal])} sessions={sessions} providers={{...providers,list:vi.fn().mockResolvedValue({items:[provider]})}} messages={messages} chat={chat}/>);await user.type(await screen.findByLabelText('输入消息'),'New history item');await user.click(screen.getByRole('button',{name:'开始对话'}));await user.click(await screen.findByRole('button',{name:'← 返回主页'}));expect(await screen.findByText('New history item')).toBeInTheDocument();expect(list.mock.calls.length).toBeGreaterThanOrEqual(2)})

it('never disposes an injected chat bridge on unmount',()=>{const injected={start:vi.fn(),approve:vi.fn(),dispose:vi.fn()}as ChatBridge,view=render(<App projects={projectBridge([])} sessions={sessionBridge()} providers={providers} messages={messages} chat={injected}/>);view.unmount();expect(injected.dispose).not.toHaveBeenCalled()})

it('offers file, folder, context, and command entries from the launch composer',async()=>{const user=userEvent.setup();render(<App projects={projectBridge([])} sessions={sessionBridge()} providers={providers} messages={messages} chat={chat}/>);await user.click(await screen.findByRole('button',{name:'添加上下文'}));expect(screen.getByRole('button',{name:/附件 \/ 文件/})).toBeInTheDocument();expect(screen.getByRole('button',{name:/上传文件夹/})).toBeInTheDocument();expect(screen.getByRole('button',{name:/@ 上下文/})).toBeInTheDocument();expect(screen.getByRole('button',{name:/\/ 命令与技能/})).toBeInTheDocument();const folder=document.querySelector('input[webkitdirectory]');expect(folder).not.toBeNull()})

it('preserves the launch draft while model settings opens and closes',async()=>{const user=userEvent.setup();render(<App projects={projectBridge([])} sessions={sessionBridge()} providers={providers} messages={messages} chat={chat}/>);const input=await screen.findByLabelText('输入消息');await user.type(input,'保留草稿');await user.click(screen.getByRole('button',{name:/选择模型/}));await user.click(screen.getByRole('button',{name:'配置供应商与模型'}));expect(screen.getByRole('dialog',{name:'模型与供应商配置'})).toBeInTheDocument();await user.click(screen.getByRole('button',{name:'← 返回对话'}));expect(screen.getByLabelText('输入消息')).toHaveValue('保留草稿')})

it('synchronizes restored and toggled themes with the native host',async()=>{localStorage.setItem('lunitide:theme','light');const set=vi.fn().mockResolvedValue({applied:true}),user=userEvent.setup();render(<App projects={projectBridge([])} sessions={sessionBridge()} providers={providers} messages={messages} chat={chat} nativeTheme={{set}}/>);await vi.waitFor(()=>expect(set).toHaveBeenCalledWith({theme:'light'}));await user.click(screen.getByRole('button',{name:'切换到黑夜模式'}));await vi.waitFor(()=>expect(set).toHaveBeenLastCalledWith({theme:'dark'}))})


it('offers persistent pin, rename, and confirmed delete actions for each chat',async()=>{const original={id:'01ARZ3NDEKTSV4RRFFQ69G5FAZ',projectId:personal.id,title:'Action chat',pinned:false,status:'active' as const,createdAt:now,updatedAt:now,version:1},update=vi.fn().mockImplementation(async p=>({...original,title:p.title,pinned:p.pinned,updatedAt:'2026-01-02T00:00:00Z',version:p.version+1})),remove=vi.fn().mockResolvedValue({deleted:true,id:original.id}),sessions:SessionBridge={list:vi.fn().mockResolvedValue({items:[original]}),create:vi.fn(),update,delete:remove},user=userEvent.setup();render(<App projects={projectBridge([personal])} sessions={sessions} providers={providers} messages={messages} chat={chat}/>);await user.click(await screen.findByRole('button',{name:'更多操作 Action chat'}));expect(screen.getByRole('menuitem',{name:'置顶'})).toBeInTheDocument();expect(screen.getByRole('menuitem',{name:'重命名'})).toBeInTheDocument();expect(screen.getByRole('menuitem',{name:'删除'})).toBeInTheDocument();await user.click(screen.getByRole('menuitem',{name:'置顶'}));await vi.waitFor(()=>expect(update).toHaveBeenCalledWith({id:original.id,title:'Action chat',pinned:true,version:1},expect.objectContaining({attempt:expect.any(Object)})));await user.click(screen.getByRole('button',{name:'更多操作 Action chat'}));await user.click(screen.getByRole('menuitem',{name:'重命名'}));const input=screen.getByLabelText('会话名称');await user.clear(input);await user.type(input,'Renamed chat');await user.click(screen.getByRole('button',{name:'保存'}));await vi.waitFor(()=>expect(update).toHaveBeenLastCalledWith(expect.objectContaining({id:original.id,title:'Renamed chat',pinned:true,version:2}),expect.any(Object)));await user.click(screen.getByRole('button',{name:'更多操作 Renamed chat'}));await user.click(screen.getByRole('menuitem',{name:'删除'}));expect(screen.getByRole('dialog',{name:'删除会话「Renamed chat」？'})).toBeInTheDocument();expect(remove).not.toHaveBeenCalled();await user.click(screen.getByRole('button',{name:'确认删除'}));await vi.waitFor(()=>expect(remove).toHaveBeenCalledOnce());expect(screen.queryByText('Renamed chat')).not.toBeInTheDocument()})

it('returns home and removes the sidebar item after deleting the active last chat',async()=>{const original={id:'01ARZ3NDEKTSV4RRFFQ69G5FAZ',projectId:personal.id,title:'Last chat',status:'active' as const,createdAt:now,updatedAt:now,version:1};let items=[original];const sessions:SessionBridge={list:vi.fn().mockImplementation(async()=>({items})),create:vi.fn(),update:vi.fn(),delete:vi.fn().mockImplementation(async()=>{items=[];return{deleted:true,id:original.id}})},user=userEvent.setup();render(<App projects={projectBridge([personal])} sessions={sessions} providers={providers} messages={messages} chat={chat}/>);await user.click(await screen.findByRole('button',{name:'Last chat'}));expect(await screen.findByLabelText('Last chat 消息')).toBeInTheDocument();await user.click(screen.getByRole('button',{name:'更多操作 Last chat'}));await user.click(screen.getByRole('menuitem',{name:'删除'}));await user.click(screen.getByRole('button',{name:'确认删除'}));expect(await screen.findByRole('heading',{name:'今天想聊什么？'})).toBeInTheDocument();await vi.waitFor(()=>expect(screen.queryByRole('button',{name:'Last chat'})).not.toBeInTheDocument());expect(screen.getByText('还没有对话')).toBeInTheDocument()})

it('deletes the session, returns home, and clears the sidebar after removing the final round',async()=>{const original={id:'01ARZ3NDEKTSV4RRFFQ69G5FAZ',projectId:personal.id,title:'Only round',status:'active' as const,createdAt:now,updatedAt:now,version:1},question={id:'01ARZ3NDEKTSV4RRFFQ69G5FAY',sessionId:original.id,role:'user' as const,status:'completed' as const,sequence:1,text:'最后一问',createdAt:now},answer={...question,id:'01ARZ3NDEKTSV4RRFFQ69G5FAX',role:'assistant' as const,sequence:2,text:'最后一答'};let items=[original];const sessions:SessionBridge={list:vi.fn().mockImplementation(async()=>({items})),create:vi.fn(),update:vi.fn(),delete:vi.fn().mockImplementation(async()=>{items=[];return{deleted:true,id:original.id}})},rewind=vi.fn().mockResolvedValue({sessionId:original.id,messageId:question.id,deletedCount:2,lastSequence:0,historyRevision:2}),user=userEvent.setup();render(<App projects={projectBridge([personal])} sessions={sessions} providers={providers} messages={{...messages,list:vi.fn().mockResolvedValue({items:[question,answer],hasMore:false,nextCursor:null,snapshotSequence:2}),rewind}} chat={chat}/>);await user.click(await screen.findByRole('button',{name:'Only round'}));await screen.findByText('最后一答');await user.click(screen.getByRole('button',{name:'删除'}));await user.click(screen.getByRole('button',{name:'确认删除'}));expect(await screen.findByRole('heading',{name:'今天想聊什么？'})).toBeInTheDocument();expect(screen.queryByRole('button',{name:'Only round'})).not.toBeInTheDocument();expect(screen.getByText('还没有对话')).toBeInTheDocument()})

it('searches chat titles and message text with Ctrl+K and opens the selected history',async()=>{const weather={id:'01ARZ3NDEKTSV4RRFFQ69G5FAZ',projectId:personal.id,title:'上海天气',status:'active' as const,createdAt:now,updatedAt:now,version:1},coding={...weather,id:'01ARZ3NDEKTSV4RRFFQ69G5FAY',title:'代码讨论'},list=vi.fn().mockImplementation(async({sessionId})=>({items:sessionId===coding.id?[{id:'01ARZ3NDEKTSV4RRFFQ69G5FAX',sessionId:coding.id,role:'user',status:'completed',sequence:1,text:'这里谈到了月汐功能',createdAt:now},{id:'01ARZ3NDEKTSV4RRFFQ69G5FAW',sessionId:coding.id,role:'assistant',status:'completed',sequence:2,text:'也谈到了历史搜索',createdAt:now}]:[],hasMore:false,nextCursor:null,snapshotSequence:2})),user=userEvent.setup();render(<App projects={projectBridge([personal])} sessions={sessionBridge([weather,coding])} providers={providers} messages={{...messages,list}} chat={chat}/>);await screen.findByText('上海天气');await user.keyboard('{Control>}k{/Control}');const dialog=await screen.findByRole('dialog',{name:'搜索历史对话'}),input=screen.getByRole('textbox',{name:'搜索对话标题和内容'});await user.type(input,'月汐 搜索');const result=await vi.waitFor(()=>{const button=dialog.querySelector<HTMLButtonElement>('.conversation-search-results>button');expect(button).toHaveTextContent('代码讨论');expect(button).toHaveTextContent(/月汐|搜索/);return button!});expect(dialog).not.toHaveTextContent('上海天气');await user.click(result);expect(await screen.findByLabelText('代码讨论 消息')).toBeInTheDocument()})
