import{cleanup,fireEvent,render,screen}from'@testing-library/react'
import userEvent from'@testing-library/user-event'
import{afterEach,expect,it,vi}from'vitest'

const {mockSkillCreator,mockEnsureSkillCreator,mockExpertManager,mockEnsureExpertManager,mockPluginCreator,mockEnsurePluginCreator,getIdentityBridgeMock,getPeopleBridgeMock,getMeetingsBridgeMock,mockPeopleThreadList}=vi.hoisted(()=>{const mockSkillCreator={id:'01ARZ3NDEKTSV4RRFFQ69G5FBB',name:'skill-creator',displayName:'skill-creator',description:'Create new skills',version:'1.0.0',status:'published' as const,permissions:['read_write','file_system','shell'] as const,entryPoint:'builtin://skill-creator',manifestJson:'{}',category:'development' as const,categorySource:'manifest' as const,createdAt:'2026-01-01T00:00:00Z',updatedAt:'2026-01-01T00:00:00Z'};const mockExpertManager={id:'01ARZ3NDEKTSV4RRFFQ69G5FBC',name:'expert-manager',displayName:'expert-manager',description:'Create experts',version:'1.0.0',status:'published' as const,permissions:['read_write'] as const,entryPoint:'builtin://expert-manager',manifestJson:'{}',category:'development' as const,categorySource:'manifest' as const,createdAt:'2026-01-01T00:00:00Z',updatedAt:'2026-01-01T00:00:00Z'};const mockPluginCreator={id:'01ARZ3NDEKTSV4RRFFQ69G5FBD',name:'plugin-creator',displayName:'plugin-creator',description:'Create plugins',version:'1.0.0',status:'published' as const,permissions:['read_write'] as const,entryPoint:'builtin://plugin-creator',manifestJson:'{}',category:'development' as const,categorySource:'manifest' as const,createdAt:'2026-01-01T00:00:00Z',updatedAt:'2026-01-01T00:00:00Z'};const identityDTO={subjectId:'01ARZ3NDEKTSV4RRFFQ69G5FAV',nickname:'mu',avatar:'',status:'online' as const,department:'',title:'',orgName:'',bio:'',publicKey:'aa'.repeat(32),pairingCode:'111111',passwordSet:false,locked:false,discoveryEnabled:false,createdAt:'2026-01-01T00:00:00Z',updatedAt:'2026-01-01T00:00:00Z'};const identity={get:vi.fn().mockResolvedValue(identityDTO),update:vi.fn(),passwordSet:vi.fn(),unlock:vi.fn()};const mockPeopleThreadList=vi.fn().mockResolvedValue({items:[]});const people={list:vi.fn().mockResolvedValue({items:[]}),pair:vi.fn(),discoveryGet:vi.fn().mockResolvedValue({enabled:false,pairingCode:'111111'}),discoverySet:vi.fn(),threadList:mockPeopleThreadList,threadOpen:vi.fn(),threadSend:vi.fn(),threadTyping:vi.fn(),groupCreate:vi.fn(),fileDecide:vi.fn(),fileOpen:vi.fn(),fileStage:vi.fn(),filePick:vi.fn(),screenCapture:vi.fn(),peerAdd:vi.fn(),contactUpdate:vi.fn()};const meetings={list:vi.fn().mockResolvedValue({items:[]}),start:vi.fn(),append:vi.fn(),loopbackPoll:vi.fn(),stop:vi.fn(),get:vi.fn(),summarize:vi.fn(),exportMeeting:vi.fn(),update:vi.fn(),delete:vi.fn()};return{mockSkillCreator,mockEnsureSkillCreator:vi.fn().mockResolvedValue(mockSkillCreator),mockExpertManager,mockEnsureExpertManager:vi.fn().mockResolvedValue(mockExpertManager),mockPluginCreator,mockEnsurePluginCreator:vi.fn().mockResolvedValue(mockPluginCreator),getIdentityBridgeMock:()=>identity,getPeopleBridgeMock:()=>people,getMeetingsBridgeMock:()=>meetings,mockPeopleThreadList}})
vi.mock('./skill/ensureSkillCreator',()=>({SKILL_CREATE_PROMPT:'请帮我创建一个可以实现「……」的skill',SKILL_CREATOR_NAME:'skill-creator',SKILL_CREATOR_TEMPLATE_ID:'skill-creator',ensureSkillCreator:mockEnsureSkillCreator}))
vi.mock('./skill/ensureExpertManager',()=>({EXPERT_CREATE_PROMPT:'帮我创建一个 XXX 专家，擅长 XXXXX。我的经验是：[请补充你的行业背景、相关经验]',EXPERT_MANAGER_NAME:'expert-manager',EXPERT_MANAGER_TEMPLATE_ID:'expert-manager',ensureExpertManager:mockEnsureExpertManager}))
vi.mock('./plugin/ensurePluginCreator',()=>({PLUGIN_CREATE_PROMPT:'帮我创建一个能力包。说明要组合哪些技能模板、MCP 预置和工具门闸。调用 plugin.create 时在 manifest 里写 skills、mcpPresetIds、toolGates。创建成功后告诉我去能力包页查看。不会执行外部脚本。',PLUGIN_CREATOR_NAME:'plugin-creator',PLUGIN_CREATOR_TEMPLATE_ID:'plugin-creator',ensurePluginCreator:mockEnsurePluginCreator}))
vi.mock('./bridge/client',async importOriginal=>{const actual=await importOriginal<typeof import('./bridge/client')>();return{...actual,templateBridge:{list:vi.fn().mockResolvedValue({items:[]}),create:vi.fn(),enable:vi.fn(),void:vi.fn(),restore:vi.fn(),delete:vi.fn()},deliverableBridge:{list:vi.fn().mockResolvedValue({items:[]}),upsert:vi.fn(),confirmGate:vi.fn()},stageBridge:{...actual.stageBridge,list:vi.fn().mockResolvedValue({items:[]}),create:vi.fn(),update:vi.fn()},automationBridge:{listJobs:vi.fn().mockResolvedValue({jobs:[]}),setJob:vi.fn(),deleteJob:vi.fn(),triggerJob:vi.fn(),listRuns:vi.fn().mockResolvedValue({runs:[]}),status:vi.fn().mockResolvedValue({running:true,lastHeartbeat:'2026-01-01T00:00:00Z',nextFire:{},runningJobs:[]})},meetingsBridge:{list:vi.fn().mockResolvedValue({items:[]}),start:vi.fn(),append:vi.fn(),loopbackPoll:vi.fn(),stop:vi.fn(),get:vi.fn(),heartbeat:vi.fn(),summarize:vi.fn(),exportMeeting:vi.fn(),update:vi.fn(),delete:vi.fn()},getIdentityBridge:getIdentityBridgeMock,getPeopleBridge:getPeopleBridgeMock,getMeetingsBridge:getMeetingsBridgeMock}})

import type{ChatBridge,ExpertBridge,MessageBridge,MroBridge,ProjectBridge,ProviderBridge,SessionBridge}from'./bridge/client'
import type{ProjectDTO}from'./generated/bridge'
import{App,PERSONAL_CHAT_PROJECT}from'./App'
import{SKILL_CREATE_PROMPT}from'./skill/ensureSkillCreator'
import{EXPERT_CREATE_PROMPT}from'./skill/ensureExpertManager'
import{PLUGIN_CREATE_PROMPT}from'./plugin/ensurePluginCreator'
import{resetLiveChatForTests}from'./session/liveChat'
afterEach(()=>{cleanup();resetLiveChatForTests();mockPeopleThreadList.mockResolvedValue({items:[]});localStorage.removeItem('lunitide:language');localStorage.removeItem('lunitide:language-default-en');localStorage.removeItem('lunitide:sidebar-chats-open');localStorage.removeItem('lunitide:sidebar-projects-open')})
const now='2026-01-01T00:00:00Z'
const personal:ProjectDTO={id:'01ARZ3NDEKTSV4RRFFQ69G5FAV',name:PERSONAL_CHAT_PROJECT,projectCode:'ITM00000',type:'implementation',status:'active',createdAt:now,updatedAt:now,version:1}
const project:ProjectDTO={id:'01ARZ3NDEKTSV4RRFFQ69G5FAA',name:'Moon',projectCode:'ITM00001',type:'implementation',status:'active',createdAt:now,updatedAt:now,version:1}
const messages:MessageBridge={list:vi.fn().mockResolvedValue({items:[],hasMore:false,nextCursor:null,snapshotSequence:0}),append:vi.fn()}
const chat:ChatBridge={start:vi.fn(),approve:vi.fn(),dispose:vi.fn()}
const providers:ProviderBridge={list:vi.fn().mockResolvedValue({items:[]}),get:vi.fn(),create:vi.fn(),update:vi.fn(),delete:vi.fn(),revealCredential:vi.fn(),submitCredential:vi.fn(),syncModels:vi.fn(),test:vi.fn()}as ProviderBridge
const projectBridge=(items:ProjectDTO[]=[project]):ProjectBridge=>({list:vi.fn().mockResolvedValue({items}),create:vi.fn(),update:vi.fn(),publish:vi.fn(),close:vi.fn(),reopen:vi.fn(),advanceStatus:vi.fn(),delete:vi.fn()})
const sessionBridge=(items:any[]=[]):SessionBridge=>({list:vi.fn().mockResolvedValue({items}),create:vi.fn(),update:vi.fn(),delete:vi.fn()})

it('opens on ordinary chat and keeps providers inside settings',async()=>{const user=userEvent.setup();render(<App projects={projectBridge([])} sessions={sessionBridge()} providers={providers} messages={messages} chat={chat}/>);expect(await screen.findByRole('heading',{name:'What would you like to do?'})).toBeInTheDocument();expect(screen.getByRole('button',{name:/New chat/})).toBeInTheDocument();expect(screen.queryByRole('button',{name:'Models & providers'})).not.toBeInTheDocument();await user.click(screen.getByRole('button',{name:'Settings'}));expect(await screen.findByRole('button',{name:'← Home'})).toBeInTheDocument();expect(screen.queryByRole('button',{name:'MCP 服务器'})).not.toBeInTheDocument();expect(screen.queryByRole('button',{name:'数据与记忆'})).not.toBeInTheDocument();expect(screen.getByRole('button',{name:'Personal intelligence'})).toBeInTheDocument();expect(screen.getByRole('navigation',{name:'Settings'})).toHaveTextContent('Meeting notes');expect(screen.queryByRole('button',{name:'Capability packs'})).toBeInTheDocument();await user.click(screen.getByRole('button',{name:'Models & providers'}));expect(await screen.findByText('还没有供应商')).toBeInTheDocument();expect(screen.getByRole('tab',{name:'LLM'})).toBeInTheDocument();expect(screen.getByRole('tab',{name:'视觉模型'})).toBeInTheDocument();expect(screen.getByRole('tab',{name:'生图模型'})).toBeInTheDocument();expect(screen.getByRole('tab',{name:'生视频模型'})).toBeInTheDocument();expect(screen.getByRole('button',{name:'← Home'})).toBeInTheDocument();expect(screen.queryByRole('button',{name:'打开供应商管理'})).not.toBeInTheDocument();expect(screen.queryByRole('button',{name:'← 返回设置'})).not.toBeInTheDocument()})

it('opens project management before entering a project workbench and returns to it',async()=>{const projects=projectBridge([personal,project]),sessions=sessionBridge(),user=userEvent.setup();render(<App projects={projects} sessions={sessions} messages={messages} chat={chat} providers={providers}/>);const entries=await screen.findAllByRole('button',{name:'Project management'});await user.click(entries[0]);expect(await screen.findByRole('heading',{name:'项目管理'})).toBeInTheDocument();expect(screen.queryByText(PERSONAL_CHAT_PROJECT)).not.toBeInTheDocument();const enterButtons=screen.getAllByRole('button',{name:'进入工作台'});await user.click(enterButtons[0]);expect(await screen.findByLabelText('项目阶段导航')).toBeInTheDocument();expect(document.querySelector('.workbench-route')).not.toBeNull();expect(document.querySelector('.workbench-route')?.classList.contains('app-shell')).toBe(false);expect(sessions.list).toHaveBeenCalledWith({projectId:project.id});await user.click(screen.getByRole('button',{name:'Back to project management'}));expect(await screen.findByRole('heading',{name:'项目管理'})).toBeInTheDocument()})

it('opens Skill Center from the sidebar under project management with chat-based creation',async()=>{const user=userEvent.setup();render(<App projects={projectBridge([])} sessions={sessionBridge()} messages={messages} chat={chat} providers={providers}/>);await user.click(await screen.findByRole('button',{name:'Skill Center'}));expect((await screen.findAllByRole('heading',{name:'技能中心'})).length).toBeGreaterThan(0);await user.click(screen.getByRole('button',{name:'添加技能'}));expect(await screen.findByRole('dialog',{name:'添加技能'})).toBeInTheDocument();expect(screen.getByRole('button',{name:/上传技能包/})).toBeInTheDocument();expect(screen.getByRole('button',{name:/通过对话创建/})).toBeInTheDocument()})

it('keeps expert center, MCP, capability packs, and asset management as sidebar entries with real panels',async()=>{const user=userEvent.setup();render(<App projects={projectBridge([])} sessions={sessionBridge()} messages={messages} chat={chat} providers={providers}/>);expect(screen.queryByRole('button',{name:'MRO workbench'})).not.toBeInTheDocument();await user.click(await screen.findByRole('button',{name:'Asset Management'}));expect(await screen.findByRole('heading',{name:'资产管理'})).toBeInTheDocument();expect(screen.getByRole('button',{name:/上传资产/})).toBeInTheDocument();expect(screen.getByLabelText('搜索模版')).toBeInTheDocument();expect(screen.queryByRole('button',{name:'资产库模版管理'})).not.toBeInTheDocument();expect(screen.queryByText('规划中')).not.toBeInTheDocument();await user.click(screen.getByRole('button',{name:'Expert Center'}));expect(await screen.findByText('专家中心',{selector:'.view-title'})).toBeInTheDocument();expect(screen.getByLabelText('搜索专家')).toBeInTheDocument();expect(screen.getByRole('button',{name:'MCP'})).toBeInTheDocument();await user.click(screen.getByRole('button',{name:'MCP'}));expect(await screen.findByRole('heading',{name:'MCP'})).toBeInTheDocument();expect(screen.getByRole('button',{name:'＋ 创建 MCP'})).toBeInTheDocument();expect(screen.queryByRole('tab',{name:'MCP'})).not.toBeInTheDocument();await user.click(screen.getByRole('button',{name:'Capability packs'}));expect(await screen.findByRole('heading',{name:'能力包'})).toBeInTheDocument();expect(screen.getByRole('button',{name:'＋ 创建能力包'})).toBeInTheDocument();expect(screen.queryByText('规划中')).not.toBeInTheDocument()})

it('starts skill creation in ordinary chat with the full prompt and files workspace',async()=>{const session={id:'01ARZ3NDEKTSV4RRFFQ69G5FAW',projectId:personal.id,title:'创建技能',status:'active' as const,createdAt:now,updatedAt:now,version:1},projects=projectBridge([personal]),sessions={...sessionBridge(),create:vi.fn().mockResolvedValue(session)},user=userEvent.setup();render(<App projects={projects} sessions={sessions} messages={messages} chat={chat} providers={providers}/>);await user.click(await screen.findByRole('button',{name:'Skill Center'}));await user.click(screen.getByRole('button',{name:'添加技能'}));await user.click(await screen.findByRole('button',{name:/通过对话创建/}));expect(await screen.findByLabelText('创建技能 messages')).toHaveClass('personal-message-panel');expect(screen.getByRole('textbox',{name:'Ask Lunitide, or describe what you want to do…'})).toHaveValue(SKILL_CREATE_PROMPT);expect(screen.getByRole('list',{name:'已引用技能'})).toHaveTextContent('skill-creator');expect(screen.getByRole('tab',{name:'文件'})).toHaveAttribute('aria-selected','true');expect(await screen.findByRole('region',{name:'技能包目录'})).toBeInTheDocument();expect(screen.queryByText('知域宫殿')).not.toBeInTheDocument();expect(sessions.create).toHaveBeenCalledWith({projectId:personal.id,title:'创建技能'},expect.objectContaining({attempt:expect.any(Object)}));expect(screen.queryByRole('button',{name:'创建技能'})).not.toBeInTheDocument()})

it('deletes an empty skill-creation draft when leaving without sending a message',async()=>{const session={id:'01ARZ3NDEKTSV4RRFFQ69G5FAW',projectId:personal.id,title:'创建技能',status:'active' as const,createdAt:now,updatedAt:now,version:1},remove=vi.fn().mockResolvedValue({deleted:true,id:session.id}),sessions={...sessionBridge(),create:vi.fn().mockResolvedValue(session),delete:remove},user=userEvent.setup();render(<App projects={projectBridge([personal])} sessions={sessions} messages={messages} chat={chat} providers={providers}/>);await user.click(await screen.findByRole('button',{name:'Skill Center'}));await user.click(screen.getByRole('button',{name:'添加技能'}));await user.click(await screen.findByRole('button',{name:/通过对话创建/}));await user.click(await screen.findByRole('button',{name:'← Home'}));expect(await screen.findByRole('heading',{name:'What would you like to do?'})).toBeInTheDocument();await vi.waitFor(()=>expect(remove).toHaveBeenCalledWith({id:session.id},expect.objectContaining({attempt:expect.any(Object)})));expect(screen.queryByRole('button',{name:'创建技能'})).not.toBeInTheDocument();expect(screen.getByText('No chats yet')).toBeInTheDocument()})

it('starts expert creation in ordinary chat with expert-manager and template prompt',async()=>{const session={id:'01ARZ3NDEKTSV4RRFFQ69G5FAW',projectId:personal.id,title:'创建专家',status:'active' as const,createdAt:now,updatedAt:now,version:1},projects=projectBridge([personal]),sessions={...sessionBridge(),create:vi.fn().mockResolvedValue(session)},user=userEvent.setup();render(<App projects={projects} sessions={sessions} messages={messages} chat={chat} providers={providers}/>);await user.click(await screen.findByRole('button',{name:'Expert Center'}));await user.click(await screen.findByRole('button',{name:'添加专家'}));await user.click(await screen.findByRole('button',{name:/通过对话创建/}));expect(await screen.findByLabelText('创建专家 messages')).toHaveClass('personal-message-panel');expect(screen.getByRole('textbox',{name:'Ask Lunitide, or describe what you want to do…'})).toHaveValue(EXPERT_CREATE_PROMPT);expect(screen.getByRole('list',{name:'已引用技能'})).toHaveTextContent('expert-manager');expect(screen.getByRole('tab',{name:'文件'})).toHaveAttribute('aria-selected','true');expect(sessions.create).toHaveBeenCalledWith({projectId:personal.id,title:'创建专家'},expect.objectContaining({attempt:expect.any(Object)}))})

it('starts plugin creation in ordinary chat with plugin-creator and template prompt',async()=>{const session={id:'01ARZ3NDEKTSV4RRFFQ69G5FAW',projectId:personal.id,title:'创建能力包',status:'active' as const,createdAt:now,updatedAt:now,version:1},projects=projectBridge([personal]),sessions={...sessionBridge(),create:vi.fn().mockResolvedValue(session)},user=userEvent.setup();render(<App projects={projects} sessions={sessions} messages={messages} chat={chat} providers={providers}/>);await user.click(await screen.findByRole('button',{name:'Capability packs'}));await user.click(await screen.findByRole('button',{name:'＋ 创建能力包'}));expect(await screen.findByLabelText('创建能力包 messages')).toHaveClass('personal-message-panel');expect(screen.getByRole('textbox',{name:'Ask Lunitide, or describe what you want to do…'})).toHaveValue(PLUGIN_CREATE_PROMPT);expect(screen.getByRole('list',{name:'已引用技能'})).toHaveTextContent('plugin-creator');expect(screen.getByRole('tab',{name:'文件'})).toHaveAttribute('aria-selected','true');expect(sessions.create).toHaveBeenCalledWith({projectId:personal.id,title:'创建能力包'},expect.objectContaining({attempt:expect.any(Object)}))})

it('creates an isolated ordinary-chat session and automatically starts the selected model',async()=>{const session={id:'01ARZ3NDEKTSV4RRFFQ69G5FAW',projectId:personal.id,title:'Hello',status:'active' as const,createdAt:now,updatedAt:now,version:1},provider={id:'01ARZ3NDEKTSV4RRFFQ69G5FAX',name:'Ready',protocol:'openai_compatible' as const,baseUrl:'https://example.test',models:[{modelId:'m-one',displayName:'Model One',isDefault:true}],status:'enabled' as const,credentialState:'configured' as const,createdAt:now,updatedAt:now,version:1},projects=projectBridge([personal]),sessions={...sessionBridge(),create:vi.fn().mockResolvedValue(session)},append=vi.fn().mockResolvedValue({}),start=vi.fn().mockResolvedValue({streamId:'01ARZ3NDEKTSV4RRFFQ69G5FAY',cancel:vi.fn(),dispose:vi.fn()}),user=userEvent.setup();render(<App projects={projects} sessions={sessions} providers={{...providers,list:vi.fn().mockResolvedValue({items:[provider]})}} messages={{...messages,append}} chat={{start,dispose:vi.fn()}}/>);await user.type(await screen.findByLabelText('Message'),'Hello');await user.click(screen.getByRole('button',{name:'Start chat'}));expect(await screen.findByRole('button',{name:'← Home'})).toBeInTheDocument();expect(screen.queryByRole('heading',{name:/· 会话/})).not.toBeInTheDocument();await vi.waitFor(()=>expect(append).toHaveBeenCalledOnce());expect(sessions.create).toHaveBeenCalledWith({projectId:personal.id,title:'Hello'},expect.objectContaining({attempt:expect.any(Object)}));expect(start).toHaveBeenCalledWith(expect.objectContaining({providerId:provider.id,modelId:'m-one',sessionId:session.id,projectId:personal.id,executionMode:'full-access',companion:false}),expect.any(Function))})

it('sends the launch message with Enter, keeps the sidebar, and uses Shift+Enter for a newline',async()=>{const session={id:'01ARZ3NDEKTSV4RRFFQ69G5FAW',projectId:personal.id,title:'Hello',status:'active' as const,createdAt:now,updatedAt:now,version:1},provider={id:'01ARZ3NDEKTSV4RRFFQ69G5FAX',name:'Ready',protocol:'openai_compatible' as const,baseUrl:'https://example.test',models:[{modelId:'m-one',displayName:'Model One',isDefault:true}],status:'enabled' as const,credentialState:'configured' as const,createdAt:now,updatedAt:now,version:1},sessions={...sessionBridge(),create:vi.fn().mockResolvedValue(session)},user=userEvent.setup();render(<App projects={projectBridge([personal])} sessions={sessions} providers={{...providers,list:vi.fn().mockResolvedValue({items:[provider]})}} messages={messages} chat={chat}/>);const input=await screen.findByLabelText('Message');await user.type(input,'line one{Shift>}{Enter}{/Shift}line two');expect(input).toHaveValue('line one\nline two');await user.keyboard('{Enter}');expect(await screen.findByRole('button',{name:/New chat/})).toBeInTheDocument();expect(await screen.findByLabelText(`${session.title} messages`)).toHaveClass('personal-message-panel');expect(sessions.create).toHaveBeenCalledOnce()})

it('rejects an oversized launch message before creating a session',async()=>{const provider={id:'01ARZ3NDEKTSV4RRFFQ69G5FAX',name:'Ready',protocol:'openai_compatible' as const,baseUrl:'https://example.test',models:[{modelId:'m-one',displayName:'Model One',isDefault:true}],status:'enabled' as const,credentialState:'configured' as const,createdAt:now,updatedAt:now,version:1},sessions=sessionBridge(),user=userEvent.setup();render(<App projects={projectBridge([personal])} sessions={sessions} providers={{...providers,list:vi.fn().mockResolvedValue({items:[provider]})}} messages={messages} chat={chat}/>);const input=await screen.findByLabelText('Message');fireEvent.change(input,{target:{value:'x'.repeat(2049)}});await user.click(screen.getByRole('button',{name:'Start chat'}));expect(await screen.findByText(/1–2048/)).toBeInTheDocument();expect(sessions.create).not.toHaveBeenCalled()})

it('Ctrl+N resets the ordinary-chat draft',async()=>{const user=userEvent.setup();render(<App projects={projectBridge([])} sessions={sessionBridge()} providers={providers} messages={messages} chat={chat}/>);const input=await screen.findByLabelText('Message');await user.type(input,'discard me');await user.keyboard('{Control>}n{/Control}');expect(await screen.findByLabelText('Message')).toHaveValue('')})

it('shows only ordinary-chat history in the conversation group',async()=>{const personalSession={id:'01ARZ3NDEKTSV4RRFFQ69G5FAZ',projectId:personal.id,title:'Normal chat',status:'active' as const,createdAt:'2027-01-01T00:00:00Z',updatedAt:'2027-01-01T00:00:00Z',version:1},empty={...personalSession,id:'01ARZ3NDEKTSV4RRFFQ69G5FAY',title:'新对话'},list=vi.fn().mockResolvedValue({items:[personalSession,empty]}),sessions:SessionBridge={list,create:vi.fn(),update:vi.fn(),delete:vi.fn()};render(<App projects={projectBridge([personal,project])} sessions={sessions} providers={providers} messages={messages} chat={chat}/>);expect(await screen.findByText('Normal chat')).toBeInTheDocument();expect(document.getElementById('conversation-list')?.textContent).not.toMatch(/新对话/);expect(screen.queryByText('Moon')).not.toBeInTheDocument();expect(list).toHaveBeenCalledTimes(1);expect(list).toHaveBeenCalledWith({projectId:personal.id})})

it('keeps colleague chats out of the conversation group',async()=>{const ordinary={id:'01ARZ3NDEKTSV4RRFFQ69G5FAZ',projectId:personal.id,title:'你好月汐',status:'active' as const,createdAt:'2027-01-01T00:00:00Z',updatedAt:'2027-01-01T00:00:00Z',version:1},colleague={...ordinary,id:'01ARZ3NDEKTSV4RRFFQ69G5FAY',title:'同事 · PPT专家'},excel={...ordinary,id:'01ARZ3NDEKTSV4RRFFQ69G5FAX',title:'同事·Excel表格制作专家'},list=vi.fn().mockResolvedValue({items:[ordinary,colleague,excel]}),sessions:SessionBridge={list,create:vi.fn(),update:vi.fn(),delete:vi.fn()};render(<App projects={projectBridge([personal,project])} sessions={sessions} providers={providers} messages={messages} chat={chat}/>);expect(await screen.findByText('你好月汐')).toBeInTheDocument();const listText=document.getElementById('conversation-list')?.textContent??'';expect(listText).not.toMatch(/同事/);expect(listText).not.toMatch(/PPT专家/);expect(listText).not.toMatch(/Excel/);expect(screen.getByRole('button',{name:/^Colleague chat$/})).toBeInTheDocument()})

it('restores ordinary-chat history by its stable id when the stored project name is damaged',async()=>{const damaged={...personal,name:'\u2063��ϫ����ͨ�Ի�'},historical={id:'01ARZ3NDEKTSV4RRFFQ69G5FAZ',projectId:damaged.id,title:'Recovered history',status:'active' as const,createdAt:now,updatedAt:now,version:1},list=vi.fn().mockResolvedValue({items:[historical]});localStorage.setItem('lunitide:personal-chat-project-id',damaged.id);render(<App projects={projectBridge([damaged,project])} sessions={{...sessionBridge(),list}} providers={providers} messages={messages} chat={chat}/>);expect(await screen.findByText('Recovered history')).toBeInTheDocument();expect(list).toHaveBeenCalledWith({projectId:damaged.id})})

it('recognizes a legacy hidden ordinary-chat project even when its saved id is unavailable',async()=>{const damaged={...personal,name:'\u2063legacy-damaged-name'},historical={id:'01ARZ3NDEKTSV4RRFFQ69G5FAZ',projectId:damaged.id,title:'Legacy history',status:'active' as const,createdAt:now,updatedAt:now,version:1},list=vi.fn().mockResolvedValue({items:[historical]});localStorage.removeItem('lunitide:personal-chat-project-id');render(<App projects={projectBridge([damaged,project])} sessions={{...sessionBridge(),list}} providers={providers} messages={messages} chat={chat}/>);expect(await screen.findByText('Legacy history')).toBeInTheDocument();expect(list).toHaveBeenCalledWith({projectId:damaged.id})})

it('refreshes ordinary-chat history after returning home',async()=>{const created={id:'01ARZ3NDEKTSV4RRFFQ69G5FAZ',projectId:personal.id,title:'New history item',status:'active' as const,createdAt:'2027-01-01T00:00:00Z',updatedAt:'2027-01-01T00:00:00Z',version:1},list=vi.fn().mockResolvedValueOnce({items:[]}).mockResolvedValue({items:[created]}),sessions:SessionBridge={list,create:vi.fn().mockResolvedValue(created),update:vi.fn(),delete:vi.fn()},provider={id:'01ARZ3NDEKTSV4RRFFQ69G5FAX',name:'Ready',protocol:'openai_compatible' as const,baseUrl:'https://example.test',models:[{modelId:'m-one',displayName:'Model One',isDefault:true}],status:'enabled' as const,credentialState:'configured' as const,createdAt:now,updatedAt:now,version:1},user=userEvent.setup();render(<App projects={projectBridge([personal])} sessions={sessions} providers={{...providers,list:vi.fn().mockResolvedValue({items:[provider]})}} messages={messages} chat={chat}/>);await user.type(await screen.findByLabelText('Message'),'New history item');await user.click(screen.getByRole('button',{name:'Start chat'}));await user.click(await screen.findByRole('button',{name:'← Home'}));expect(await screen.findByText('New history item')).toBeInTheDocument();expect(list.mock.calls.length).toBeGreaterThanOrEqual(2)})

it('never disposes an injected chat bridge on unmount',()=>{const injected={start:vi.fn(),approve:vi.fn(),dispose:vi.fn()}as ChatBridge,view=render(<App projects={projectBridge([])} sessions={sessionBridge()} providers={providers} messages={messages} chat={injected}/>);view.unmount();expect(injected.dispose).not.toHaveBeenCalled()})

it('offers file, folder, context, skill, and expert entries from the launch composer',async()=>{const user=userEvent.setup();render(<App projects={projectBridge([])} sessions={sessionBridge()} providers={providers} messages={messages} chat={chat}/>);await user.click(await screen.findByRole('button',{name:'Add context'}));expect(screen.getByRole('button',{name:/Files/})).toBeInTheDocument();expect(screen.getByRole('button',{name:/Upload folder/})).toBeInTheDocument();expect(screen.getByRole('button',{name:/@ Context/})).toBeInTheDocument();expect(screen.getByRole('button',{name:/Choose skill/})).toBeInTheDocument();expect(screen.getByRole('button',{name:/Choose expert/})).toBeInTheDocument();const folder=document.querySelector('input[webkitdirectory]');expect(folder).not.toBeNull()})

it('keeps empty composer chats out of the sidebar',async()=>{const session={id:'01ARZ3NDEKTSV4RRFFQ69G5FAW',projectId:personal.id,title:'新对话',status:'active' as const,createdAt:now,updatedAt:now,version:1},create=vi.fn().mockResolvedValue(session),user=userEvent.setup();render(<App projects={projectBridge([personal])} sessions={{...sessionBridge(),create}} providers={providers} messages={messages} chat={chat}/>);await user.click(await screen.findByRole('button',{name:'Add context'}));await user.click(screen.getByRole('button',{name:/@ Context/}));expect(await screen.findByLabelText('新对话 messages')).toBeInTheDocument();expect(document.getElementById('conversation-list')?.textContent).not.toMatch(/新对话/);expect(screen.getByText('No chats yet')).toBeInTheDocument()})

it('preserves the launch draft while model settings opens and closes',async()=>{const user=userEvent.setup();render(<App projects={projectBridge([])} sessions={sessionBridge()} providers={providers} messages={messages} chat={chat}/>);const input=await screen.findByLabelText('Message');await user.type(input,'保留草稿');await user.click(screen.getByRole('button',{name:/Select model/}));await user.click(screen.getByRole('button',{name:'Manage providers and models'}));expect(screen.getByRole('dialog',{name:'Models & providers'})).toBeInTheDocument();await user.click(screen.getByRole('button',{name:'← Back to chat'}));expect(screen.getByLabelText('Message')).toHaveValue('保留草稿')})

it('synchronizes restored and toggled themes with the native host',async()=>{localStorage.setItem('lunitide:theme','light');const set=vi.fn().mockResolvedValue({applied:true}),user=userEvent.setup();render(<App projects={projectBridge([])} sessions={sessionBridge()} providers={providers} messages={messages} chat={chat} nativeTheme={{set}}/>);await vi.waitFor(()=>expect(set).toHaveBeenCalledWith({theme:'light'}));await user.click(screen.getByRole('button',{name:'Switch to dark mode'}));await vi.waitFor(()=>expect(set).toHaveBeenLastCalledWith({theme:'dark'}))})


it('offers persistent pin, rename, and confirmed delete actions for each chat',async()=>{const original={id:'01ARZ3NDEKTSV4RRFFQ69G5FAZ',projectId:personal.id,title:'Action chat',pinned:false,status:'active' as const,createdAt:now,updatedAt:now,version:1},update=vi.fn().mockImplementation(async p=>({...original,title:p.title,pinned:p.pinned,updatedAt:'2026-01-02T00:00:00Z',version:p.version+1})),remove=vi.fn().mockResolvedValue({deleted:true,id:original.id}),sessions:SessionBridge={list:vi.fn().mockResolvedValue({items:[original]}),create:vi.fn(),update,delete:remove},user=userEvent.setup();render(<App projects={projectBridge([personal])} sessions={sessions} providers={providers} messages={messages} chat={chat}/>);await user.click(await screen.findByRole('button',{name:'More actions Action chat'}));expect(screen.getByRole('menuitem',{name:'Pin'})).toBeInTheDocument();expect(screen.getByRole('menuitem',{name:'Rename'})).toBeInTheDocument();expect(screen.getByRole('menuitem',{name:'Delete'})).toBeInTheDocument();await user.click(screen.getByRole('menuitem',{name:'Pin'}));await vi.waitFor(()=>expect(update).toHaveBeenCalledWith({id:original.id,title:'Action chat',pinned:true,version:1},expect.objectContaining({attempt:expect.any(Object)})));await user.click(screen.getByRole('button',{name:'More actions Action chat'}));await user.click(screen.getByRole('menuitem',{name:'Rename'}));const input=screen.getByLabelText('Chat name');await user.clear(input);await user.type(input,'Renamed chat');await user.click(screen.getByRole('button',{name:'Save'}));await vi.waitFor(()=>expect(update).toHaveBeenLastCalledWith(expect.objectContaining({id:original.id,title:'Renamed chat',pinned:true,version:2}),expect.any(Object)));await user.click(screen.getByRole('button',{name:'More actions Renamed chat'}));await user.click(screen.getByRole('menuitem',{name:'Delete'}));expect(screen.getByRole('dialog',{name:'Delete chat「Renamed chat」？'})).toBeInTheDocument();expect(remove).not.toHaveBeenCalled();await user.click(screen.getByRole('button',{name:'Delete'}));await vi.waitFor(()=>expect(remove).toHaveBeenCalledOnce());expect(screen.queryByText('Renamed chat')).not.toBeInTheDocument()})

it('returns home and removes the sidebar item after deleting the active last chat',async()=>{const original={id:'01ARZ3NDEKTSV4RRFFQ69G5FAZ',projectId:personal.id,title:'Last chat',status:'active' as const,createdAt:now,updatedAt:now,version:1};let items=[original];const sessions:SessionBridge={list:vi.fn().mockImplementation(async()=>({items})),create:vi.fn(),update:vi.fn(),delete:vi.fn().mockImplementation(async()=>{items=[];return{deleted:true,id:original.id}})},user=userEvent.setup();render(<App projects={projectBridge([personal])} sessions={sessions} providers={providers} messages={messages} chat={chat}/>);await user.click(await screen.findByRole('button',{name:'Last chat'}));expect(await screen.findByLabelText('Last chat messages')).toBeInTheDocument();await user.click(screen.getByRole('button',{name:'More actions Last chat'}));await user.click(screen.getByRole('menuitem',{name:'Delete'}));await user.click(screen.getByRole('button',{name:'Delete'}));expect(await screen.findByRole('heading',{name:'What would you like to do?'})).toBeInTheDocument();await vi.waitFor(()=>expect(screen.queryByRole('button',{name:'Last chat'})).not.toBeInTheDocument());expect(screen.getByText('No chats yet')).toBeInTheDocument()})

it('deletes the session, returns home, and clears the sidebar after removing the final round',async()=>{const original={id:'01ARZ3NDEKTSV4RRFFQ69G5FAZ',projectId:personal.id,title:'Only round',status:'active' as const,createdAt:now,updatedAt:now,version:1},question={id:'01ARZ3NDEKTSV4RRFFQ69G5FAY',sessionId:original.id,role:'user' as const,status:'completed' as const,sequence:1,text:'最后一问',createdAt:now},answer={...question,id:'01ARZ3NDEKTSV4RRFFQ69G5FAX',role:'assistant' as const,sequence:2,text:'最后一答'};let items=[original];const sessions:SessionBridge={list:vi.fn().mockImplementation(async()=>({items})),create:vi.fn(),update:vi.fn(),delete:vi.fn().mockImplementation(async()=>{items=[];return{deleted:true,id:original.id}})},rewind=vi.fn().mockResolvedValue({sessionId:original.id,messageId:question.id,deletedCount:2,lastSequence:0,historyRevision:2}),user=userEvent.setup();render(<App projects={projectBridge([personal])} sessions={sessions} providers={providers} messages={{...messages,list:vi.fn().mockResolvedValue({items:[question,answer],hasMore:false,nextCursor:null,snapshotSequence:2}),rewind}} chat={chat}/>);await user.click(await screen.findByRole('button',{name:'Only round'}));await screen.findByText('最后一答');await user.click(screen.getByRole('button',{name:'删除'}));await user.click(screen.getByRole('button',{name:'确认删除'}));expect(await screen.findByRole('heading',{name:'What would you like to do?'})).toBeInTheDocument();expect(screen.queryByRole('button',{name:'Only round'})).not.toBeInTheDocument();expect(screen.getByText('No chats yet')).toBeInTheDocument()})

it('searches chat titles and message text with Ctrl+K and opens the selected history',async()=>{const weather={id:'01ARZ3NDEKTSV4RRFFQ69G5FAZ',projectId:personal.id,title:'上海天气',status:'active' as const,createdAt:now,updatedAt:now,version:1},coding={...weather,id:'01ARZ3NDEKTSV4RRFFQ69G5FAY',title:'代码讨论'},search=vi.fn().mockResolvedValue({items:[{sessionId:coding.id,messageId:'01ARZ3NDEKTSV4RRFFQ69G5FAX',role:'user' as const,sequence:1,snippet:'这里谈到了月汐功能',sessionTitle:'代码讨论'}]}),user=userEvent.setup();render(<App projects={projectBridge([personal])} sessions={sessionBridge([weather,coding])} providers={providers} messages={{...messages,search}} chat={chat}/>);await screen.findByText('上海天气');await user.keyboard('{Control>}k{/Control}');const dialog=await screen.findByRole('dialog',{name:'Search chat history'}),input=screen.getByRole('textbox',{name:'Search chat titles and content'});await user.type(input,'月汐 搜索');const result=await vi.waitFor(()=>{expect(search).toHaveBeenCalled();const button=dialog.querySelector<HTMLButtonElement>('.conversation-search-results>button');expect(button).toHaveTextContent('代码讨论');expect(button).toHaveTextContent(/月汐|搜索/);return button!});expect(dialog).not.toHaveTextContent('上海天气');await user.click(result);expect(await screen.findByLabelText('代码讨论 messages')).toBeInTheDocument()})

it('places 会议记录 directly under 自动化 and opens an independent meeting workspace',async()=>{const user=userEvent.setup();render(<App projects={projectBridge([])} sessions={sessionBridge()} providers={providers} messages={messages} chat={chat}/>);const automation=await screen.findByRole('button',{name:/^Automation$/});const meetings=screen.getByRole('button',{name:/^Meeting notes$/});const search=screen.getByRole('button',{name:/Search/});expect(automation.compareDocumentPosition(meetings)&Node.DOCUMENT_POSITION_FOLLOWING).toBeTruthy();expect(meetings.compareDocumentPosition(search)&Node.DOCUMENT_POSITION_FOLLOWING).toBeTruthy();await user.click(meetings);expect(await screen.findByRole('heading',{name:'新的会议'})).toBeInTheDocument();expect(screen.getByRole('button',{name:'开始录制'})).toBeInTheDocument();expect(screen.getByRole('button',{name:'＋ 新纪要'})).toBeInTheDocument();expect(screen.getByRole('button',{name:'历史纪要'})).toBeInTheDocument();expect(screen.queryByRole('heading',{name:'What would you like to do?'})).not.toBeInTheDocument()})

it('opens meeting listen settings from the workbench and returns without sticking the next Settings visit',async()=>{const user=userEvent.setup();render(<App projects={projectBridge([])} sessions={sessionBridge()} providers={providers} messages={messages} chat={chat}/>);await user.click(await screen.findByRole('button',{name:/^Meeting notes$/}));await user.click(await screen.findByRole('button',{name:'听写与纪要设置'}));expect(await screen.findByRole('radiogroup',{name:'Live captions'})).toBeInTheDocument();expect(screen.getByRole('navigation',{name:'Settings'}).querySelector('[aria-current="page"]')).toHaveTextContent('Meeting notes');await user.click(screen.getByRole('button',{name:'← Back to meetings'}));expect(await screen.findByRole('heading',{name:'新的会议'})).toBeInTheDocument();await user.click(screen.getByRole('button',{name:/^Settings$/}));expect(await screen.findByText('启动时打开')).toBeInTheDocument();expect(screen.getByRole('navigation',{name:'Settings'}).querySelector('[aria-current="page"]')).toHaveTextContent('General');expect(screen.queryByRole('radiogroup',{name:'Live captions'})).not.toBeInTheDocument()})

it('places 同事聊天 above the conversation group and opens an independent WeChat workspace',async()=>{const user=userEvent.setup();render(<App projects={projectBridge([])} sessions={sessionBridge()} providers={providers} messages={messages} chat={chat}/>);const peopleBtn=await screen.findByRole('button',{name:/^Colleague chat$/});const chatList=document.getElementById('conversation-list');expect(chatList).not.toBeNull();expect(peopleBtn.compareDocumentPosition(chatList!)&Node.DOCUMENT_POSITION_FOLLOWING).toBeTruthy();expect(screen.queryByText('登录用户名')).not.toBeInTheDocument();expect(await screen.findByRole('button',{name:'Open my profile'})).toHaveTextContent('mu');await user.click(peopleBtn);expect(await screen.findByRole('navigation',{name:'同事工作区'})).toBeInTheDocument();expect(screen.getByRole('heading',{name:'聊天'})).toBeInTheDocument();expect(screen.queryByRole('heading',{name:'What would you like to do?'})).not.toBeInTheDocument();expect(document.getElementById('conversation-list')).not.toBeNull()})

it('shows people unread on the 同事聊天 item and opens 我 from the account chip',async()=>{mockPeopleThreadList.mockResolvedValue({items:[{threadId:'01ARZ3NDEKTSV4RRFFQ69G5FAX',kind:'direct',title:'',ownerSubjectId:'01ARZ3NDEKTSV4RRFFQ69G5FAV',members:[],unreadCount:4,createdAt:now,updatedAt:now}]});const user=userEvent.setup();render(<App projects={projectBridge([])} sessions={sessionBridge()} providers={providers} messages={messages} chat={chat}/>);expect(await screen.findByLabelText('4 unread')).toBeInTheDocument();await user.click(screen.getByRole('button',{name:'Open my profile'}));expect(await screen.findByText('Let others on this LAN see me')).toBeInTheDocument();expect(screen.getByRole('navigation',{name:'同事工作区'}).querySelector('[aria-current="true"]')).toHaveTextContent('我')})

it('shows 月汐 as the product name after switching the chrome to Chinese',async()=>{const user=userEvent.setup();render(<App projects={projectBridge([])} sessions={sessionBridge()} providers={providers} messages={messages} chat={chat}/>);expect(await screen.findByRole('button',{name:'Lunitide home'})).toBeInTheDocument();expect(screen.getByText('LUNITIDE')).toBeInTheDocument();await user.click(screen.getByRole('button',{name:'Switch to Chinese'}));expect(await screen.findByRole('button',{name:'月汐首页'})).toBeInTheDocument();expect(screen.getByText('月汐')).toBeInTheDocument();expect(screen.getByRole('button',{name:'切换到英文'})).toHaveTextContent('中/EN')})

it('draws no horizontal sidebar splitter when the chat list is empty',async()=>{render(<App projects={projectBridge([])} sessions={sessionBridge()} providers={providers} messages={messages} chat={chat}/>);await screen.findByRole('button',{name:/^Colleague chat$/});const rows=[...document.querySelectorAll('#launch-sidebar [role="separator"][aria-orientation="horizontal"]')];expect(rows).toHaveLength(0);expect(screen.queryByLabelText(/chats and projects|对话与项目/)).toBeNull();expect(screen.getByText('No chats yet')).toBeInTheDocument()})

it('draws one horizontal sidebar splitter between chats and projects when ordinary chats exist',async()=>{const personalSession={id:'01ARZ3NDEKTSV4RRFFQ69G5FAZ',projectId:personal.id,title:'Normal chat',status:'active' as const,createdAt:'2027-01-01T00:00:00Z',updatedAt:'2027-01-01T00:00:00Z',version:1};render(<App projects={projectBridge([personal])} sessions={sessionBridge([personalSession])} providers={providers} messages={messages} chat={chat}/>);expect(await screen.findByText('Normal chat')).toBeInTheDocument();const rows=[...document.querySelectorAll('#launch-sidebar [role="separator"][aria-orientation="horizontal"]')];expect(rows).toHaveLength(1);expect(screen.getByLabelText('Resize chats and projects')).toBeInTheDocument()})

it('shows a gated MRO workbench entry only after the aviation expert is enabled',async()=>{
  const user=userEvent.setup()
  const experts={list:vi.fn().mockResolvedValue({experts:[{expertId:'01ARZ3NDEKTSV4RRFFQ69G5FAX',catalogItemId:'mro-expert',name:'航空机务专家',division:'operations',source:'builtin',semver:'1.0.0',state:'enabled',versionCount:1,mountedPhaseCount:0}]})} as unknown as ExpertBridge
  const mro={aircraftList:vi.fn().mockResolvedValue({items:[]}),aircraftUpsert:vi.fn(),manualList:vi.fn().mockResolvedValue({items:[]}),manualRegister:vi.fn(),checklistBuild:vi.fn(),auditList:vi.fn().mockResolvedValue({items:[]})} as unknown as MroBridge
  render(<App projects={projectBridge([])} sessions={sessionBridge()} messages={messages} chat={chat} providers={providers} experts={experts} mro={mro}/>)
  expect(await screen.findByRole('button',{name:'MRO workbench'})).toBeInTheDocument()
  await user.click(screen.getByRole('button',{name:'MRO workbench'}))
  expect(await screen.findByRole('heading',{name:'MRO workbench'})).toBeInTheDocument()
  expect(screen.getByText('Start from a manual or a tail number')).toBeInTheDocument()
  expect(screen.getByText('The workbench only checks effectivity and cites. Release stays with licensed personnel.')).toBeInTheDocument()
  expect(screen.getByRole('button',{name:'Ask Lunitide'})).toHaveClass('primary')
})
