import { readFileSync } from 'node:fs'
import { resolve } from 'node:path'
import { describe, expect, it } from 'vitest'

const css = readFileSync(resolve(process.cwd(), 'src/styles.css'), 'utf8')
const inspectorCss = readFileSync(resolve(process.cwd(), 'src/workspace/artifactInspector.css'), 'utf8')
const app = readFileSync(resolve(process.cwd(), 'src/App.tsx'), 'utf8')

describe('project workbench native-frame stability', () => {
  it('does not wrap the workbench in the 3-column app-shell grid with Atmosphere as a sibling row', () => {
    expect(app).toMatch(/className="session-shell workbench-route"/)
    expect(app).not.toMatch(/className="app-shell session-shell"/)
  })

  it('locks ordinary chat and the workbench to the host client instead of stacking 100vh rows', () => {
    expect(css).toMatch(/\.workbench-route\.session-shell\{[^}]*display:block;[^}]*height:100%;[^}]*overflow:hidden/)
    expect(css).toMatch(/\.pm-workbench\.launch-shell\{height:100%;min-height:0;overflow:hidden/)
    expect(css).toMatch(/\.pm-workbench \.launch-content,\.pm-workbench \.pm-workbench-center\{height:100%;overflow:hidden/)
    expect(css).not.toMatch(/\.pm-workbench\.launch-shell\{height:100vh/)
    expect(css).not.toMatch(/\.launch-content\{[^}]*height:100vh/)
    expect(css).not.toMatch(/\.launch-shell\{[^}]*min-height:100vh/)
    expect(css).not.toMatch(/\.main\.project-workspace-shell\{[^}]*min-height:100vh/)
    expect(css).toMatch(/\.chat-shell\.launch-shell\{height:100%;min-height:0;overflow:hidden/)
    expect(css).toMatch(/\.chat-content\{[^}]*min-height:0/)
    expect(css).not.toMatch(/\.chat-content\{[^}]*min-height:100vh/)
    expect(css).not.toMatch(/min-height:calc\(100vh - 92px\)/)
    expect(css).toMatch(/html,#root\{[^}]*height:100%/)
    expect(css).toMatch(/html,#root\{[^}]*overflow:hidden/)
    expect(css).toMatch(/html,#root\{[^}]*overflow-anchor:none/)
    expect(css).toMatch(/body\{background:var\(--bg\);overflow:hidden;[^}]*height:100%/)
    expect(css).toMatch(/body\{[^}]*overflow-anchor:none/)
  })

  it('pins stream layout so thinking tokens cannot shake the native frame', () => {
    expect(css).toMatch(/\.conversation-scroll\{[^}]*overflow-anchor:none/)
    expect(css).toMatch(/\.workspace-layout\{[^}]*overflow-anchor:none/)
    expect(css).toMatch(/\.message-body\{[^}]*overflow-anchor:none/)
    expect(css).toMatch(/\.thinking-panel\{[^}]*overflow-anchor:none/)
    // Size containment collapses an auto-height expanded process to zero.
    expect(css).toMatch(/\.thinking-panel\{[^}]*contain:layout style/)
    expect(css).not.toMatch(/\.thinking-panel\{[^}]*(?:contain:strict|contain:[^;}]*size)/)
    expect(css).toMatch(/\.thinking-panel\{[^}]*max-height:28vh/)
    expect(css).toMatch(/\.thinking-panel\{[^}]*overflow-y:auto/)
    expect(css).toMatch(/\.thinking-live-text\{[^}]*max-height:18em/)
    expect(css).toMatch(/\.thinking-live-text\{[^}]*min-height:0/)
    expect(css).toMatch(/\.waiting-response\{[^}]*min-height:1\.7em/)
    expect(css).toMatch(/\.mermaid-host\{[^}]*max-height:min\(40vh,360px\)/)
    expect(css).toMatch(/\.mermaid-host\{[^}]*overflow:hidden/)
    expect(css).not.toMatch(/\.mermaid-host\{[^}]*overflow:auto/)
    expect(css).toMatch(/\.mermaid-lightbox\{[^}]*overflow:auto/)
    expect(css).toMatch(/\.mermaid-skin/)
    expect(css).toMatch(/\.moon-dialog\{[^}]*overflow-anchor:none/)
    expect(css).toMatch(/\.modal-backdrop\{[^}]*overflow-anchor:none/)
    expect(css).toMatch(/\.mermaid-preview\{[^}]*overflow-anchor:none/)
    expect(css).toMatch(/\.chat-follow-ups\{[^}]*overflow-anchor:none/)
    expect(css).toMatch(/\.workspace-layout\.workspace-is-open\{[^}]*grid-template-rows:minmax\(0,1fr\)/)
    expect(css).toMatch(/\.workspace-layout\.workspace-is-expanded\{[^}]*grid-template-columns:0 0 minmax\(0,1fr\)/)
    expect(css).toMatch(/\.workspace-layout\.workspace-is-expanded>\.message-panel\{[^}]*visibility:hidden/)
    expect(css).toMatch(/\.workspace-layout\.workspace-is-expanded>\.message-panel\{[^}]*overflow-anchor:none/)
    expect(css).toMatch(/\.workspace-layout\.workspace-is-expanded \.workspace-side-menu\{[^}]*display:none/)
    expect(css).toMatch(/\.workspace-layout\.workspace-is-expanded>\.workspace-column\{[^}]*width:100%/)
    expect(inspectorCss).toMatch(/\.artifact-inspector\{[^}]*overflow-anchor:none/)
    expect(inspectorCss).toMatch(/\.artifact-icon-btn\{[^}]*width:22px/)
    expect(css).toMatch(/\.workspace-layout>\.message-panel\{[^}]*min-height:0;[^}]*height:100%/)
    expect(css).toMatch(/\.project-chat-panel\.workspace-layout>\.message-panel\{min-height:0;height:100%/)
  })

  it('keeps expert-chip glow from invalidating the window chrome compositor', () => {
    expect(css).toMatch(/\.skill-chip\{[^}]*contain:paint/)
    expect(css).toMatch(/\.atmosphere\{[^}]*contain:paint/)
  })

  it('paints Work chat chrome black instead of navy overlays', () => {
    expect(css).toMatch(/\.chat-content>\.main\{[^}]*background:#000/)
    expect(css).toMatch(/\.personal-chat-page \.topbar\{[^}]*background:#000/)
    expect(css).toMatch(/\.workspace-side-menu\{[^}]*background:#000/)
    expect(css).toMatch(/\.files-panel\{[^}]*background:#000/)
    expect(css).not.toMatch(/\.chat-content>\.main\{[^}]*background:rgba\(4,9,17/)
    expect(css).not.toMatch(/\.personal-chat-page \.topbar\{[^}]*background:rgba\(7,12,20/)
  })

  it('paints Settings dark chrome black instead of navy overlays', () => {
    expect(css).toMatch(/\.settings-shell\{[^}]*background:#000/)
    expect(css).toMatch(/\.settings-nav\{[^}]*background:#000/)
    expect(css).toMatch(/\.settings-content\{[^}]*background:#000/)
    expect(css).toMatch(/\.settings-top\{[^}]*background:#000/)
    expect(css).toMatch(/\.setting-group\{[^}]*background:#000/)
    expect(css).toMatch(/\.setting-group-title\{[^}]*background:#000/)
    expect(css).toMatch(/\.about-info>div\{[^}]*background:#000/)
    expect(css).toMatch(/\.about-links\{[^}]*background:#000/)
    expect(css).toMatch(/\.capability-routing\{[^}]*background:#000/)
    expect(css).toMatch(/\.launch-content>\.settings-shell\{[^}]*background:#000/)
    expect(css).toMatch(/\.provider-table\{[^}]*background:#000/)
    expect(css).toMatch(/\.profile-section-title\{[^}]*background:#000/)
    expect(css).not.toMatch(/\.settings-nav\{[^}]*background:rgba\(12,18,29/)
    expect(css).not.toMatch(/\.settings-shell\{[^}]*background:#080d16/)
    expect(css).not.toMatch(/\.settings-top\{[^}]*background:rgba\(8,13,22/)
    expect(css).toMatch(/html\[data-theme="light"\] \.settings-nav \{ background: var\(--bg2\)/)
    expect(css).toMatch(/html\[data-theme="light"\] \.setting-group \{ background: #fff/)
  })

  it('paints sibling launch pages black instead of navy overlays', () => {
    expect(css).toMatch(/\.launch-content \.skill-center,.launch-content \.expert-center-page,.launch-content \.asset-center,.launch-content \.org-console\{[^}]*background:#000/)
    expect(css).toMatch(/\.skill-center\{[^}]*background:#000/)
    expect(css).toMatch(/\.expert-center-page\{[^}]*background:#000/)
    expect(css).toMatch(/\.org-console-page\{[^}]*background:#000/)
    expect(css).toMatch(/\.org-console\{[^}]*background:#000/)
    expect(css).toMatch(/\.asset-center\{[^}]*background:#000/)
    expect(css).toMatch(/\.project-workspace\{[^}]*background:#000/)
    expect(css).toMatch(/\.phase-nav\{[^}]*background:#000/)
    expect(css).not.toMatch(/\.launch-content \.skill-center,.launch-content \.expert-center-page,.launch-content \.asset-center,.launch-content \.org-console\{[^}]*background:#080d16/)
    expect(css).not.toMatch(/\.skill-center\{[^}]*background:#080d16/)
    expect(css).not.toMatch(/\.expert-center-page\{[^}]*background:#080d16/)
    expect(css).not.toMatch(/\.asset-center\{[^}]*background:#080d16/)
    expect(css).not.toMatch(/\.org-console-page\{[^}]*background:#080d16/)
    expect(css).not.toMatch(/\.project-workspace\{[^}]*background:#080d16/)
    expect(css).toMatch(/html\[data-theme="light"\] \.launch-content \.skill-center/)
    expect(css).toMatch(/html\[data-theme="light"\] \.skill-center,html\[data-theme="light"\] \.skill-table/)
  })

  it('paints remaining launch inner chrome black instead of navy glass', () => {
    expect(css).toMatch(/\.launch-content \.brand,.launch-content \.project-create,.launch-content \.project-list,.launch-content main,.launch-content aside\{background:#000/)
    expect(css).not.toMatch(/background:rgba\(9,16,28/)
    expect(css).toMatch(/\.project-hero\{[^}]*background:#000/)
    expect(css).toMatch(/\.project-list\{[^}]*background:#000/)
    expect(css).toMatch(/\.pm-body\{[^}]*background:#000/)
    expect(css).toMatch(/\.people-rail\{[^}]*background:#000/)
    expect(css).toMatch(/\.people-mid\{[^}]*background:#000/)
    expect(css).toMatch(/\.snapshot-dialog\{[^}]*background:#000/)
    expect(css).toMatch(/\.session-shell>\.main\{[^}]*background:#000/)
    expect(css).toMatch(/\.sidebar\{[^}]*background:#000/)
    expect(css).toMatch(/\.project-scoped-tabs\{[^}]*background:#000/)
    expect(css).toMatch(/\.memory-tabs\{[^}]*background:#000/)
    expect(css).toMatch(/\.asset-dialog\{[^}]*background:#000/)
    expect(css).toMatch(/\.activity\{[^}]*background:#000/)
    expect(css).toMatch(/\.inputbar\{[^}]*background:#000/)
    expect(css).toMatch(/html,#root\{[^}]*background:var\(--bg\)/)
  })

  it('uses white-neutral light page fills instead of icy blue', () => {
    expect(css).toMatch(/html\[data-theme="light"\] \{\s*--bg:#fff/)
    expect(css).not.toMatch(/--bg:#f8fcff/)
    expect(css).not.toMatch(/--bg:#eef8ff/)
    expect(css).not.toMatch(/background:#bfe8ff/)
    expect(css).not.toMatch(/html\[data-theme="light"\] \.launch-shell\{background:linear-gradient\(180deg,#8fd5ff/)
    expect(css).toMatch(/html\[data-theme="light"\] \.launch-shell\{background:#fff/)
    expect(css).toMatch(/html\[data-theme="light"\] \.atmosphere \.sky\{background:#fff/)
    expect(css).not.toMatch(/html\[data-theme="light"\] \.atmosphere \.sky\{background:linear-gradient\(180deg,#79caff/)
    expect(css).toMatch(/html\[data-theme="light"\] \.project-hero\{background:#fff/)
    expect(css).toMatch(/html\[data-theme="light"\] \.session-shell>\.main/)
  })
})
