package webviewhost

import (
	"net/url"
	"path"
	"strings"
)

// An HTML artifact is generated by a model and then read by a human who
// reasonably expects it to behave like a web page: menus that switch views,
// data that persists. Running it inside the application document is not an
// option — that document holds the bridge, and therefore the user's files,
// models and keys. So previews get their own origin.
//
// preview.lunitide.local is cross-origin to app.lunitide.local, which is what
// makes this safe: the framed page cannot read the application's storage, reach
// into its DOM, or post to the bridge (the gateway answers only the trusted
// origin, and only the top frame). What it CAN do is run its own scripts and
// keep its own localStorage, because the headers below are set by the host, and
// a document can never widen a policy delivered with its response.
const (
	PreviewVirtualHost       = "preview.lunitide.local"
	PreviewOrigin            = "https://" + PreviewVirtualHost
	PreviewPathPrefix        = "/p/"
	PreviewResourceFilterURI = PreviewOrigin + PreviewPathPrefix + "*"

	// A ticket is minted per preview and expires; it is the only way to name a
	// file on this origin, so guessing one must be infeasible.
	previewTokenMin = 22
	previewTokenMax = 64
	// Relative paths address sibling assets of the previewed document
	// (stylesheets, scripts, images). Long enough for real folder layouts,
	// short enough that nothing can smuggle a path through sheer length.
	previewRelMax = 400
)

// PreviewDocumentURL is the address the renderer frames. Sibling assets resolve
// relative to it, so a generated multi-file site loads its own CSS and JS.
func PreviewDocumentURL(token, rel string) string {
	if token == "" {
		return ""
	}
	url := PreviewOrigin + PreviewPathPrefix + token + "/"
	if clean, ok := cleanPreviewRel(rel); ok && clean != "" {
		url += clean
	}
	return url
}

// ParsePreviewRequest accepts only https://preview.lunitide.local/p/<token>/<rel>
// and returns the ticket plus the requested relative path ("" means the ticket's
// own document). A query string is allowed and ignored — generated pages use one
// for their own routing — but it can never influence which file is served.
func ParsePreviewRequest(raw string) (token, rel string, ok bool) {
	u, err := url.Parse(raw)
	if err != nil || u.Scheme != "https" || u.User != nil || u.Opaque != "" {
		return "", "", false
	}
	// Host must match exactly: no port, no trailing dot, no suffix that merely
	// ends in our name (preview.lunitide.local.evil).
	if strings.ToLower(u.Host) != PreviewVirtualHost {
		return "", "", false
	}
	// EscapedPath keeps %2e%2e visible; decode once through u.Path and validate
	// the decoded form, so a single or double encoding cannot escape the root.
	if !strings.HasPrefix(u.Path, PreviewPathPrefix) {
		return "", "", false
	}
	rest := strings.TrimPrefix(u.Path, PreviewPathPrefix)
	token, remainder, _ := strings.Cut(rest, "/")
	if !validPreviewToken(token) {
		return "", "", false
	}
	clean, valid := cleanPreviewRel(remainder)
	if !valid {
		return "", "", false
	}
	return token, clean, true
}

func validPreviewToken(token string) bool {
	if len(token) < previewTokenMin || len(token) > previewTokenMax {
		return false
	}
	for _, c := range token {
		switch {
		case c >= 'a' && c <= 'z', c >= 'A' && c <= 'Z', c >= '0' && c <= '9', c == '-', c == '_':
		default:
			return false
		}
	}
	return true
}

// cleanPreviewRel normalizes a slash-relative asset path and rejects anything
// that could address a file outside the previewed document's folder. The engine
// re-validates containment against the session root as well; this is the first
// gate, not the only one.
func cleanPreviewRel(raw string) (string, bool) {
	if raw == "" {
		return "", true
	}
	// A colon is never part of a web asset path, and on Windows it names a drive
	// ("C:/Windows") or an NTFS alternate data stream ("index.html:payload").
	// Backslash is a separator there too. Neither may survive into a file join.
	if len(raw) > previewRelMax || strings.ContainsAny(raw, "\x00\\:") {
		return "", false
	}
	for _, c := range raw {
		if c < 0x20 || c == 0x7f {
			return "", false
		}
	}
	if strings.HasPrefix(raw, "/") {
		return "", false
	}
	clean := path.Clean(raw)
	if clean == "." || clean == "/" {
		return "", true
	}
	// Clean resolves interior traversal; anything still climbing is an escape,
	// and an absolute result means the input was absolute in disguise.
	if clean == ".." || strings.HasPrefix(clean, "../") || strings.HasPrefix(clean, "/") {
		return "", false
	}
	for _, segment := range strings.Split(clean, "/") {
		if segment == "" || segment == "." || segment == ".." {
			return "", false
		}
	}
	return clean, true
}

// PreviewResponseHeaders is the whole isolation story, delivered with every
// preview byte. CSP composes by intersection, so a generated document cannot
// loosen any of this by writing its own <meta> policy:
//
//   - scripts and inline styles are allowed, which is the point: menus work,
//     layout is faithful, localStorage works (a real origin, unlike a sandboxed
//     opaque one where storage access throws).
//   - connect-src 'none' and form-action 'none' mean no fetch, XHR, WebSocket,
//     EventSource, beacon or form post. The page cannot send anything anywhere,
//     so executing it cannot leak the data it was built from.
//   - frame-ancestors pins it inside our application document, and frame-src
//     'none' stops it framing anything else.
func PreviewResponseHeaders(contentType string) string {
	if contentType == "" {
		contentType = "application/octet-stream"
	}
	return strings.Join([]string{
		"Content-Type: " + contentType,
		"Content-Security-Policy: " + PreviewContentPolicy,
		"X-Content-Type-Options: nosniff",
		"Referrer-Policy: no-referrer",
		"Cache-Control: no-store",
		"Cross-Origin-Resource-Policy: same-origin",
	}, "\r\n")
}

// PreviewContentPolicy is exported so the renderer contract test can assert the
// shell's frame-src and this policy stay compatible.
const PreviewContentPolicy = "default-src 'none'; " +
	"script-src 'self' 'unsafe-inline' 'unsafe-eval'; " +
	"style-src 'self' 'unsafe-inline'; " +
	"img-src 'self' data: blob:; " +
	"font-src 'self' data:; " +
	"media-src 'self' data: blob:; " +
	"connect-src 'none'; " +
	"form-action 'none'; " +
	"base-uri 'none'; " +
	"frame-src 'none'; " +
	"object-src 'none'; " +
	"frame-ancestors " + TrustedOrigin

// PreviewDeniedHeaders answer a rejected request. They carry the same policy so
// an error body can never be mistaken for a licence to do more.
func PreviewDeniedHeaders() string {
	return PreviewResponseHeaders("text/plain; charset=utf-8")
}

// PreviewContentType maps a file extension to a MIME type. An unknown
// extension is served as a download-neutral octet-stream under nosniff, so it
// cannot be coaxed into executing as script or markup.
func PreviewContentType(name string) string {
	switch strings.ToLower(strings.TrimPrefix(path.Ext(name), ".")) {
	case "html", "htm":
		return "text/html; charset=utf-8"
	case "css":
		return "text/css; charset=utf-8"
	case "js", "mjs":
		return "text/javascript; charset=utf-8"
	case "json":
		return "application/json; charset=utf-8"
	case "svg":
		return "image/svg+xml"
	case "png":
		return "image/png"
	case "jpg", "jpeg":
		return "image/jpeg"
	case "gif":
		return "image/gif"
	case "webp":
		return "image/webp"
	case "ico":
		return "image/x-icon"
	case "woff2":
		return "font/woff2"
	case "woff":
		return "font/woff"
	case "ttf":
		return "font/ttf"
	case "txt", "md", "csv":
		return "text/plain; charset=utf-8"
	case "wav":
		return "audio/wav"
	case "mp3":
		return "audio/mpeg"
	case "mp4":
		return "video/mp4"
	default:
		return "application/octet-stream"
	}
}

// PreviewRequestAllowed mirrors MediaResourceAllowed: only our own application
// document may pull from this origin, and only as a subresource/document load.
func PreviewRequestAllowed(source string, uri string) bool {
	if !NavigationAllowed(source) {
		return false
	}
	_, _, ok := ParsePreviewRequest(uri)
	return ok
}
