import React,{useEffect,useRef,useState}from'react'
import{BridgeClientError,createMutationAttempt,type MutationAttempt,type ProjectBridge}from'../bridge/client'
import type{ProjectCreatePayload,ProjectDTO,ProjectDeletePayload}from'../generated/bridge'

export const normalizeProjectName=(raw:string):string=>raw.split(/\p{White_Space}+/u).filter(Boolean).join(' ')
const problem=(e:unknown)=>e instanceof BridgeClientError?e:new BridgeClientError(e instanceof Error?e.message:'请求失败','CLIENT_ERROR',false,'renderer')
type Retained={signature:string;attempt:MutationAttempt<ProjectCreatePayload>}

const orderedProjects=(values:ProjectDTO[]):ProjectDTO[]=>[...values].sort((a,b)=>a.createdAt.localeCompare(b.createdAt)||a.id.localeCompare(b.id))

export function ProjectPage({bridge,onSelect}:{bridge:ProjectBridge;onSelect?:(project:ProjectDTO)=>void}):React.JSX.Element{
 const[items,setItems]=useState<ProjectDTO[]>([]),[name,setName]=useState(''),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[loadError,setLoadError]=useState<BridgeClientError>(),[createError,setCreateError]=useState<BridgeClientError>(),[notice,setNotice]=useState('')
 const mounted=useRef(true),loadToken=useRef(0),busyRef=useRef(false),retained=useRef<Retained|undefined>(undefined),deleteToken=useRef(0)
 const load=async()=>{const token=++loadToken.current;setLoading(true);try{const result=await bridge.list();if(mounted.current&&token===loadToken.current){setItems(orderedProjects(result.items));setLoadError(undefined)}}catch(e){if(mounted.current&&token===loadToken.current)setLoadError(problem(e))}finally{if(mounted.current&&token===loadToken.current)setLoading(false)}}
 useEffect(()=>{mounted.current=true;void load();return()=>{mounted.current=false;loadToken.current++}},[])
 const submit=async(e:React.FormEvent)=>{e.preventDefault();if(busyRef.current)return;const normalized=normalizeProjectName(name);if(!normalized){setNotice('请输入项目名称');return}if(Array.from(normalized).length>200){setNotice('项目名称最多 200 个 Unicode 字符');return}const payload:ProjectCreatePayload={name:normalized},signature=JSON.stringify(payload);const attempt=retained.current?.signature===signature?retained.current.attempt:createMutationAttempt('project.create',payload);retained.current={signature,attempt};busyRef.current=true;setBusy(true);setName(normalized);setCreateError(undefined);setNotice('');try{const created=await bridge.create(attempt.payload as ProjectCreatePayload,{attempt});if(mounted.current){retained.current=undefined;setItems(current=>orderedProjects([...current.filter(item=>item.id!==created.id),created]));setName('');setNotice('项目已创建')}}catch(e){const issue=problem(e);if(mounted.current){setCreateError(issue);if(!issue.retryable)retained.current=undefined}}finally{if(mounted.current){busyRef.current=false;setBusy(false)}}}
 const del=async(id:string,name:string)=>{if(busyRef.current)return;if(!window.confirm(`确定删除项目「${name}」？所有会话、消息和附件将被永久删除。`))return;const token=++deleteToken.current;busyRef.current=true;setBusy(true);try{const attempt=createMutationAttempt('project.delete',{id});await bridge.delete(attempt.payload as ProjectDeletePayload,{attempt});if(mounted.current&&token===deleteToken.current){setItems(current=>current.filter(item=>item.id!==id));setNotice('项目已删除')}}catch(e){if(mounted.current&&token===deleteToken.current){const issue=problem(e);setLoadError(issue)}}finally{if(mounted.current&&token===deleteToken.current){busyRef.current=false;setBusy(false)}}}
 return <div className="shell project-page"><header className="brand"><div><p className="eyebrow">LOCAL-FIRST WORKSPACE</p><h1>项目</h1><p>创建并管理你的本地工作空间。</p></div></header><div className="project-layout"><section className="project-create"><h2>新建项目</h2><form onSubmit={e=>void submit(e)}><fieldset disabled={busy}><label>项目名称<input value={name} onChange={e=>{setName(e.target.value);retained.current=undefined}} aria-describedby="project-name-help"/></label><small id="project-name-help">空白会合并为单个空格，最多 200 个 Unicode 字符；新项目初始为活跃状态。</small><button className="primary" disabled={busy}>{busy?'创建中…':'创建项目'}</button></fieldset></form>{notice&&<p className="notice" role="status">{notice}</p>}{createError&&<ErrorBox error={createError}/>}</section><section className="project-list" aria-labelledby="projects-heading"><div className="aside-title"><h2 id="projects-heading">项目列表</h2><button aria-label="刷新项目" disabled={busy||loading} onClick={()=>void load()}>↻</button></div>{loading&&!items.length?<p role="status">正在载入项目…</p>:loadError&&!items.length?<ErrorBox error={loadError} retry={load}/>:!items.length?<div className="empty"><b>还没有项目</b><span>创建第一个项目开始使用。</span></div>:<><div className="project-cards">{items.map(item=><article key={item.id} className="project-card" onClick={()=>onSelect?.(item)}><div><h3>{item.name}</h3><span className={`pill project-${item.status}`}>{item.status==='active'?'活跃':'已归档'}</span></div><p>版本 {item.version} · 更新于 {new Date(item.updatedAt).toLocaleString()}</p><button className="card-delete" aria-label={`删除项目 ${item.name}`} disabled={busy} onClick={e=>{e.stopPropagation();void del(item.id,item.name)}}>删除</button></article>)}</div>{loadError&&<ErrorBox error={loadError} retry={load}/>}</>}</section></div></div>
}
function ErrorBox({error,retry}:{error:BridgeClientError;retry?:()=>void}){return <div className="error" role="alert"><b>{error.message}</b><span>代码 {error.code} · 关联 {error.correlationId}{error.retryable?' · 可重试':''}</span>{retry&&<button onClick={retry}>重试</button>}</div>}
