import React,{useEffect,useMemo,useRef,useState}from'react'
import{BridgeClientError,createMutationAttempt,type MutationAttempt,type ProjectBridge}from'../bridge/client'
import type{ProjectClosePayload,ProjectCreatePayload,ProjectDTO,ProjectPublishPayload,ProjectReopenPayload,ProjectType,ProjectUpdatePayload}from'../generated/bridge'
import{ConfirmDialog,Dialog}from'../ui/Dialog'
import{canClose,canDelete,canEnterWorkbench,canPublish,isReadOnly,normalizeStatus,statusLabel}from'./projectStatus'

export const normalizeProjectName=(raw:string):string=>raw.split(/\p{White_Space}+/u).filter(Boolean).join(' ')
const problem=(e:unknown)=>e instanceof BridgeClientError?e:new BridgeClientError(e instanceof Error?e.message:'请求失败','CLIENT_ERROR',false,'renderer')

const TYPE_LABELS:Record<ProjectType,string>={implementation:'实施项目',operations:'运维项目',enhancement:'增强项目'}
const orderedProjects=(values:ProjectDTO[]):ProjectDTO[]=>[...values].sort((a,b)=>b.updatedAt.localeCompare(a.updatedAt)||b.id.localeCompare(a.id))
const dateInput=(value:string|undefined)=>value??''
const amountText=(value:number|undefined)=>value&&value>0?String(value):''

interface ProjectForm{name:string;type:ProjectType;description:string;summary:string;objective:string;client:string;contractNo:string;amount:string;budget:string;planStart:string;planEnd:string;remark:string}
const emptyForm=(type:ProjectType):ProjectForm=>({name:'',type,description:'',summary:'',objective:'',client:'',contractNo:'',amount:'',budget:'',planStart:'',planEnd:'',remark:''})
const formFromProject=(p:ProjectDTO):ProjectForm=>({name:p.name,type:p.type,description:p.description??'',summary:p.summary??'',objective:p.objective??'',client:p.client??'',contractNo:p.contractNo??'',amount:amountText(p.amount),budget:amountText(p.budget),planStart:dateInput(p.planStart),planEnd:dateInput(p.planEnd),remark:p.remark??''})

const defaultProjectType=():ProjectType=>{try{const raw=localStorage.getItem('lunitide:project-defaults');if(raw){const parsed=JSON.parse(raw) as {type?:string};if(parsed.type==='implementation'||parsed.type==='operations'||parsed.type==='enhancement')return parsed.type}}catch{}return'implementation'}
const isDate=(v:string)=>/^\d{4}-\d{2}-\d{2}$/.test(v)

function validateForm(form:ProjectForm):string{
  if(!normalizeProjectName(form.name))return'请输入项目名称（C）'
  if(Array.from(normalizeProjectName(form.name)).length>200)return'项目名称最多 200 个字符'
  if(!form.description.trim())return'请输入项目描述（D）'
  if(!form.client.trim())return'请输入客户（G）'
  if(!isDate(form.planStart))return'请选择计划开始日期（K）'
  if(!isDate(form.planEnd))return'请选择计划完成日期（L）'
  if(form.planEnd<form.planStart)return'计划完成日期不能早于开始日期'
  if(form.amount&&(!/^\d+(\.\d{1,2})?$/.test(form.amount)||Number(form.amount)<0))return'项目金额需为非负数字（I）'
  if(form.budget&&(!/^\d+(\.\d{1,2})?$/.test(form.budget)||Number(form.budget)<0))return'项目预算需为非负数字（J）'
  return''
}

const formPayload=(form:ProjectForm)=>({name:normalizeProjectName(form.name),type:form.type,description:form.description.trim(),summary:form.summary.trim(),objective:form.objective.trim(),client:form.client.trim(),contractNo:form.contractNo.trim(),amount:form.amount?Number(form.amount):0,budget:form.budget?Number(form.budget):0,planStart:form.planStart,planEnd:form.planEnd,remark:form.remark.trim()})

export function ProjectPage({bridge,onSelect,hiddenProjectName}:{bridge:ProjectBridge;onSelect?:(project:ProjectDTO)=>void;hiddenProjectName?:string}):React.JSX.Element{
 const[items,setItems]=useState<ProjectDTO[]>([]),[query,setQuery]=useState(''),[typeFilter,setTypeFilter]=useState<'all'|ProjectType>('all'),[statusFilter,setStatusFilter]=useState<'all'|string>('all'),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[loadError,setLoadError]=useState<BridgeClientError>(),[actionError,setActionError]=useState<BridgeClientError>(),[notice,setNotice]=useState('')
 const[editorOpen,setEditorOpen]=useState<false|{mode:'create'}|{mode:'edit';project:ProjectDTO}>(),[form,setForm]=useState<ProjectForm>(()=>emptyForm(defaultProjectType())),[formError,setFormError]=useState('')
 const[publishTarget,setPublishTarget]=useState<ProjectDTO>(),[closeTarget,setCloseTarget]=useState<ProjectDTO>(),[reopenTarget,setReopenTarget]=useState<ProjectDTO>(),[reason,setReason]=useState(''),[deleteTarget,setDeleteTarget]=useState<ProjectDTO>()
 const mounted=useRef(true),loadToken=useRef(0),busyRef=useRef(false),retained=useRef<{signature:string;attempt:MutationAttempt<ProjectCreatePayload>|MutationAttempt<ProjectUpdatePayload>}|undefined>(undefined)
 const load=async()=>{const token=++loadToken.current;setLoading(true);try{const result=await bridge.list();if(mounted.current&&token===loadToken.current){setItems(orderedProjects(result.items.filter(item=>item.name!==hiddenProjectName&&normalizeStatus(item.status)!=='archived')));setLoadError(undefined)}}catch(e){if(mounted.current&&token===loadToken.current)setLoadError(problem(e))}finally{if(mounted.current&&token===loadToken.current)setLoading(false)}}
 useEffect(()=>{mounted.current=true;void load();return()=>{mounted.current=false;loadToken.current++}},[])
 useEffect(()=>{if(notice){const t=window.setTimeout(()=>setNotice(''),2500);return()=>window.clearTimeout(t)}},[notice])
 const patch=<K extends keyof ProjectForm>(key:K,value:ProjectForm[K])=>{retained.current=undefined;setForm(current=>({...current,[key]:value}))}
 const openCreate=()=>{retained.current=undefined;setForm(emptyForm(defaultProjectType()));setFormError('');setEditorOpen({mode:'create'})}
 const openEdit=(project:ProjectDTO)=>{retained.current=undefined;setForm(formFromProject(project));setFormError('');setEditorOpen({mode:'edit',project})}
 const submitForm=async(e:React.FormEvent)=>{e.preventDefault();if(busyRef.current)return;const issue=validateForm(form);if(issue){setFormError(issue);return}const editing=editorOpen&&editorOpen.mode==='edit'?editorOpen.project:undefined;const base=formPayload(form);const signature=JSON.stringify({id:editing?.id,version:editing?.version,method:editing?'project.update':'project.create',...base});const attempt=retained.current?.signature===signature?retained.current.attempt:editing?createMutationAttempt('project.update',{id:editing.id,version:editing.version,...base} as ProjectUpdatePayload):createMutationAttempt('project.create',base as ProjectCreatePayload);retained.current={signature,attempt};busyRef.current=true;setBusy(true);setFormError('');try{const saved=editing?await bridge.update(attempt.payload as ProjectUpdatePayload,{attempt:attempt as MutationAttempt<ProjectUpdatePayload>}):await bridge.create(attempt.payload as ProjectCreatePayload,{attempt:attempt as MutationAttempt<ProjectCreatePayload>});retained.current=undefined;if(mounted.current){setItems(current=>orderedProjects([...current.filter(item=>item.id!==saved.id),saved]));setEditorOpen(false);setNotice(editing?'项目已保存':`项目已创建，编号 ${saved.projectCode}`)}}catch(err){const failure=problem(err);if(!failure.retryable)retained.current=undefined;if(mounted.current)setFormError(failure.message)}finally{busyRef.current=false;if(mounted.current)setBusy(false)}}
 const runLifecycle=async(method:'publish'|'close'|'reopen',payload:ProjectPublishPayload|ProjectClosePayload|ProjectReopenPayload&{reason?:string})=>{if(busyRef.current)return;busyRef.current=true;setBusy(true);setActionError(undefined);try{const saved=await(async()=>{if(method==='publish'){const attempt=createMutationAttempt('project.publish',payload as ProjectPublishPayload);return bridge.publish(attempt.payload,{attempt})}if(method==='close'){const attempt=createMutationAttempt('project.close',payload as ProjectClosePayload);return bridge.close(attempt.payload,{attempt})}const attempt=createMutationAttempt('project.reopen',payload as ProjectReopenPayload&{reason:string});return bridge.reopen(attempt.payload as ProjectReopenPayload&{reason:string},{attempt})})();if(mounted.current){setItems(current=>orderedProjects(current.map(item=>item.id===saved.id?saved:item)));setPublishTarget(undefined);setCloseTarget(undefined);setReopenTarget(undefined);setReason('');setNotice(method==='publish'?`已发布 ${saved.projectCode}，现在可以进入工作台`:method==='close'?'项目已关闭，转为只读':'项目已重新打开')}}catch(err){if(mounted.current)setActionError(problem(err))}finally{busyRef.current=false;if(mounted.current)setBusy(false)}}
 const del=async()=>{if(busyRef.current||!deleteTarget)return;const{id}=deleteTarget;const attempt=createMutationAttempt('project.delete',{id});busyRef.current=true;setBusy(true);try{await bridge.delete(attempt.payload as {id:string},{attempt});if(mounted.current){setItems(current=>current.filter(item=>item.id!==id));setNotice('项目已删除');setDeleteTarget(undefined)}}catch(err){if(mounted.current)setActionError(problem(err))}finally{busyRef.current=false;if(mounted.current)setBusy(false)}}
 const filtered=useMemo(()=>items.filter(item=>(typeFilter==='all'||item.type===typeFilter)&&(statusFilter==='all'||normalizeStatus(item.status)===normalizeStatus(statusFilter)||(statusFilter==='chartered'&&normalizeStatus(item.status)==='chartered'))&&(!query.trim()||`${item.name} ${item.projectCode} ${item.client??''}`.toLocaleLowerCase().includes(query.trim().toLocaleLowerCase()))),[items,typeFilter,statusFilter,query])
 const editing=editorOpen&&editorOpen.mode==='edit'?editorOpen.project:undefined
 return <div className="shell project-page pm-shell"><header className="project-hero"><div><p className="eyebrow">PROJECT MANAGEMENT</p><h1>项目管理</h1><p>管理项目的完整生命周期：创建、发布、进入工作台、关闭与归档。</p></div><div className="project-hero-art" aria-hidden="true"><span>◇</span><span>◌</span><span>□</span><i/></div></header>
 <section className="pm-body" aria-labelledby="pm-heading"><div className="pm-toolbar"><h2 id="pm-heading">项目清单</h2><label className="pm-search"><span aria-hidden="true">⌕</span><input aria-label="搜索项目" placeholder="搜索项目名称、ITM编号或客户…" value={query} onChange={e=>setQuery(e.target.value)}/></label><label className="pm-filter">类型<select aria-label="筛选项目类型" value={typeFilter} onChange={e=>setTypeFilter(e.target.value as 'all'|ProjectType)}><option value="all">全部类型</option><option value="implementation">实施项目</option><option value="operations">运维项目</option><option value="enhancement">增强项目</option></select></label><label className="pm-filter">状态<select aria-label="筛选项目状态" value={statusFilter} onChange={e=>setStatusFilter(e.target.value)}><option value="all">全部状态</option><option value="created">创建</option><option value="chartered">立项</option><option value="req_architecture">需求架构规范</option><option value="req_assessment">需求评估</option><option value="in_progress">实施中</option><option value="integration_test">集成测试</option><option value="go_live_prep">上线准备</option><option value="live">系统上线</option><option value="closed">项目关闭</option></select></label><button aria-label="刷新项目" disabled={busy||loading} onClick={()=>void load()}>↻</button><button className="primary" onClick={openCreate}>＋ 创建项目</button></div>
 <p className="gate-note">动作门禁：创建状态仅可修改、发布或删除，不能进入工作台；发布确认后进入工作台可用。关闭项目需填写关闭原因；打开项目需填写原因并恢复关闭前状态。关闭后只读；删除仅限无产出的创建态项目。</p>
 {notice&&<p className="notice project-notice" role="status">{notice}</p>}
 {actionError&&<div className="error" role="alert"><b>{actionError.message}</b><span>代码 {actionError.code}</span><button onClick={()=>setActionError(undefined)}>关闭</button></div>}
 {loading&&!items.length?<p role="status">正在载入项目…</p>:loadError&&!items.length?<ErrorBox error={loadError} retry={load}/>:!filtered.length?<div className="empty"><b>{items.length?'没有符合筛选条件的项目':'还没有项目'}</b><span>{items.length?'调整搜索或筛选条件试试。':'点击“创建项目”，按 A–N 字段录入项目信息。'}</span></div>:
 <ul className="pm-list">{filtered.map(item=>{const norm=normalizeStatus(item.status),created=norm==='created',workbench=canEnterWorkbench(item.status),closed=isReadOnly(item.status),publishable=canPublish(item.status),closable=canClose(item.status,item.type),deletable=canDelete(item.status);return <li key={item.id} className={`pm-item status-${norm}`}><div className="pm-item-main"><button type="button" className="pm-item-open" onClick={()=>{if(workbench)onSelect?.(item)}} disabled={!workbench} title={created?'创建态项目需先立项才能进入工作台':'进入项目'}><span className={`pm-dot status-${norm}`} aria-hidden="true"/><span className="pm-item-title"><b>{item.name}</b><small>{item.projectCode}{item.client?` · ${item.client}`:''}{item.contractNo?` · ${item.contractNo}`:''}</small></span></button><span className="pm-item-meta"><i className="pm-chip">{TYPE_LABELS[item.type]}</i><i className={`pm-chip status-${norm}`}>{statusLabel(item.status,item.type)}</i><i className="pm-chip mono">v{item.version}{created?' · 未立项':closed?' · 已锁版':''}</i><time>{item.planStart&&item.planEnd?`${item.planStart} ~ ${item.planEnd}`:`更新 ${new Date(item.updatedAt).toLocaleDateString()}`}</time></span><span className="pm-item-actions">{workbench&&!closed&&<button className="primary" onClick={()=>onSelect?.(item)}>进入工作台</button>}{closed&&<button onClick={()=>onSelect?.(item)}>只读进入</button>}{publishable&&<button className="primary" onClick={()=>setPublishTarget(item)}>发布</button>}{!closed&&<button onClick={()=>openEdit(item)}>修改</button>}{closable&&<button onClick={()=>{setCloseTarget(item);setReason('')}}>关闭</button>}{norm==='closed'&&<button onClick={()=>{setReopenTarget(item);setReason('')}}>打开</button>}{deletable&&<button className="danger" onClick={()=>setDeleteTarget(item)}>删除</button>}{!deletable&&<button className="danger" disabled title={created?'':'已关闭或进行中的项目保留审计记录，不支持删除'}>删除</button>}</span></div></li>})}</ul>}
 {loadError&&items.length>0&&<ErrorBox error={loadError} retry={load}/>}
 </section>
 <Dialog open={!!editorOpen} wide title={editing?`修改项目 · ${editing.projectCode}`:'创建项目 · A–N'} onClose={()=>{if(!busy)setEditorOpen(false)}}>
  <form className="project-editor-dialog" onSubmit={e=>void submitForm(e)}><fieldset disabled={busy}>
   <div className="form-grid">
    <label>A 项目编号<input value={editing?editing.projectCode:'保存时自动生成 ITMxxxxx'} disabled/></label>
    <label>B 项目类型 *<select value={form.type} disabled={!!editing&&normalizeStatus(editing.status)!=='created'} onChange={e=>patch('type',e.target.value as ProjectType)}><option value="implementation">实施项目</option><option value="operations">运维项目</option><option value="enhancement">增强项目</option></select></label>
    <label>C 项目名称 *<input autoFocus value={form.name} maxLength={200} disabled={!!editing&&normalizeStatus(editing.status)!=='created'} placeholder="例如：在线商城系统" onChange={e=>patch('name',e.target.value)}/></label>
    <label>G 客户 *<input value={form.client} maxLength={200} placeholder="客户名称" onChange={e=>patch('client',e.target.value)}/></label>
    <label className="wide">D 项目描述 *<textarea rows={2} maxLength={2000} placeholder="建设面向客户的…" value={form.description} onChange={e=>patch('description',e.target.value)}/></label>
    <label className="wide">E 项目简介<textarea rows={2} maxLength={500} placeholder="一句话简介" value={form.summary} onChange={e=>patch('summary',e.target.value)}/></label>
    <label className="wide">F 项目目标<textarea rows={2} maxLength={2000} placeholder="完成设计、开发、测试与上线" value={form.objective} onChange={e=>patch('objective',e.target.value)}/></label>
    <label>H 合同编号<input value={form.contractNo} maxLength={100} placeholder="HT-2026-000" onChange={e=>patch('contractNo',e.target.value)}/></label>
    <label>I 项目金额（元）<input inputMode="decimal" value={form.amount} placeholder="0.00" onChange={e=>patch('amount',e.target.value)}/></label>
    <label>J 项目预算成本（元）<input inputMode="decimal" value={form.budget} placeholder="0.00" onChange={e=>patch('budget',e.target.value)}/></label>
    <label>M 项目状态<input value={editing?statusLabel(editing.status,editing.type):'创建'} disabled/></label>
    <label className="form-pair"><span>K 计划开始日期 *</span><span>L 计划完成日期 *</span></label>
    <label className="form-pair"><input type="date" value={form.planStart} onChange={e=>patch('planStart',e.target.value)}/><input type="date" value={form.planEnd} onChange={e=>patch('planEnd',e.target.value)}/></label>
    <label className="wide">N 阶段文档附件<div className="pm-attachment-note">新建时为空；保存后按需求架构规范、方案和UI设计、数据库、接口、开发、测试、集成、发布分类上传、下载和版本替换。</div></label>
    <label className="wide">O 项目备注<textarea rows={2} maxLength={2000} placeholder="客户环境与上线窗口待确认" value={form.remark} onChange={e=>patch('remark',e.target.value)}/></label>
   </div>
   {formError&&<p className="error" role="alert"><b>{formError}</b></p>}
  </fieldset><div className="dialog-actions"><button type="button" disabled={busy} onClick={()=>setEditorOpen(false)}>取消</button><button className="primary" disabled={busy}>{busy?'保存中…':'保存项目'}</button></div></form>
 </Dialog>
 <Dialog open={!!publishTarget} title={`发布项目 ${publishTarget?.projectCode??''}`} onClose={()=>{if(!busy)setPublishTarget(undefined)}}><div className="pm-confirm"><p><b>{publishTarget?.name}</b></p><p>确定是否发布执行该项目？</p><p className="gate-note">确认后项目状态由“创建”变更为“立项”，且“进入工作台”按钮启用。</p>{actionError&&<p className="error" role="alert"><b>{actionError.message}</b></p>}<div className="dialog-actions"><button disabled={busy} onClick={()=>setPublishTarget(undefined)}>取消</button><button className="primary" disabled={busy} onClick={()=>publishTarget&&void runLifecycle('publish',{id:publishTarget.id,version:publishTarget.version})}>{busy?'发布中…':'确认发布'}</button></div></div></Dialog>
 <Dialog open={!!closeTarget} title={`关闭项目 ${closeTarget?.projectCode??''}`} onClose={()=>{if(!busy)setCloseTarget(undefined)}}><div className="pm-confirm"><p>关闭原因（必填，最多 500 字）</p><textarea className="pm-reason" rows={3} maxLength={500} value={reason} onChange={e=>setReason(e.target.value)} placeholder="填写关闭原因，关闭前状态将被记录"/><p className="gate-note">关闭后项目转为只读；可通过“打开项目”填写原因后恢复。</p>{actionError&&<p className="error" role="alert"><b>{actionError.message}</b></p>}<div className="dialog-actions"><button disabled={busy} onClick={()=>setCloseTarget(undefined)}>取消</button><button className="primary" disabled={busy||!reason.trim()} onClick={()=>closeTarget&&void runLifecycle('close',{id:closeTarget.id,version:closeTarget.version,reason:reason.trim()})}>{busy?'关闭中…':'确认关闭'}</button></div></div></Dialog>
 <Dialog open={!!reopenTarget} title={`打开项目 ${reopenTarget?.projectCode??''}`} onClose={()=>{if(!busy)setReopenTarget(undefined)}}><div className="pm-confirm"><p>打开原因（必填，最多 500 字）</p><textarea className="pm-reason" rows={3} maxLength={500} value={reason} onChange={e=>setReason(e.target.value)} placeholder="填写打开原因，项目将恢复为关闭前状态"/><p className="gate-note">确认后项目恢复关闭前业务状态，可继续修改与进入工作台。</p>{actionError&&<p className="error" role="alert"><b>{actionError.message}</b></p>}<div className="dialog-actions"><button disabled={busy} onClick={()=>setReopenTarget(undefined)}>取消</button><button className="primary" disabled={busy||!reason.trim()} onClick={()=>reopenTarget&&void runLifecycle('reopen',{id:reopenTarget.id,version:reopenTarget.version,reason:reason.trim()})}>{busy?'打开中…':'确认打开'}</button></div></div></Dialog>
 <ConfirmDialog open={!!deleteTarget} title={`删除项目「${deleteTarget?.name??''}」？`} description="仅创建态且无阶段产出的项目可删除。删除后不再显示在项目清单中，数据库保留归档记录。" busy={busy} onCancel={()=>setDeleteTarget(undefined)} onConfirm={()=>void del()}/>
 </div>
}
function ErrorBox({error,retry}:{error:BridgeClientError;retry?:()=>void}){return <div className="error" role="alert"><b>{error.message}</b><span>代码 {error.code} · 关联 {error.correlationId}{error.retryable?' · 可重试':''}</span>{retry&&<button onClick={retry}>重试</button>}</div>}
