import React,{useEffect,useRef,useState}from'react'
import{BridgeClientError,createMutationAttempt,type MutationAttempt,type ProjectBridge}from'../bridge/client'
import type{ProjectCreatePayload,ProjectDTO,ProjectDeletePayload}from'../generated/bridge'
import{ConfirmDialog,Dialog}from'../ui/Dialog'

export const normalizeProjectName=(raw:string):string=>raw.split(/\p{White_Space}+/u).filter(Boolean).join(' ')
const problem=(e:unknown)=>e instanceof BridgeClientError?e:new BridgeClientError(e instanceof Error?e.message:'请求失败','CLIENT_ERROR',false,'renderer')
type Retained={signature:string;attempt:MutationAttempt<ProjectCreatePayload>}

const orderedProjects=(values:ProjectDTO[]):ProjectDTO[]=>[...values].sort((a,b)=>a.createdAt.localeCompare(b.createdAt)||a.id.localeCompare(b.id))

export function ProjectPage({bridge,onSelect,hiddenProjectName}:{bridge:ProjectBridge;onSelect?:(project:ProjectDTO)=>void;hiddenProjectName?:string}):React.JSX.Element{
 const[items,setItems]=useState<ProjectDTO[]>([]),[name,setName]=useState(''),[query,setQuery]=useState(''),[createOpen,setCreateOpen]=useState(false),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[loadError,setLoadError]=useState<BridgeClientError>(),[createError,setCreateError]=useState<BridgeClientError>(),[notice,setNotice]=useState(''),[deleteTarget,setDeleteTarget]=useState<ProjectDTO>()
 const mounted=useRef(true),loadToken=useRef(0),busyRef=useRef(false),retained=useRef<Retained|undefined>(undefined),deleteToken=useRef(0)
 const load=async()=>{const token=++loadToken.current;setLoading(true);try{const result=await bridge.list();if(mounted.current&&token===loadToken.current){setItems(orderedProjects(result.items.filter(item=>item.name!==hiddenProjectName)));setLoadError(undefined)}}catch(e){if(mounted.current&&token===loadToken.current)setLoadError(problem(e))}finally{if(mounted.current&&token===loadToken.current)setLoading(false)}}
 useEffect(()=>{mounted.current=true;void load();return()=>{mounted.current=false;loadToken.current++}},[])
 const submit=async(e:React.FormEvent)=>{e.preventDefault();if(busyRef.current)return;const normalized=normalizeProjectName(name);if(!normalized){setNotice('请输入项目名称');return}if(Array.from(normalized).length>200){setNotice('项目名称最多 200 个 Unicode 字符');return}const payload:ProjectCreatePayload={name:normalized},signature=JSON.stringify(payload);const attempt=retained.current?.signature===signature?retained.current.attempt:createMutationAttempt('project.create',payload);retained.current={signature,attempt};busyRef.current=true;setBusy(true);setName(normalized);setCreateError(undefined);setNotice('');try{const created=await bridge.create(attempt.payload as ProjectCreatePayload,{attempt});if(mounted.current){retained.current=undefined;setItems(current=>orderedProjects([...current.filter(item=>item.id!==created.id),created]));setName('');setCreateOpen(false);setNotice('项目已创建')}}catch(e){const issue=problem(e);if(mounted.current){setCreateError(issue);if(!issue.retryable)retained.current=undefined}}finally{if(mounted.current){busyRef.current=false;setBusy(false)}}}
 const del=async()=>{if(busyRef.current||!deleteTarget)return;const{id}=deleteTarget,token=++deleteToken.current;busyRef.current=true;setBusy(true);try{const attempt=createMutationAttempt('project.delete',{id});await bridge.delete(attempt.payload as ProjectDeletePayload,{attempt});if(mounted.current&&token===deleteToken.current){setItems(current=>current.filter(item=>item.id!==id));setNotice('项目已删除');setDeleteTarget(undefined)}}catch(e){if(mounted.current&&token===deleteToken.current){const issue=problem(e);setLoadError(issue)}}finally{if(mounted.current&&token===deleteToken.current){busyRef.current=false;setBusy(false)}}}
 const filtered=items.filter(item=>item.name.toLocaleLowerCase().includes(query.trim().toLocaleLowerCase()))
 return <div className="shell project-page"><header className="project-hero"><div><p className="eyebrow">PROJECTS</p><h1>项目</h1><p>为长期任务组织对话、附件与工作成果。</p><button className="primary project-create-button" onClick={()=>{setCreateError(undefined);setNotice('');setCreateOpen(true)}}>＋ 新建项目</button></div><div className="project-hero-art" aria-hidden="true"><span>◇</span><span>◌</span><span>□</span><i/></div></header><section className="project-list" aria-labelledby="projects-heading"><div className="project-list-toolbar"><div><h2 id="projects-heading">我的项目</h2><p>{items.length} 个项目 · 点击卡片进入工作区</p></div><label className="project-search"><span aria-hidden="true">⌕</span><input aria-label="搜索项目" placeholder="搜索项目" value={query} onChange={e=>setQuery(e.target.value)}/></label><button aria-label="刷新项目" disabled={busy||loading} onClick={()=>void load()}>↻</button></div>{notice&&<p className="notice project-notice" role="status">{notice}</p>}{loading&&!items.length?<p role="status">正在载入项目…</p>:loadError&&!items.length?<ErrorBox error={loadError} retry={load}/>:!items.length?<div className="empty"><b>还没有项目</b><span>点击“新建项目”开始使用。</span></div>:!filtered.length?<div className="empty compact"><b>没有匹配的项目</b><span>换一个关键词试试。</span></div>:<><div className="project-cards">{filtered.map(item=><article key={item.id} className="project-card"><button className="project-card-main" onClick={()=>onSelect?.(item)}><span className="project-card-icon" aria-hidden="true">◇</span><span><b>{item.name}</b><small>更新于 {new Date(item.updatedAt).toLocaleString()}</small></span><i className={`project-${item.status}`}>{item.status==='active'?'活跃':'已归档'}</i></button><div className="project-card-actions"><button className="project-open" onClick={()=>onSelect?.(item)}>进入项目</button><button className="card-delete" aria-label={`删除项目 ${item.name}`} disabled={busy} onClick={()=>setDeleteTarget(item)}>删除</button></div></article>)}</div>{loadError&&<ErrorBox error={loadError} retry={load}/>}</>}</section><Dialog open={createOpen} title="新建项目" onClose={()=>{if(!busy)setCreateOpen(false)}}><form className="project-create-dialog" onSubmit={e=>void submit(e)}><fieldset disabled={busy}><label>项目名称<input autoFocus value={name} onChange={e=>{setName(e.target.value);retained.current=undefined}} aria-describedby="project-name-help" placeholder="输入项目名称"/></label><small id="project-name-help">最多 200 个字符，新项目初始为活跃状态。</small></fieldset>{createError&&<ErrorBox error={createError}/>} {notice&&<p className="notice" role="status">{notice}</p>}<div className="dialog-actions"><button type="button" disabled={busy} onClick={()=>setCreateOpen(false)}>取消</button><button className="primary" disabled={busy}>{busy?'创建中…':'创建项目'}</button></div></form></Dialog><ConfirmDialog open={!!deleteTarget} title={`删除项目「${deleteTarget?.name??''}」？`} description="所有会话、消息和附件将被永久删除，此操作不可撤销。" busy={busy} onCancel={()=>setDeleteTarget(undefined)} onConfirm={()=>void del()}/></div>
}
function ErrorBox({error,retry}:{error:BridgeClientError;retry?:()=>void}){return <div className="error" role="alert"><b>{error.message}</b><span>代码 {error.code} · 关联 {error.correlationId}{error.retryable?' · 可重试':''}</span>{retry&&<button onClick={retry}>重试</button>}</div>}
