import{cleanup,render,screen,waitFor}from'@testing-library/react'
import userEvent from'@testing-library/user-event'
import{afterEach,expect,it,vi}from'vitest'
import{BridgeClientError,type ProjectBridge}from'../bridge/client'
import type{ProjectDTO}from'../generated/bridge'
import{normalizeProjectName,ProjectPage}from'./ProjectPage'

afterEach(cleanup)
const now='2025-01-01T00:00:00Z',project:ProjectDTO={id:'01ARZ3NDEKTSV4RRFFQ69G5FAV',name:'<img src=x onerror=alert(1)>',status:'active',createdAt:now,updatedAt:now,version:1}
const api=(overrides:Partial<ProjectBridge>={}):ProjectBridge=>({list:vi.fn().mockResolvedValue({items:[]}),create:vi.fn().mockResolvedValue(project),delete:vi.fn().mockResolvedValue({deleted:true,id:'01ARZ3NDEKTSV4RRFFQ69G5FAV'}),...overrides})
it('normalizes Go-style whitespace and counts astral code points',()=>{expect(normalizeProjectName(' \t月\n\u00a0汐 ')).toBe('月 汐');expect(Array.from('😀')).toHaveLength(1)})
it('loads an empty state, opens the create dialog, normalizes create, and renders names as inert text',async()=>{const bridge=api(),user=userEvent.setup();render(<ProjectPage bridge={bridge}/>);expect(await screen.findByText('还没有项目')).toBeInTheDocument();expect(screen.queryByLabelText('项目名称')).not.toBeInTheDocument();await user.click(screen.getByRole('button',{name:/新建项目/}));await user.type(screen.getByLabelText('项目名称'),'  Moon   Tide  ');await user.click(screen.getByRole('button',{name:'创建项目'}));await waitFor(()=>expect(bridge.create).toHaveBeenCalledOnce());expect(vi.mocked(bridge.create).mock.calls[0][0]).toEqual({name:'Moon Tide'});expect(await screen.findByText(project.name)).toBeInTheDocument();expect(document.querySelector('img')).toBeNull()})
it('blocks busy re-entry and retains the same attempt for a retryable retry',async()=>{let reject!:(e:unknown)=>void;const first=new Promise<ProjectDTO>((_,r)=>{reject=r}),create=vi.fn().mockReturnValueOnce(first).mockResolvedValue(project),bridge=api({create}),user=userEvent.setup();render(<ProjectPage bridge={bridge}/>);await screen.findByText('还没有项目');await user.click(screen.getByRole('button',{name:/新建项目/}));await user.type(screen.getByLabelText('项目名称'),'Demo');await user.click(screen.getByRole('button',{name:'创建项目'}));expect(screen.getByRole('button',{name:'创建中…'})).toBeDisabled();expect(create).toHaveBeenCalledOnce();reject(new BridgeClientError('uncertain','TIMEOUT',true,'trace'));expect(await screen.findByText('uncertain')).toBeInTheDocument();await user.click(screen.getByRole('button',{name:'创建项目'}));await waitFor(()=>expect(create).toHaveBeenCalledTimes(2));expect(create.mock.calls[1][1]?.attempt).toBe(create.mock.calls[0][1]?.attempt)})
it('keeps stale projects visible when refresh fails',async()=>{const list=vi.fn().mockResolvedValueOnce({items:[project]}).mockRejectedValueOnce(new BridgeClientError('offline','OFFLINE',true,'trace')),bridge=api({list}),user=userEvent.setup();render(<ProjectPage bridge={bridge}/>);expect(await screen.findByText(project.name)).toBeInTheDocument();await user.click(screen.getByRole('button',{name:'刷新项目'}));expect(await screen.findByText('offline')).toBeInTheDocument();expect(screen.getByText(project.name)).toBeInTheDocument()})
it('inserts a created project in repository createdAt ASC, id ASC order',async()=>{const older={...project,id:'01ARZ3NDEKTSV4RRFFQ69G5FAA',name:'Older'},newer={...project,id:'01ARZ3NDEKTSV4RRFFQ69G5FAC',name:'Newer',createdAt:'2025-01-03T00:00:00Z'},middle={...project,id:'01ARZ3NDEKTSV4RRFFQ69G5FAB',name:'Middle',createdAt:'2025-01-02T00:00:00Z'},bridge=api({list:vi.fn().mockResolvedValue({items:[older,newer]}),create:vi.fn().mockResolvedValue(middle)}),user=userEvent.setup();const{container}=render(<ProjectPage bridge={bridge}/>);await screen.findByText('Older');await user.click(screen.getByRole('button',{name:/新建项目/}));await user.type(screen.getByLabelText('项目名称'),'Middle');await user.click(screen.getByRole('button',{name:'创建项目'}));await screen.findByText('Middle');expect([...container.querySelectorAll('.project-card-main b')].map(node=>node.textContent)).toEqual(['Older','Middle','Newer'])})

it('filters projects and enters from the whole project card',async()=>{const alpha={...project,name:'Alpha'},beta={...project,id:'01ARZ3NDEKTSV4RRFFQ69G5FAZ',name:'Beta'},onSelect=vi.fn(),user=userEvent.setup();render(<ProjectPage bridge={api({list:vi.fn().mockResolvedValue({items:[alpha,beta]})})} onSelect={onSelect}/>);await screen.findByText('Alpha');await user.type(screen.getByLabelText('搜索项目'),'bet');expect(screen.queryByText('Alpha')).not.toBeInTheDocument();await user.click(screen.getAllByRole('button',{name:/Beta/})[0]);expect(onSelect).toHaveBeenCalledWith(beta)})

it('requires the application danger dialog before deleting a project',async()=>{const bridge=api({list:vi.fn().mockResolvedValue({items:[project]})}),user=userEvent.setup();render(<ProjectPage bridge={bridge}/>);await user.click(await screen.findByRole('button',{name:`删除项目 ${project.name}`}));expect(screen.getByRole('dialog',{name:`删除项目「${project.name}」？`})).toBeInTheDocument();expect(bridge.delete).not.toHaveBeenCalled();await user.click(screen.getByRole('button',{name:'确认删除'}));await waitFor(()=>expect(bridge.delete).toHaveBeenCalledOnce());expect(screen.queryByText(project.name)).not.toBeInTheDocument()})
